kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "nim-nai-llm-k8s"
  environment: "non-prod"
  cluster_profile: "nai-llm-k8s"
  gpu_cuda_toolkit_version: "v1.14.3-centos7"
  gpu_operator_version: "v23.9.0"
  gpu_time_slicing_replica_count: "2"
  nginx_ingress_version: "4.8.3"
  istio_version: "10.122.7.204"
  cert_manager_version: "v1.13.5"
  cert_manager_issuer_name: "letsencrypt-issuer"
  model: "llama2_7b_chat"
  revision: "94b07a6e30c3292b8265ed32ffdeccfdadf434a8"
  maxTokens: "4000"
  repPenalty: "1.2"
  temperature: "0.2"
  topP: "0.9"
  useExistingNFS: "true"
  kserve_version: "v0.11.2"
  knative_serving_version: "knative-v1.10.1"
  knative_istio_version: "knative-v1.10.0"
  kyverno_version: "3.1.4"
  weave_gitops_version: "4.0.36"
  jupyterhub_version: "3.1.0"
