apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: milvus
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: kyverno
  - name: cert-manager-resource-configs
  - name: ingress-nginx
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./platform/milvus/_operators
  prune: true
  wait: true
  timeout: 15m
  install:
    remediation:
      retries: 3
  postBuild:
    substitute:
      namespace_name: milvus
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false
  patches:
  # - patch: |-
  #     - op: replace
  #       path: /data/httpNumThreads
  #       value: "100"
  #   target:
  #     kind: ConfigMap
  #     name: milvus-milvus-vectordb-pulsar-proxy
  #     namespace: milvus
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: milvus-vectordb
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/values/pulsar/proxy/configData/httpNumThreads
        value: null
