apiVersion: v1
kind: Namespace
metadata:
  name: milvus
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: milvus
  namespace: flux-system
spec:
  interval: 4h
  url: https://zilliztech.github.io/milvus-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus-vectordb
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=milvus}
  chart:
    spec:
      chart: milvus
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: milvus
      version: "4.1.13"
  interval: 1h
  values:
    attu:
      enabled: true
      name: attu
      image:
        pullSecrets:
        - docker-hub-regcred
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
        - attu.nke-nvd-llm-mgmt-02.cloudnative.nvdlab.net
        ingressClassName: nginx
        tls:
        - hosts:
          - attu.nke-nvd-llm-mgmt-02.cloudnative.nvdlab.net
          secretName: attu-tld-secret
    dataCoordinator:
      replicas: 2
      activeStandby:
        enabled: true
    dataNode:
      replicas: 2
    indexCoordinator:
      replicas: 2
    indexNode:
      replicas: 2
    queryCoordinator:
      replicas: 2
      activeStandby:
        enabled: true
    queryNode:
      replicas: 2
    rootCoordinator:
      replicas: 2
      activeStandby:
        enabled: true
    externalS3:
      accessKey: 7Sejs7yHqAyjcPNATS-pWVP9fHgmU7tv
      bucketName: nke-nvd-llm-mgmt-02-milvus
      enabled: true
      host: objects.gptnvd.cloudnative.nvdlab.net
      port: 443
      region: us-east-1
      rootPath: ""
      secretKey: XZJyQL3bzNTIEOYOKz2B4Py-D6BBivTU
      useSSL: true
      useVirtualHost: false


    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          monitoring: apps

    minio:
      enabled: false
