apiVersion: v1
kind: Namespace
metadata:
  name: milvus
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: milvus
  namespace: flux-system
spec:
  interval: 4h
  url: https://zilliztech.github.io/milvus-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus-vectordb
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=milvus}
  chart:
    spec:
      chart: milvus
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: milvus
      version: "4.1.13"
  interval: 1h
  postRenderers:
  - kustomize:
      patches:
      - target:
          version: v1
          kind: ConfigMap
          name: pulsar-proxy
        patch: |
          - op: replace
            path: /data/httpNumThreads
            values: "100"
  values:
    # setting as default to deal with issue around helm upgrades https://github.com/zilliztech/milvus-helm/issues/58
    pulsar:
      proxy:
        configData:
          httpNumThreads: null
