apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          monitoring: apps


