apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    toolkit.fluxcd.io/tenant: platform-team
    istio-injection: disabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 4h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=istio-system}
  chart:
    spec:
      chart: base
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: istio
      version: "4.1.9"
  interval: 1h
  values:
    profile: "minimal"
