kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:A6RGdVkkCroKnJ9/UMmF970NxWMqcNLRxi+FC/wWSuINF4xAfF7OJEbPJcszPndJAFN6bIQ=,iv:yYco8fnV5nA/OeW7+u0Zz/pcyAPR6nbc8Uq6RX03sLU=,tag:FiDvpucCyV1SfkHieITNMA==,type:str]
    github_user: ENC[AES256_GCM,data:7AbvhPI3Uu0FTOyMcPA=,iv:LbrKAfHOQK2Rn6yxJPTDqpAUOXqLYeHfXfud0OdaBLg=,tag:YhmquD6Q94gdYIwqoEAtlw==,type:str]
    github_api_token: ENC[AES256_GCM,data:CrhKR9RoYZAu3MAWbhUt7QFUwfrgmGCSy1OynjFHlXl/XEiz4sSvJw==,iv:KJSkD9ZMDgUp/6r5lSFDTvrEFbRSZajsIxmBgb6/4vI=,tag:N0aN2lhqHSjTXlldah+qaA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:hCuqSuDPAzE=,iv:3IHTVyX8I7wrCku4DTuQG4i2Wm251nVy9MwisZVZK0M=,tag:N+1hhr6on8FC+E8zZFbgDQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:GvIkytOSnaoBBhEbRW/+xUjNVxjCLPRCGVEmBZCpKOimLETB,iv:jO8VI7LTKzv2e8OJ3ckSklPrgqWWBVLQ+xkhFFe0AOI=,tag:2+wwKNhbzCHeJ6SrEZIPdA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:IA7U2uYf0+oYk0MnLOHskcVrPOnBg8E=,iv:Y3IDfnVJCrAqbV8/B0/upK8Gi8V49sNMuIAwFKgYxGc=,tag:n8qRVJFH9edl5QT+z1McOQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:k7CPOXTvJAihEvPMhts=,iv:f4ASezocygJhROdvcomhC9TTN+gWXP/VkiHRe8r1m8g=,tag:WMpr+oOk5rlxt+lNXW1BcA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:MpA+SG3sjGx2ScCjtg0WGGvvu2ozL61VymPI1qsKK1DIXA==,iv:jsNrvJFOakEVaJUQkpLOS2fNJfQx4NSKLGwtsSYscJ4=,tag:vJDrl23x7K+QBjxZJXlpag==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:PhYOMktNIzhVG+Ru73bChIfkhPWvMHmvr5eo83UtYURS7g==,iv:GYbzgmWzajeZFkqTaWDAzj0wQDmYPjiQ5kIM2w2BUWA=,tag:TvwpUlQcWJnFxdwtXzdOPg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:Ls20GUi3HRfVInAx8tA=,iv:hQ33XYX2FR0KYS3h/K7HYzw2go46eCXKvJz3Ej9JENE=,tag:WHOKzSri2v6Rng+qjoZa7w==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:qYaC6Ou2xOfafA9s9Uh+JY6jDIcj0wjjzH094Km9FdOE/kL5tss=,iv:FM73o+dVdbj/N+yjpvXfI2MB5pDtipIOyU66PUlRrIE=,tag:7F6mFrKf++FRm+27UVvmjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRzdBMXRWY0pUcW5ERCs4
            RDBVODJCQVhxYzlvVHRVYW5qaWZ2QXVNQkJFCmZOdWdCTktMazFpU2N2ems0M2cv
            V2VTdkNBOTlUQzBhOStBem9NVHN3TkEKLS0tIFQ1NWZyUGhndlRtRWlHTGt4RTZR
            SkxUUGhxdkVwalRMTWF3c1JJMGtoMHMKzHvzqDiKxwPhhoGaOdORJxDHWdHDoYwO
            yc9pDOOGGL7IU+dLTrqN+yTdsIejyIQ/cNH9Ef2KLTOg1PGH2usCsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T10:09:25Z"
    mac: ENC[AES256_GCM,data:yiRlX4ExYdQsXstR0TV2jaOyM4A89ygihyNWbtFSkhZ+WzE6JkQX3zmyu0pvhn+3ZwrIo/qQylp/i7BsVDHXuceUNg6eAm8B4vCCLdrGCOo42gRiFX6Wk6jZwGi00+yoYY3pWzRiBW2LH5O/gotMp66e4NXn7k9o18y377pG1aE=,iv:M/2RVgVG94YRz2XF7rEIjJQQWQ8nDsTqL7RoUm/84Sg=,tag:b8U+Pnni7F6yb0kjYXdRgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
