apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/cert-manager/cert-manager/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/cert-manager/kubeflow-issuer/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/istio-1-17/istio-crds/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/istio-1-17/istio-namespace/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/istio-1-17/istio-install/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/oidc-client/oidc-authservice/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/dex/overlays/istio
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/knative/knative-serving/overlays/gateways
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/knative/knative-eventing/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/istio-1-17/cluster-local-gateway/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/kubeflow-namespace/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/kubeflow-roles/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/istio-1-17/kubeflow-istio-resources/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/katib/upstream/installs/katib-with-kubeflow
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/centraldashboard/upstream/overlays/kserve
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/admission-webhook/upstream/overlays/cert-manager
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/jupyter/jupyter-web-app/upstream/overlays/istio
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/profiles/upstream/overlays/kubeflow
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pvcviewer-controller/upstream/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/volumes-web-app/upstream/overlays/istio
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/training-operator/upstream/overlays/kubeflow
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/user-namespace/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/contrib/kserve/kserve
- workarounds/contrib/kserve/models-web-app/overlays/kubeflow
- nutanix-kubeflow-kustomizations/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
- nutanix-kubeflow-kustomizations/apps/pipeline/upstream/env/ntnx
sortOptions:
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration
  order: legacy
