version: '3'

#vars:
#  K8S_CLUSTER_NAME: '{{.K8S_CLUSTER_NAME}}'

dotenv: ['configs/_common/.env', '.local/{{.K8S_CLUSTER_NAME}}/.config.env']

includes:
  helpers: ./.taskfiles/helpers.yaml
  init: ./.taskfiles/init.yaml
  bootstrap: ./.taskfiles/bootstrap.yaml
  kubectl: ./.taskfiles/kubectl.yaml
  nke: ./.taskfiles/nke.yaml
  flux: ./.taskfiles/flux.yaml
  tofu: ./.taskfiles/tofu.yaml
  sops: ./.taskfiles/sops.yaml
  test: ./test
  workstation: ./.taskfiles/workstation.yaml
  ts: ./.taskfiles/troubleshoot.yaml

tasks:

  default:
    silent: true
    cmds:
    - task --summary bootstrap:silent
    - task -l

  test:
    cmds:
    - 'echo $K8S_CLUSTER_NAME'
    - 'echo {{.K8S_CLUSTER_NAME}}'
    - echo "$BOOTSTRAP_PRISM_CENTRAL_PASSWORD"
    - echo "$BOOTSTRAP_prism_central_password"
    - echo "{{.PRISM_CENTRAL_PASS}}"
    - echo "$PRISM_CENTRAL_PASS"
    requires:
      vars: [K8S_CLUSTER_NAME]
