apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      className: "nginx"
      pathtype: ImplementationSpecific
      hosts:
      - host: elastic.${wildcard_ingress_subdomain}
        paths:
        - path: /
      tls:
      - secretName: elastic-wildcard-tls
        hosts:
        - elastic.${wildcard_ingress_subdomain}
