apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
      #storageClassName: nutanix-volume
