apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 4h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=elasticsearch}
  chart:
    spec:
      chart: elasticsearch
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "19.13.10"
  interval: 1h
  values:
    data:
      persistence:
        size: 5Gi
    master:
      persistence:
        size: 5Gi
