apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
patchesStrategicMerge:
- patches/remove-pdb.yaml
resources:
- cluster-local-gateway.yaml
- gateway-authorizationpolicy.yaml
- gateway.yaml
