kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "nai-llm-prod-wkl"
  environment: "prod"
  cluster_profile: "llm-workload"
  kube_vip_ipam_range: "10.38.16.76-10.38.16.77"
  kube_vip_nginx_ingress_ipam: "10.38.16.74/32"
  kube_vip_istio_system_ipam: "10.38.16.75/32"
  wildcard_ingress_subdomain: "nai-llm-prod-wkl.ncnlabs.ninja"
  milvus_objects_bucket_name: "milvus"
  documents_objects_bucket_name: "documents01"
  objects_host: "10.38.16.14"
  objects_port: "80"
  objects_region: "us-east-1"
  objects_use_ssl: "false"
  gpu_cuda_toolkit_version: "v1.14.3-centos7"
  gpu_time_slicing_replica_count: "2"
  aws_route53_dns_zone: "ncnlabs.ninja"
  aws_route53_region: "us-east-2"
