kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:uI8tQJe6FK7P/YNOkxR/qeEGv1SpjgxcFllz6fFaWzBPfoZesb5vK4NTipMo/X2xEduNlkmahwCl,iv:C+A6XUiWjDmpu1rwQJ1Dv2biFT03VoGzNqx8fvK2bjQ=,tag:H+1HoUpEXpbnA2jy7ELDdw==,type:str]
    github_user: ENC[AES256_GCM,data:XvEf6eFyl8P8X1PW89U=,iv:FMmXCJ/q1DBE5aAmsEvZ5PXbKadcq1MJ02dy4bE1xMk=,tag:sjEAeCy+rcf+UnKlyIoJKQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:1O7OS2dA6rbmHxwhlSV1Xuie9URx18pof2siGr/mqgWkvypynEdfTQ==,iv:ziTCwXa8ZvVRbTQyAL/iOJDIrzU2znwiVXA/4n2WP+c=,tag:w5q2Ry2XXGzoHITLMwg5yw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:uYcws/kFKED+xoyP,iv:UIs/3LE4ZJ2NiDgR71vDlglLIvHfpHD6KAMAnc3wrNM=,tag:4ySRr6yPWb6m4mNnswfnKQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:pW9552aNWi+SJo3zXyYw,iv:Qh6Lc5KKjgWmv/wetPc5B408lryVQa1PjFIVzf7Gzks=,tag:HdwUvjwiViapMRjtuS/IyA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:t07RKcG5OyiWGr7FUhUZnfYivUDyRswEeAkapvdBUN6KJesArA==,iv:VVqnHrXGFK65olOukNoBxWw3ehd39cZzv9YKsUwGROI=,tag:GStCtXQL2Ffr4r2NORgGOg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:PiJBp/Y=,iv:H+ZPJO1u6Fvm/ocyjAD0AAvjMSWHgFmjn4lDxTEv0Sg=,tag:BGTjIrnieB4ySJAzH6hoMw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:7ZISEy/s9dlayO0=,iv:Fj9IeGGtCfQPitCIlEn+A2RvO3Kb5qwdHl1QZtV88iU=,tag:m15XVRdJSxm4jDlzZLMOJA==,type:str]
    objects_host: ENC[AES256_GCM,data:XlhBReLDLnpmXtiiYxfu1v/i+6XYLogJWilC0wACpFLuamue6thqHfP6,iv:Kv/lhCWp8GZb2uB1YEuUu7uhISNdW/SnFzRBejsafug=,tag:A+hiAOOC538FkXRvVaW3Xw==,type:str]
    objects_port: ENC[AES256_GCM,data:cDE=,iv:i56FekCqDzF6wgLfDPVxWg4xZZpLC0bVeK3ohN+j1xI=,tag:AzXFaCL0QAuGsYMogbGyqg==,type:str]
    objects_region: ENC[AES256_GCM,data:rPxHv6ResnjG,iv:LuvwcZ42OHgUAn2laduodPpHYUCQKCVR6OMpB8uERvU=,tag:gTKrk7kNbVszcYqYHODZEA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:i32ORac=,iv:pL0HJ+7v8WQucjVJQxJUDg+d3fNEc1PZk7OzsUy7esw=,tag:ZarTFqPdJZoClqSQmzo8lg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:+0BHN2beaoF9VrlGheiNSJuMxcI94DffU1uZZYOzIe0=,iv:5Fn7048gqxSGxmbFzUaTiJVKpmWS5n9yMe8M9GVweB0=,tag:9+vE9G88NYrFWjIrakNSPA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:xEhxqXo5saZqu9LXTiGzF55lcb3kCizkai/gr1zTZHE=,iv:MWDIofwoAQ5PzYwQ/eynuj84Zt6auTAprbQ24pY7atw=,tag:a2tK21i6CcvtTe9p92cE3A==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:T/0LMB7LOnxFyxOjK+UeJ0QCmLG3qpQ=,iv:n+Dq3nxqL1u/FXrLmG6Ds0rNQNOeFUh/suwuYkcnNeU=,tag:TZ+V5AGjlKSfuwdaVMObgw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:zJbRqxSns0yUUbjveP4=,iv:I7NrOdUtBI3dwK6B2+m7xHDqOiUGBqVXGoS5j7w9XdA=,tag:CfukoVQkimnh+8p57rxuVQ==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:bnv+rbqDfPSMWyrprV6BFoco1wfBuC+2IN6gT80KUBuO5uxt2LrjMaggz36/o+jBDR4Q5H4ISJQ=,iv:XO9puElESlCB/lAuSqjZq1r1QGA57my3FJp1De067F4=,tag:vAmvVwx6bZllKkJSbXb0WA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:SwkTYRwVNVCTnpgysOiSwiQTF0wGSVewPk5U6Q7eJ2cZIMyxrPgjZemnll9DpjlvKFvSZKyu8LXT,iv:0Az9NlFeTPmpph+RVw5hK4zoIukRlzS8gcJPk9Z0lho=,tag:DF40nLBUSPYKUHqNqkhg8w==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:rgM486toB9GzWe/qp3U=,iv:6guZaEPaYzBUXV9lSsS9MBGYlMTEhjlr1Ri1yY6g7Xk=,tag:ZawC+0qG47Yc8J/0WnbyqA==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:BuDssmyktPCkmVy03LjBtTzrBQObqcAYLSkBPs67NJF69whFwRsRjGhUWJM81evXCkHzer1NLvjVEcP9,iv:h9aV7ZWNRzoJjPtL7L1BLALpe2xXwJC+GdR9OzIV+Fw=,tag:oekb817lOxR6mnRaOo4lTA==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:oGnTyLntKn7jisN+X4eoSkrYKP8m0Z+QLA==,iv:P2mDSqn87bmPXYn1Q3TN8KEsG+kSQ9gb/U1O0DKrDYA=,tag:MsQ66ii8+NLYyAt3oAR8yA==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:DOc5MHhGIkq+fLbb+IGZBAbwjvUDJw==,iv:Fr078Q4cglqKfneIAa/nDOtdslNItRUH4u0hdjYJm60=,tag:zYJOgK5iJRfeTT+wbW4idg==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:cpJOM8qzuuFb,iv:NrCjP7ZAOpMTTrihNKAyt0FTcduR9LQ3KSgsYCkAoF8=,tag:rJDtV+vtrTc9aPvmvAn9lw==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:aziaudTtaEr1PdbWpVD7eFWwKzmx,iv:jBXMn+aW8yH8cvkPYko6JmtyQ/tnMSGfSGNGfKEW+eg=,tag:SU6oFDpA91eKkMPyrKp0Bw==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:um0OH1e9bwF2zAA3DgaXPDMT13E=,iv:5sQQoacDxBK3Oe+sGkIx/QEs75o8jwRGYkosYHFGs0g=,tag:XmNdrZ6uuRI60sPAxT3sbA==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:3C+OX8Omq4umreVVxETcDIaWcpe+rZnTgMW2In5sMD3BSf25M9NafA==,iv:GGM995VQXty4CLubELnF4wq1gdZt5rk4yYVzswjaAow=,tag:pViOgOtQ07Hoydt6JD55IQ==,type:str]
    nfs_export: ENC[AES256_GCM,data:/JmVp6MGJ+PFjER9z6JWcQ==,iv:08qfIDgg/zBoKgCAkHfK9BQToP40voaRpgqqg4wy3ZY=,tag:BEzchF3iQvF4/IUT2sGmUg==,type:str]
    nfs_server: ENC[AES256_GCM,data:Z5oaD9Vi1CMLo07wtFb6YxFWkIzkZp1g+CoqerLN8MaOYqF90hk5Xw==,iv:UT/eg+f5jnMgXtjJySIZrQv0Zf4MDocGRkvZcPXEp60=,tag:prf/lDVKFHExxuY581KTwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd2RmdU5jSTlySlU0cDJO
            TTIwc2lhRFZsZEtrQkV3RENwdlVNS0ZUL2w4CmZPTFVHMmgrUFBKNHVFa2Rlazhq
            d00zNkdRcHZyMWRYa1ZRRnBVRUpyRU0KLS0tIFoxaThPQ3QvNzN4ZEJ3bTJMTFE0
            cTYxTVhNSFh0ZGI0ZHhjUlhZRjZmMVkKoim3SF8VEu2AYY+5avGmR+UFVJ9l2EXF
            oE7QRSPUED9TnraNc6FmRki/Oe1xZX3+TbuTix2Tb5NJz9qMYMXKBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-24T17:14:49Z"
    mac: ENC[AES256_GCM,data:J1UAL+k8zhiszu3YKoG9OL6CeDRijnbx34USqVlMv5PmMfFQ78WBgbHiDzbxaAwwDu4tEYvK48IpsEwpcoUastT25MjZxu8fW/yynXPUvUJiPJl3xBnrnSMOpfr6C20NUDIjJwa3pvgw5TxU8uYCFgGgllVTef7ydZYWashXZ1A=,iv:MbXi2RmHK7/+Exq1H8o2t15vU+pkpzHpLtrz+PQpjYw=,tag:3mELlr4c8/eWFL7gQ1DN8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
