kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:Vg+F+QCzXeQffx7gnjYXvqnsny9Z1cs2P4DgyX7OpIfZWGad7Zo1ug3hkWHlggm7NXf7TsfVUPeF,iv:eTKxOVaMPTbzOwk/IaQJklqkg3p9S/2v1Af95/xw9Tg=,tag:6m1WdrcWRZhggSi8c+gqjA==,type:str]
    github_user: ENC[AES256_GCM,data:everXba4sEvL1iJ561Q=,iv:HYP22N8xK7qavLUe6ZW8bDDSLSC2afVJ0mFgtDOFjxE=,tag:PKWZpK9hXvGf6jCZQmcuVg==,type:str]
    github_api_token: ENC[AES256_GCM,data:SPucfsYp6o3Ap2EbCXRCa7MKGtE1sCXVTGCw4yo21PQkWiUM5h47TA==,iv:6uL50ZsgnKjJtFBTOqYaJnAlH3S+jx9Z1eXL6jfEIu0=,tag:rQ1uKV6jA7vMYe8k56eyMw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:Gx4I1lBtupcEOZzB,iv:38kZgmIopfVAtMfzBN9wfUZF1QdYeIVYFrtG+iuuu40=,tag:t9rsczGUQ7ZDwvlfkfJepA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:z3/m+pi0c39qtJvk2rgT,iv:XyIEJUUpD3wiR2al0KNIbPhquS1C00rWmD6zUyDF5Q8=,tag:GdGqlnkWAVTJ8huyIToopw==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:hJB/i5iI5GJlnXk4pEIFgdCln/1lpGNtxn7C3dyC2R1srl0yqQ==,iv:ewOirPz9dfaHeoZru+ZRXJBAeWLoK5dcplvVaW9pB90=,tag:EZkcHi9sOwhGVUz02gpHTw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:VmiR/OU=,iv:kjMNOZINTsFxrK4h3n9iJLP3y9xGjQx6u001xRkk/54=,tag:FLq8sVFGfV4cAG8cusAQnQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:zKtOJ+phEh3OMhc=,iv:n+j8B+oVX1gbRK26AcY0htpkXIxfy+85SY2JJi64gZk=,tag:pFzp0taUI+D35wbndummhg==,type:str]
    objects_host: ENC[AES256_GCM,data:TOXNzCiWevJJFjzzhz9ComZwrnorza3G3kEXfcFNe940vQNvfzbIb6DC,iv:wGDGC6/76yaJg1DunZOCZjT3e2PNfqySO42arKdw2/c=,tag:E+i9Vuzb9dGghHPqbdhN8w==,type:str]
    objects_port: ENC[AES256_GCM,data:koU=,iv:bzsIUWdlWzDsMA28av+b5OcrHVIcblPWyYAHG83pma4=,tag:Uw8zR2oUSAx9aPjex4RWEA==,type:str]
    objects_region: ENC[AES256_GCM,data:CUtR7bNcdyhv,iv:/qI0wpIJBizZRXJzY4Az/o+bKi43XdlwktvYD3Faank=,tag:Q8jqOdoL6n0f3+3aFQL32Q==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:XVJD1qs=,iv:dvyIPpG0vCS/+uDzdirV/4ywraVV/NCKPHRBSvl7jls=,tag:AkiiQu0enOnsBpJwxoHj1g==,type:str]
    objects_access_key: ENC[AES256_GCM,data:44nO7lZcRBAKk+UAP0oC/mReKlPDtDGI7pAN6exDPME=,iv:Rn7wks23rOQ9JIWti86KEsazjL+IyjAU9OsVC1RKrEQ=,tag:nIUBcDETpQxPuPA89lijUw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:y6KJ/LHG3mlgiRnORgM4ORyUkeG8TDCUlQbPSfFgWC8=,iv:6M/QVdmgrzYJ2X0LJjCb3sw9ZaVuw1nK0kROZ7Scq6w=,tag:g5XNFCPlXggUJmHteThvtg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:Qr2eaDJQ0AAEerYclFHHWAuxAk1XxLA=,iv:SEyx6Qi6FvzltuyZr3Zv/+3KyK+2Tb7sLpJ753iWSVk=,tag:AyOq1EfMPmsm0EAZRKjGvg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:QvmDgIcLiNdGof5qdw4=,iv:R1dXPDYCGRMoI9ya5J5321lHPHAnD5RSkIMLSfOnCCE=,tag:yUDTQ5SHcIvOLiyXwbd5Wg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:Mta14H0dwnrao2jeHJNZMXuF3haBUQJOx3YTc/Kk1cMSlA9gNou0tqMy7H4qDxHj1o7Rh30jow4=,iv:+QL2T+ukpEeGprFcraTLVBSZ98ZCQydx8iW95kVBpV0=,tag:UBmsVg/gXoLA11InHJ3LWw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:byL1gcHeADTRRHmgw99U3KwSTE3Xn8Zd9niOl2inzbApbb8xN2XgxyUOyvU6UpF72WDmPkT+yNHN,iv:zb5UQ1P524G6M3zZEGfQy9KRY861dDTZI9BEZZ7paK4=,tag:AHB2Ng/LBBQFuVqHSiHwew==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:SHgWkg4U5TtNfpNh5Eo=,iv:M9TWHmyAaxsXHyKvmNow9L6vtoa+K4LhMHSOI34szaY=,tag:jO0kwoCcwHVCthRyfcMOTg==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:JRb+howPnaMgaJQML+JTTUJUIj6kWn2dsVxmR9sIqg6J+Iun4AIUWj2YtirgljA05qgg14AvgLgci0ic,iv:F009ndrDxoMQHOAmxOYfR/7TjKio18APSBztWWmU4yw=,tag:PXdaLnG5+ogvHAqGkBY5pw==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:0YkM1I3DXtsFH7QtOKwPuiNDGPofmp2T7A==,iv:IfsrDODOHYOqT9Qq4M8vY7CWaJXkr2UQJb7UEIcy6fU=,tag:+l9lq3FNDSkLFq+6KkBrsg==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:Ublv88MWnUAX/QAvJ9lTmbQtuZC3Cg==,iv:CpuOr23RImgeepjPAIWozDijnTtj4pPZpornip4QRyQ=,tag:sDPnP7axBIpc4dFeWbcR4Q==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:uMcE1Z4R8SA5,iv:m4M3s3+O8Hf5x9Dr7LcTBYKEPdnC/HBPkIdQYajgWM8=,tag:iNdK73HIruaCUQjIq1B+eQ==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:Ujrkn3QVgagrt9BDUTBTva7ZWDt/,iv:dow4MlHjMQX9KrF6cwc3WSYXZQlXqCigFImVK7gM7vw=,tag:qqPbLZB5YEHWTcAGy+RZSA==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:JRI+x5Ku8r5eHX3WAWysll8AsTI=,iv:Raecu1pkaugIMrY0sPS3p2FDlYeWhknQGF1D0LTyAjs=,tag:lCFI2id4JfiEfJto3GedRw==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:3OjBdnPPzbrseCDcWKHtVyCH/qkZcqPSl1q/BR8TnxTs/5fC6BtOlA==,iv:qLH9NZuqIN2qZ3egOSDIgeJeyFqyO0V7cI1FOOSd5HM=,tag:Ig3J8eAez6p7EyHg9fvBIA==,type:str]
    nfs_export: ENC[AES256_GCM,data:p1fwd6B90aZ1/J2cl4267A==,iv:Lad/zNHsVmYt5Wq9EwLhBIC6ZH9P99MOKPD+CsiITDU=,tag:1/8odbOe9eWr0mXkSXrxrg==,type:str]
    nfs_server: ENC[AES256_GCM,data:avw4k+Qdi9ZDclIpZ3fk3Ys065bodsBxXequw0M4mYzxHYFnZgXlNg==,iv:NeAH7XoVoqtWMMIrTa/XmEjGVMHAS+5gIwj1DgIlC80=,tag:p+L/VCp9asxBlTN16t4ZHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108nszhc9q6ezmj8ultjnq59k4df2t0vrjek3eyaqufwc74a9aeeqwh3l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWTdOMnJLWjg0ZjNtNnVi
            bjZ2TU1nRHh1dVo0Q1Nrc0NlVjY0bEFSL0VzClV1SGR1VUJnQzdBU2ZRN0VUWHVm
            cTdtVkovaU9CY0ZGTU9oMmkwV2QvTVEKLS0tIFNJc3JyZmJ4bHk1ZE5hSFRURlBL
            ZWQ1OU53TGFrWmZsZHFaSzlrY0I4NzgKaxKlMTG6VyTl5N0bRgkXDC09HgAD50hs
            o8F+1R8xjbBKsWTuC/UbjHfcLrwE4283N3R4U2a8tcaMJTR4gWtqwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T02:25:27Z"
    mac: ENC[AES256_GCM,data:Zn4PkWgZBGbmov3S5Y9Q37utafKI7mTLNRM4dwadGUfrN2LCEBDhEOrcAcogOA8LYOQFNA9PZIWe/OwvECYtSglTzoIEma7zcBsed5INlAkJvCtCzv8AFvhbWpGyoeu48lY7Gyfj8k6BEJGjPC2kN97eMD9ZvIRpXrcUmzbKtqk=,iv:lQfDYhzyte7aoP6E83nNVSxH9z5NyiIMpH0gpwY4ya4=,tag:y6l40qb6pGLTbdv95lexXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
