kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:calHvDusS2ISnaslcmYhbjE7qwF9qTzWseODxKt7NWzQow4XNLLKN0imH7ms957BOG4Y85Ln3zQ1,iv:P44Jy+Lis1X7/zZ0x6f3EVft1RxjApqgjG8vXqN1EbM=,tag:MLFIW3DOLaxVU35GcGOEhg==,type:str]
    github_user: ENC[AES256_GCM,data:dnXq9uTh39cZhhfO3eM=,iv:EXOXknGMCnTaOq4B9TwHk/6LDzHvwan+/7hQnH/uyzQ=,tag:0/tcJCeRqO8GAbJXf9E3pg==,type:str]
    github_api_token: ENC[AES256_GCM,data:rdn8fA+l3gylb1TCY2Qf7v2XOHuJP1w06xaw0plFeUk+NC2zZJNwJQ==,iv:ozxAJUq63nv3b1gUid8x/xU1qBmasFbCK5mcNA1kxv8=,tag:RAFZH5vEPlBZkkK3zdykWQ==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:a0fIsOyEGQSy62+o,iv:WZ2eo7Dji1dB9+jH8j8W3TJy+WUL/9lmwU3ei7ozabE=,tag:SXR9Id76hNqf45uaCYC9YA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:I4aJIyJ+EGG42AOw/X5e,iv:6N0gYOfFGup/sOI9gkNbRDiDa1M/9ugkC1h3hZID3b0=,tag:OZkZoY9xaJpNxro+AVHsYA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:fphpJWG9fprBpRRphk+wlmhavXT/edmLsgpLv03IXW5kB3ZOoQ==,iv:3IpS5JbaNqQwI3AioTQPWpPcY1zkone6rgU2eyKkH4I=,tag:bJ9ZiMSQZ21VomQ+5XR55w==,type:str]
    prism_central_user: ENC[AES256_GCM,data:jDkHMp4=,iv:v3gFDaD3prKM10JkyG8y0qQhiQ3hbQ1ihIqa3mHWVv4=,tag:HHb5d68chk39YH9zPE5aAA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:SfacKUm8ksR6OuQ=,iv:h7H52+P+xw4YP4+2eXP29jDFqQS5u1uqemNq5eBAOEA=,tag:CxfAPee/90xiGNQu5F3Kyg==,type:str]
    objects_host: ENC[AES256_GCM,data:jk0u0XCasRJfQE6R03bMChzv7A0Wi3Zm2No44Un64m63S3j6rA==,iv:mkJOkO5kqTs2ux6cag0RrYZE3CI/8xp3tyoPvif/bE8=,tag:FW16CRZMEWsoA7EeQxYezg==,type:str]
    objects_port: ENC[AES256_GCM,data:OnU=,iv:ksPM2iwHtczl2ZktgVp9750m2Ck67OJLxbTil/2yzP8=,tag:nBWbnYjLe5I0MErBAfjsRA==,type:str]
    objects_region: ENC[AES256_GCM,data:LI7h4In/XjeX,iv:fIlc7uGtPy7aTIq7j4KxYgg9kr0zvz+0YNNgkPuBSFo=,tag:g9vgaUGR6R7wA/ParVYURw==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:cVAL1w==,iv:ZMPIjtJ47jASi55ijkyy5aCzKoa0pVEn6+JG71NweGw=,tag:oqXZInlr4Mfg9CQ93nMiiw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:NEFHdnCKJe/FgvdylnKv28evU7x97FNTAEn9wHSBgiM=,iv:BAbkIAaAfrqy2CFEw6Dl6SjAB2HQTOzsSHz7wdehUXM=,tag:kuxMMjQecgFMu849A8opSQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:Hn0Qhf2haLEAy4CWjfsSKTN0DzYza5QhYK7/JV5MTIc=,iv:+cC2B9Goup8+sVB5gGPvDor4hLWPR9RiIVxOpJjtdAU=,tag:lSZREyrPFjPvnWdh+lRjxA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:+2IhVitjy20OGM+inHDaFcLemiGJNHo=,iv:iOhD7GogxWQBdPpspB7i+Ib+TdrBSqqaaeusgIgA2cQ=,tag:RoiY9ywa2xiFdBKiPSuWfg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:gbu9/wQKhsyQOyU5v7Q=,iv:epD/MijdVtKkghz6kcJ6/HKVC1Mq37V3rrqiUlSFTTo=,tag:9DDQ2SWRXGs0q++pV86BrA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:c6p005e5+p0S2dCM1gnNTP1e8WBrToBHeftXqzXAV4DSZWZAugXmJWDQkbBgINZM2QxOU5Y4ZvE=,iv:4L8HL+jd4YEzSlFIQHpe6kZhbV8DdwhMCI2n4ctuFAk=,tag:9nU7uQilXOj1LVcpbHbsUg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:HZcgvEo0t0MIDP/B57sh2Ic27OhlS/o5cxt1W7/wjibJA5yiF6u38t2VMDXJNXml8qlyTdrOcTKU,iv:Fz9pCE+50FXMX6xbl/jaN+p8jH1p6GrzPrS+Xu11F1c=,tag:Cu9+cCas3WQ086/32eSJXw==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:QbU/6TUT1zx4/bR1swU=,iv:kKNUlbK5rkWBezL0pBCdEdoU8Oi85in/rgyhjol4mMY=,tag:7f9cSojDY/5gKH2tujqEcg==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:poQVZCZSfL8+rMWuVTJWEYAplzgOlw/CfCfoBAtauzsETJGFelxQUexfqsfjqI1nPtqdY2BQ8OFcnsPQ,iv:42HeqfnYjR49cmjaEEB/rLUq/Hmups7Lz30pmd5thgQ=,tag:Z2dELSFA7lCH8DopHHSOzA==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:Xxw6Qusk3AmbWRSLnCztHis859suu26QKA==,iv:5SDui94Lrym4m1xTgxhzo8bmDPlkGHWNvWMnZkPX8Hk=,tag:+xvfrwlfImg0bRLsTo9msw==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:eWYCSTHHrTTelPKBxGJ78+esOsrM5g==,iv:uec7rJCxXE1tu6gfoqKm5mEnkGcFjfyrF/eIF/5x4Bg=,tag:+5ylPXt8Wue76NnUQGn4Sw==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:YnYG9cHOXxl8,iv:czn4hXeJJOpyS6YAZB9qBkR+GFdP5oIUKiYTM4Jh4c8=,tag:sR3n3j2rcPj9/l/5VoW1mQ==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:nFYJW7BM7odEYJnFPZF4GudhtQd4,iv:cyg4isBuHCc6w5HoDTkwXOC86f0l41CcybizdpqRd/w=,tag:PVz6n5LySXEcm22lKbzX1A==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:jVmUxScbYUzursXx0O3UpF4WvCY=,iv:bVAzf8P6YDP1hjc85WRYrGJjwRppA4Mn1spIRP6w7cI=,tag:pBYz0shkN4e8PXZZkS9LMg==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:a4ryz4r1HBDGh9A30mpjLPjaN1e4tsUFGXd3IQDCu/F+GlRWJUt4fw==,iv:NFTvzTeG6YMlgF81AM+ZPiXkvZ+A+BnbN8oMx0fkh50=,tag:QLh/CBkdhC1IGnf9vq/Ruw==,type:str]
    nfs_export: ENC[AES256_GCM,data:dZk8WgsCKuf/4CoFS5IgUA==,iv:FkTe9+NfPlPBeeaIL5gw8UcnP2ROwhz6E1vRgJqRPDo=,tag:fs8QzRUJnN0HuA9Dl07t+Q==,type:str]
    nfs_server: ENC[AES256_GCM,data:XzsOPG6yB0NXZ195iJO2j29UV7NlW29mipDZ+Fhsklga8amDUdsAwQ==,iv:GsUTJ4iJJe9/HT92pSJBChE7bfBi7Sk3A0XZcDDmc6I=,tag:Zbxq3+HPwaoTFaS18Kyivg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbXhLU1hTWmExVXpLSTR1
            cDZNT0E2NlZENUhiOUVsNlBpWTdXNlhudEVFCld5VmQ2NHpqdmNGZ2p2OGNCY0Jz
            eUtZZVJIZ0NGeUFoc2g5TEp4VkFCeG8KLS0tIHp1UGxCeEVabzNSOFlwb3VvbERJ
            bXBzNHFhcUJ0VlhoUW50VEVvSHVOSVkKL+t2PnXsw8kUuCba/wbb8xqdmw1mzIaJ
            hAtWMrskK8380uQ2bDqbiJDXZCPv154KJiAYfrTSKOSj0uv0ruJNmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-24T16:42:42Z"
    mac: ENC[AES256_GCM,data:LfkCXs1D3snkEtV0ZCMnEM37ggNHUiLRG1Y7krIGyLTjQ99+GSEP9tJQnC2xO4YXEEnttZhL1L9ud/eSZm5Xz6Dmqu3PlMPfcqvwUq7fmcBilVe7iOdyUCiy/s8p1x2IrHXoD2K16qIrgggfJEff46jAH7A81zo7Jav5ktmPT+E=,iv:Iqsgm4AYUgZ1AiYxikBi6wfiEQyclnLZRDlqiD1R21A=,tag:hvKGZca6Th7tpk4I6ElDYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
