kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:2llVeDw1eExELsXUqrehSq0YZyq1YN2tm5dn92Ed9icgv8aOaLQnQ6EX/KTs1/p70DBv9MR/dLzB,iv:Q0AgV6ilKlZnvMCF1iczOh/TV5vboXn8O5o4VZpsNHU=,tag:t2QE4nYUpjCrBCxav8VrPQ==,type:str]
    github_user: ENC[AES256_GCM,data:quJ9PMPxwi2IFBRxcag=,iv:lshOCQkSgAXCQihI8hAAdQzf2Uvh1AmMcMk+MIknsuA=,tag:x3eoaLLO6f31jwbB4e+jrg==,type:str]
    github_api_token: ENC[AES256_GCM,data:J0NqjPI/ybxoYN82DbrbsgtmHoZo/BRNb9T0+tckCmhi3dKT/13pcg==,iv:AOTU7p+Jg+jxv0QoR0fU8nkgMaPo+awOUKvPAQoS83Q=,tag:99qPUuFPiJHNuRLdldE1MA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:6gCs86wy3/n9RNNm,iv:4sgBGlFu8xWenr33tpJYIYRM/f4LxNSiNUYWiaZVeJE=,tag:BTCtibBkhscWXaCg9k9Dxw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:JFQ7EdvWVnSSSpd+Sbcs,iv:rsoQUINYickfBVCajoauU0rNes8JtlSMHI8kHdGo8tE=,tag:c5B/EBS+HLdH2DBvulaIJg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:ztUkjxZfn1p5Nbi2RkvaYQQL29DqlWdtPRbquJKj8BRSGAURuA==,iv:nuKrB0V8SROuobR3Oe+Z2U3gXXO4CKU8zP5i8WV91TQ=,tag:opWROL4lvhcyR4YjSSI8Gg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:4KClIfE=,iv:8Xx4bjQQgQwqBwe5FNhXqw2y8+zh/5EDPHhhmBaJn60=,tag:EpUE2RoZ/9CiIcdH5Gz6Qw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:b2h0DYDuALYwZ1M=,iv:dvdzAgTEsVryXH0nnOYiOjvR6ssZENu6xDGNNtYmnHE=,tag:4N0BeoC6UsPDd6JfotmSfQ==,type:str]
    objects_host: ENC[AES256_GCM,data:WUX9o+xusIWS22nfFeczQEAmt8ZVhx3WEDnctQdt/uo+TU03kCtXWVwD,iv:oznMVDAhgy+R4spGhMHxDB20sn4daRScoD0101LkHQ0=,tag:JWYV9d/eYB5ctkTNbYeoSQ==,type:str]
    objects_port: ENC[AES256_GCM,data:QIc=,iv:ypUHIOtlEmiQxPwhx9coaYIFk564vltCJYD1oVow2G8=,tag:WWguSM+OjgC1ZQjQd+i0PA==,type:str]
    objects_region: ENC[AES256_GCM,data:SwP4Qwa3MWQn,iv:ciXd/gY1pxVMGtEIc0U2IrmV6Grb7EPxuXIqi5Ibwbs=,tag:iUUSJR5vFeiu+vRk4ergrg==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:vgAFjq8=,iv:evfQROwUKitrBsYA5kU7lA0yJ64bLD54d4u+hw1O2Cg=,tag:cPVW1UU4BxitddnHJKGIJA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:YVoXTlJEQS9mRYfofANOlFb/w7Vq7KE44dxNjs8syco=,iv:37mD4uyvPc8xbncNgOOBOZ+g9GUlxenJfh5Wbn8wVJc=,tag:hRppkXcN63PNskjmiTacjw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:PebS2UVRd1Qz2J/7smizQRM6QqQxsmP6hWWGlIm8YnI=,iv:wZI/qgR9wcx85GC3b4sxE0U/R6symj2cWjiT68Iyrgc=,tag:Yx7/lTxnxeMxta1Aerld7A==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:zBcWay0mEodENWHqHVVeGaH3ijnxqKA=,iv:PqdW7zLT50iR2/YQl78XxjmtCGVkNSC4hVVR5kE2RIM=,tag:tmO3iZoMBrF7+GCkI+y0sQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:QyMDjaQsjGfHAQn5adQ=,iv:0J9ybTE8AcGJlco3EO9UouVezCTjA2DBjlcNY4iQQUY=,tag:wCKMcuuMK0DTUCdH7jdy+A==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:FT2Exu/cZlnQEw2+bb4lAY9gSS6uwm3GL/DTI6pRC7uSaJat6TIMS3U59sNFrH/m8NdcbEe+rcs=,iv:t2e+LktT+x29Vsm9Z3VlYCnKSLNkrImmBMln08UhB1c=,tag:5Rve+NbxEa2UzCgyiGuNlw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:EAz3KOx4KkWDfkAfEQ5XMdKG9EHxNxrnUGxtsImVuE1BYaG38jJospqnzkT/U2rfCHrYpy3QsHpA,iv:X4QYIxO1nbwzDCV6xnf1zOrqhiqKN/hcSm1us6Btwps=,tag:UzkI2LeP84oZyUH4S0O9lg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:Vid/DnLdHUwqtU9hubQ=,iv:xUW8cEsMSRmDf/yUfOZoQnNpYuf5oLbxsBfbEplRZJI=,tag:xZ6gNm6bGh0LxrQuXMR0nw==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:bZlD46LeTc5Bqjamr+0ZjDQ5QONZ6IEbaiJp8YJV+9nhoQLzmroEWLH3d60/tx4aoyA11SKWZCOoh4E5,iv:EdGMnd0Kod8yymM0iCBfYN58J1MnogQgwhtwaegRxRQ=,tag:+ET0Fe9VbfxpMDYcC5kITQ==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:0xyeR20c7HP8ZyFWPl2/h1cLLv0XGiYx/Q==,iv:ZJlOjjpxYY4mxvuPZqATpPbSTcWXQYVeNlYTLXUXUiE=,tag:EuttKQ0Yyztgp64VP3JsPg==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:LbOUKxIUaeRmliHxo7UrP7k1XjtV6Q==,iv:GZ5EIO4We5+dztu/Dq1JJlDPKIGZArxQos5qCsIVTTs=,tag:Q0oNQ6DPWQ63M9PztFFrFA==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:ccUt75Ae4wig,iv:9jVF0O4bO1a2JteG6T1ek0P9iLVX7U/i8hheD2JpDu4=,tag:Xv6b8OhLcBT+f1T55swQJg==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:fONxH3SHFPlssrSs7uKaUleVijiK,iv:C2CldgWevQg3xYysVBCNAjztWlZmFVYOkk9c5LbsBdg=,tag:dbByUR5AISn0X7WKFXuRrw==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:owzYMhNIa/6T5gyTBILX8jSDUM8=,iv:fa0r/v1ryz+3ARpE5v1cdYf5RJT3ldf4hCIJQIzYVBo=,tag:iM4Jw3J5YdTXP3COo4I4SQ==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:ABdR3ZPODpakDagbFAGiq69GAN+D6ACmtdPuQoxAZC1uh/DTSX6w7g==,iv:/1Et3xBL9FbRDnD3dHIRMhTSfP5HRwDi1GOGLxH5AOg=,tag:UN7rFSoy7kN7WEk9n7whHg==,type:str]
    nfs_export: ENC[AES256_GCM,data:ZdehfAH+ohKKeouafoIX6w==,iv:fb3bBHcEZD8jnW278RF+K3PKflMocRkQ/tmqzTHgEj0=,tag:0addp+jUPs8L0cBP9pNSvQ==,type:str]
    nfs_server: ENC[AES256_GCM,data:WSkNSMpVGr5S+Jpv5fb4L6WLEDgHj6AIYOg33jQ8h8k2KlyhKz1T8A==,iv:TIRJMFPVeHN+qjnQ7LodECQzEJlDd2dJUw6aOSz+m3s=,tag:jVsRlhNRIZwTXdRZW0K4ZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108nszhc9q6ezmj8ultjnq59k4df2t0vrjek3eyaqufwc74a9aeeqwh3l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVjV1WXdQdnVCWGxJQkcw
            MitGWEY2c1FwK01YSlRYRVhKKzdDYUR4NWdZCnFiK2o1V3BZNWJNQmNVaVhLeFVD
            ZkZqOVRqRVg4amlqQXIxT3lNNWVQR1UKLS0tIFNtQ092a2FHZEt1Ujg3V0gyNEsz
            QzVuSUpZdFU3MktnUFo2elZEeFprM0EKu9YVI5Qwf4QCQ5Namx+632C8hgsWg+vC
            VpsF9te23jaa5cPVbm2fWA/wLwMaPyl/bnHTQHFf1s1lXTeCpkqr6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T02:16:52Z"
    mac: ENC[AES256_GCM,data:BhKbO0m8gFPDcFe+RCvUJ5mbtmD6vouFFex4j5KqwgkHRdGaMhKfXCnD4dygKHZkpCkUwD6eqCy/A4TjHjupBsu+7aHCtaThTm3/1nSHpvvqmX2JbN9FG4IcVR1cOSz+03GEAfqOWqj5PkjWv8gTWe8vySEBaVAWG8fKZN5dLN8=,iv:73tNigkTuq5INQ4Ffcv8ZpQXv8CZ2wq+O69w3T5jazo=,tag:HqBT05Wp1+UAaHdunrlZIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
