kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:USlNID5RsfdIzyxLZw2QzwuSGm7bSOahcUvEH813mOCvi4fFMx0nCtnS7OOqB2tNBVklNMPV0YZR,iv:NVFobfzZx9IuRE2jvTxBPzionBOyWOY8/VxQLVQupYw=,tag:GIQZ6hn1mE5dMcnf9i9roQ==,type:str]
    github_user: ENC[AES256_GCM,data:oI5ZBMzjBBEjsOyZ0yY=,iv:iAVTXvJV2C0fyBzVLCiPKVIAhilQSNxsT0CvhgMRfTE=,tag:mTMMxcV+U6vCgBNsWldsyA==,type:str]
    github_api_token: ENC[AES256_GCM,data:CkzewKggNIsxyAv5ZntW+LWGzLukqJa2iQ4iF8Jb2di+A/3aoynlSw==,iv:+bRbs369TZA6V8+YjRnKQOa/D+VEqX4/XWRsl9I57lA=,tag:evyb3ogULvjGU5d/RlIEng==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:L13xBfkDpwaa/to8,iv:KIqKtUNV9pREfzUV6Ze9nx2lNJEbv9gEokdsTC+ygU8=,tag:K8hYrvWtjcnKAx/EH0srQg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:nlignMEd8V3t7BwmLlXZ,iv:R3PqnJGa6DtMA9fqXdO0MqzSktHdJbUatY6Kokac19E=,tag:bKcrYc/aj/wwtBn6aewQTA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:KL/8m4Bei66AP5E5G2FRBrF+ChR06cjRhVlFz3oPO72/6C8/5A==,iv:N5Zd1U1kyvYshPBLrI2ilSi9s4BcwKjSuBSsvH3tA9A=,tag:pCz1/9rKULkFykI+ztp/Aw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:5XH2Nw8=,iv:ouAdOpnJrddhyq/AaUXc9Fva4huURqwQV7ubkxfvWcc=,tag:0zD9pfdcTqNVwTOXt1M7Zg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:6izGsXcikAqZeQE=,iv:9os8PBH650rlOXSOMH20epuweYIs5k0iytd156gl7YM=,tag:RbS1q8BF7WdF0C9cEKBAaQ==,type:str]
    objects_host: ENC[AES256_GCM,data:JonB9GfF68ON9NeSvZ4VbZ5WcVkKwHg7d2HWojmCtLVDeosMCGfvrQd3,iv:gNtk/KQE9k/DhokITx2TmVznowDH6jIUCJprf6rJHM8=,tag:0tSJNtz0i+ZlJsm72Tk1PA==,type:str]
    objects_port: ENC[AES256_GCM,data:E+M=,iv:jVUnoiMDK+xSntpA3vR398cApMqxedtijo3wV1PhRhg=,tag:90ykyTRiQXL5HBj8L42vJQ==,type:str]
    objects_region: ENC[AES256_GCM,data:YbfKzTwK3eB7,iv:C38anLcitkeZJAJGg+NOVSikXgSes/HnRBzbsw1E1kI=,tag:Fax01HDYhQUk1VU05qmZRQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:ucqKRC4=,iv:3859yKCMk86fGj2/mBc6YOqwj0jK8LG3nnmkgZNlOOg=,tag:mIwV0KmGsvhn4wdaiNddFg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:y2p1rz8hGgP5vDRq6QMQJtAPokim1UgMheV3h9FcRuM=,iv:V/g0IpHhxfH6pUARiG3RRG94DHpDdDJFADNb+7MLoos=,tag:iH8G+xDYuZnh/6vBuqxa6g==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:NFjVY8sJ0gFTDBMVamz9wMPXhKIDR0mhBuEZCzxpApw=,iv:QZxfsBpmfgEpa1GKi1zPi4ZybAk6aTixBHQH3ltp9LA=,tag:8kiKs1U+jfHM44kAxrXrVg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:dk18gH6J+NzTrhsFFgBYiWjYX6PwYf8=,iv:AEv7KbIcy5aiWSxry3xV3knoDDtE3KoxMoOY4/cFOnQ=,tag:zgGzbZKpFln7P+x412YGYA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:xEDAwzCThb//bTg4oYs=,iv:nogicUEI/rnVjN1DUVoI5IeUTyJjIlZZ3Gn1BWzN7Zo=,tag:DWiqh04gcxTmQOeA4e6W2A==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:K+plshDTI4981vtCSqEcSQZVBw2oVc6xsvRVc+NI0gV1Bp2m9BsbcZLrQEIDNrXh2S1/SqNuTsA=,iv:GIf4oKL6jhXVvY5NltQdHheS1Nlfxes3GerEvWJ6dQw=,tag:yiiOTlaacUCCkdv4Ez7yBg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:VSbipPI298fHyg4E8gziwweGYr253ZBigLBk0yMgYdWuAwjsFV2gr5Z1CG5zXRQYaBM2SyYZ+itu,iv:abP07J9UkXaPUutg5HY2lDiPU1ctLPIW1XNV2c2lWO0=,tag:GJn3aRIqo7ak4dyuf4BHuA==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:g0t30FKpPYhPyom6vlM=,iv:VX2Iv18hhmteZT7sDJj+jLvYsw0VuvEZcwSlEquQBkQ=,tag:cYybScpXzm1CbGAWEEj82A==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:wMhlRZ1f002bxby9Avv9zXKD++Qxy+oqZAYB0sFyrDyVPoOmFhK2qp6rCv54OPBEbMJIxgKnYYEovJjd,iv:+Mx7k4V/y7PuTCiY5aOHgstJiyDvJyiIkWWgRjBLjVA=,tag:+tf8rV0mEVfO55DfMbSyFw==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:F82X0aeP1e9xqbTm9P2hWNPZZFoUmtbPSw==,iv:JxrIafPUf+Nfewa+37S2ibXZWdZVdI6WermGVtDFL0Q=,tag:XTPYjOd5M3y6obRvCyWsDw==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:lAyrDLTD8XdEGKaa83RUov/x2rI08g==,iv:y4VVqpf97M/FA42AiLslfFpkl+2uzx8a6D0OR1b0kz0=,tag:1ZgCY6gnrBrAAGYwSAALJw==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:F8w1duw6XDh/,iv:B1dSTfs7/NIJgF/e0VnMwi81uHh1Q+ialcT4oZSpOTE=,tag:DCySAx0BGLmdl9ULWqExQw==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:M00mFlBGIrpqAHbJRKVNxGKNpgsa,iv:uvTQ1rNUBUnX8pqVJwq4B305C9qayOXxUcmewq28EeA=,tag:s8PWlGisKBkB9VNJDIi+Ig==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:7lbvmnOInK1WbmOPzNoi2JgOswQ=,iv:5NEzdviIXDts5CXwtImwS1iY59ftSfgWxnuvHqde+5U=,tag:Vu7VmmoKPpIu7sWyDLOcdg==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:gAQTAOXaRS7y1kM9ZTTFsDgZvgpTXrwyDpFbwvcfXXj+Q4VQGcThFQ==,iv:/m+0AVWT1jlosfy82eldS2EhDnxXgyazKPa2N8hmkhU=,tag:v755Ug5w71X1yhydwl+kpA==,type:str]
    nfs_export: ENC[AES256_GCM,data:a7Hixd3PFVjWkD+bAPjgmA==,iv:L+mMtAXqIPvJ3xUeVXZzRrz+XQZKI/Lm02ngzLZ5Suw=,tag:/DQB6XFiL659Fr9tcUOHOA==,type:str]
    nfs_server: ENC[AES256_GCM,data:VU5UcnPwjiOs8vLuSoSL3qD5/TWXAmTziV5oEj3hjLKTl1AKLKrirg==,iv:blZYoaNF3vHF6w3jbuh2J7yvTYzR1771UXuBoSRHqlk=,tag:HZwb1RAY00Zfhl7qXXYrQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdFdwSHkrRmd1T0hXdG9G
            aTNhYkhaaEdoU0wyUUxaK3d5TWdGZ2xmZERBClZjOUEyT3RqUzBxSVorS0RjbU5x
            Nmtvd3hyTG5vSktydkZlOG9vMTFZdHMKLS0tIEZMV3o5N2ZFUTN3OGgrVjl5dGVZ
            YXBKemZkcHZpUnV6TzF0eGdvWFRjVncKEtZMDhbdm9NJ1ErtUZ53zJiXnGTWFa8l
            W0lEH8fqftxHbtpC34537zZevdEXtw8dL8XjAEcn4Ohl/lAfLmCcnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-13T14:25:02Z"
    mac: ENC[AES256_GCM,data:emUD+IOTWFQn103bXHmWL7DH/Dcel8GKeeyUJVN+dwo67mtqJXshDIZU6UPzy9cHRxYFBeu6JVDSmOP1Q1L8B8mjXDXz+PLG2FA+PTg5ydzXorns2HyYLZ/Nhc7M5K1t41qhYk3mg5jMeTl2aHMj3YLHcBrrjr6zb8dY71cYydM=,iv:LyzDo+8YmP1wCfNfEoRqic0gGaJ3QmGiMUteIleLfiA=,tag:dN/hi2vzZTFMeHVU6Bylng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
