kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:WtdDjsNv2tETfjj1NVPTv7yl3idVjc+0Qn4s3VUjuusjHWXTiAI=,iv:ZZ4VbcusdR1FW9gZx9bLYaDvtwa4xPfC57fjVQV9CCk=,tag:Dnp+zH+ydeKfk5l/ZEf2wA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:2ERNFuY=,iv:sPQjMhuZ4/xLfqBHI389WKu4tXl9p8UwuurpeaNglUI=,tag:VWfDzbkykcxEm4gTxIkHpA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:Cr9IY0nsD5NT8Bs3z71nwN3ufHBoFD/igbU=,iv:qv1WskyWBNilmIoHqnKy/JcrVy3JaMXPY/YobKStojc=,tag:JTGLoVU9JI4Z29W3udPeDg==,type:str]
    prism_element_user: ENC[AES256_GCM,data:jT5S35M=,iv:tBDTNEqN7u0/CtzoISDjcAaV54x1FgCb8ZHvyapaoRg=,tag:ipSzMUbHosaz1K1HwqidEw==,type:str]
    prism_element_password: ENC[AES256_GCM,data:qSsTw4W6Y2pHHHkd8KVNLk/77rxZaEKHVCk=,iv:cW2z8ovzLEHnA9i+lf/cdQKKxQaMPbkHmzf1hdA4X/o=,tag:4t0SaJOXyY0+KEDOyk0cKQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:AVctE6mV6olX/Kdi6SR2Ods16N8=,iv:T53c4BAueTjjH3PqtOVxDnr5xym1Ob0Cp5/J8ie8wuU=,tag:+LW1gVj4uOI0TGBTvIk9EA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:3YVi8CL9Z4tZKKG3nFTWw751Iy0Q4GCrjViq57F8P5Z2qUIootq6ow==,iv:4238SbRPg3mQWbNDhcKWRSwrO0gu4ZaZHWW7uTmdcZM=,tag:+PbAZqF11Y69hXtLYffSdQ==,type:str]
    github_repo_url: ENC[AES256_GCM,data:Dw3W6btV2dR0uokXVEo/Vswb0Ax2x01llsA3HIaxy1o5fB6PRNtE8Pmk5R0fEoR/YSkmDPk=,iv:AS08DzXUfJI2k4LogVsIG7mqC0RW6DmnNBm6QWIVYdY=,tag:pomogAptKwrJgdpFJPgSdw==,type:str]
    github_user: ENC[AES256_GCM,data:ZBog1M2doGBs3z1ZvSE=,iv:bD86htrxJuaC5FMTBMUgltWr2YtTbU5qajBIeAZb8as=,tag:3EpVu/7L1x5qa9SmYoER2w==,type:str]
    github_api_token: ENC[AES256_GCM,data:P6BpozmLS9aJzoX5HqQYSoXlQeNbF/kNtQi/KxAAMJ23MD8WWqf1jw==,iv:NqHSfm0X8fK/iwucS+hT/nxCJfmVnBX7d6fCaryNvQA=,tag:+SfRqb/IxmBHNnGChKOWLw==,type:str]
    github_app_id: ENC[AES256_GCM,data:1roLuaTX,iv:oqoOKqrEnO0YaKrAQmM/HT8JpdTByGv5KUfiFeUfD7U=,tag:6eCy5g3w/Tl7FEs6Kr8LdQ==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:ALDj2Gzmj74=,iv:7k7hCQGYanQhwZJJglfzBHRJsXIQ5QJbXUzHQ2o9ttY=,tag:jQ86lTK9ZK6P2VYfiL7tjw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:bUoqTPAL1wU=,iv:9ZBpjaCTks3+6Zz2MMyPj9FN/kQYIHw5SqgqeOLPsiA=,tag:qDLO7PqoCw1mbKBrqR9CTw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:X5sJsjN9X07KK9j0kO5GX/DbsQtglIO7m4Bo6KFZHtJAAGvf,iv:B81gujVYsq581kD4qizPrMdv5gBlzX/SUQPcp4qHLpc=,tag:bAo8f2rb/eZwk/lnEVY5eA==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:Bjuw1yaTIr3Avvytw6g1OVqit9k=,iv:Ia9hADX7wkvsn/6Ma9/jzonLeYeO5lCZvJwbQErKedo=,tag:ug1xA+Zn01REII6BGIR2bQ==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:ddPckmky7/jm6kugmX2k5fcSoZFO8W41wOoWY0ojMNJqmONoiEbQyg==,iv:9+lRITpV/LY4HhVXVJkoflmlJqcnEg3tXE8+MrGAlaw=,tag:Qe+wH1lBPTb5rEyr4nGdCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQk85bXllTnZwNTFBZHlB
            cVZaVGx1amZJSzVTbm42WkV1Skxwcy9ZRTJNCmtjZWhZc2ZIdFphaWxnOGE5MUtm
            ZVNlejg2SHk4R3l2aDBsb2R3UDJWaW8KLS0tIG5ONTBWcGc3a0toTE9jczJsMmpY
            ZThWWWtWcGxRalNKNmswajRuNUJqY0EKXNR77MVLiDUZbNPbn/sOA+UeOCYPOCp/
            u8WnSd0o5wskiZz5WXymp526zAxq1abBbkBIkVAUyKUYMjtuvsnTAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T02:14:50Z"
    mac: ENC[AES256_GCM,data:Zz2x3u14ZJnWKg74SzVIB1A6D/KlbS/GOIE0iLWI5cr5N3L8JyIVXvvPdku/PPEjeU9+eXUoRUVOwEjBR5HaGO2x7Pk9r9C4BFKTS6vWb2mrE49oXSypRwSw5HbumKwzRQXgVlArbU6+SRksBeUvyn347v9/vIWwKw4oH5/X45s=,iv:cl6R6Nzi3JkUjIo+dt0RnjZy/npggvbM/Miy1fkJUJY=,tag:kDqQx/08gbeSSDAIehb7aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
