apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  valuesFrom:
  - kind: ConfigMap
    name: cluster-configs
    valuesKey: jupyterhub_values_override
