kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:0NIcIEfLiFCHJFshuuCrvt0BcHDMu3bjzmsMxK1M6o6EIe2ew5pIwnXG6Zeu8DYBkF1TkDw=,iv:JGKZG0TsBSYEF3aJSzcqCAqAoaV/cXtjvJX6N7moQ/U=,tag:/Kp0ZSAPI5TUwscLSe8/7w==,type:str]
    github_user: ENC[AES256_GCM,data:GKmoqkIIecV/F26MsY4=,iv:YToGqo2HGfeaEAEBJmSXnpRVsE15Nmi/lXTqrYfbT74=,tag:JNPEwLA5Rbmljb1ASxIqiA==,type:str]
    github_api_token: ENC[AES256_GCM,data:91GKGeiCk/c/Dd91ln1SMihPplGpqh99oHvMsfmEn0Pjxpq1Cmc76w==,iv:xRjrfEUMYAcmm1IYKegtj8cUnybebpw1/Y9vGoPeoq8=,tag:xuavWP71sI1zKmFkgZa+/A==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:VX1xYnR1DWs=,iv:kLHKY/Wh7QubU6hofzTQrCiu6yX+vbrZll17cckho10=,tag:E83W+pShglBUyW+p9rF/6g==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:cKEmDmODy69hBtyCpGZSOjjnwpojW5Apk3T7pKbgtpVRn+VW,iv:2IT12q0ro4IuAkTMbPOCmcAtShhNt7zrtodGwhjlwTs=,tag:jhz0JLwaNlwg5s0FUWbBgQ==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:3dWbqSm+OJdUwkJA,iv:LKAyNNUlHfoaYXanYe6JSDUCl6UALDgeRG4kMayzi+I=,tag:qJYMpDxcfZlvs2mYfZdpmQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:TrrdBGA=,iv:rm4WSh9J7wn+lYP9602zC+X0MPBhh9reHHIIjHG8g8Y=,tag:obw5FTyUrP7033eR6eg1HA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:iIl59I/7Q7PWp1M=,iv:u1AUZtdvSGvq5joWUDctXHOVbqvM1FEjnFU+n5Ft7WY=,tag:E8o+eMUQOPdsGdaBlORPlw==,type:str]
    objects_host: ENC[AES256_GCM,data:miCNCMe1WaQy2E6m,iv:ltg/vb+Th9FnAa3cih3ppGHZDAVzeIJ/CNXvutZL+5w=,tag:xrCFqhTAiTV24seZIdBybA==,type:str]
    objects_port: ENC[AES256_GCM,data:jzY=,iv:vdu0/MfEv5SuvuKNdQlSXNLn6Dr1Ab0ESQnZ9LVKgaI=,tag:FSH7H5IuK4Fkr1cQDH+T0A==,type:str]
    objects_region: ENC[AES256_GCM,data:C9JURXlfokGW,iv:dB5+mcOVT45Mk3PPy/W/ik6+at0ZLh3/hgAz1JUfJkY=,tag://IcYA1lRIexU7LQdpxAFA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:KC1tRpg=,iv:pK8B/kHBlYjVWd40YejZhRaAtlSgoR9F4TKvC5NIcXg=,tag:dnK8Dt7XwssCrqbERqY0yQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:KcupDnYEnY73AdWZasxNDuiLCUVCQC7I0ShMvwqdqDk=,iv:2wu2KoSTh90mMhL5w4U3Xv4rR6q7lNOfqY1vPzNtmcU=,tag:DYvfqlkTYl+pCDpbY0pmCg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:Rku+WO0kGuWKG/dBD7rn2QzW/0ii5XwmVZFyQGGUlZo=,iv:9YPihBUW5C6QnJzxNukkEqmwf5tazawWNL6ErU7/5gI=,tag:khBek2zXH0Xqmc3JIY+VOA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:AxVqNqQlxcljAAyS/b+AWSEOmrxpBLE=,iv:HBpXZDDGq0Qudp+PeNNduKbkG1pOmz3OW5VOowvvJeA=,tag:Q5L1l4D3RPWpXMaXMOioFg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:BH/XLLyvzOxM9I0bo1o=,iv:pz0WgE1jihnK0EgtK7dIWO+xdi4d9FgMFH9iYZ7V0Cs=,tag:UK6318RC/11xCRqCyQIAKw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:c31tjLabsAc61IPkOl2tZlTQXaj0KvAuEwiXCw/YP5ZD,iv:v3yA1iNhH0GdUoBoQ+vKj3WvOUx0luTu6xNh6Zru+7c=,tag:ijfABf3gPzKdyAZmp5pArA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:OKZ1Og9qjWNJp+TW2Bs47C32Jut6U+B9AVPIgXDdjtLG,iv:eyCBnfiJao0Y0jFnYvQ1fc2qes+4M/hNGjk79t0qAUE=,tag:U81sBDGJ5TxlPbAWPQHLyQ==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:C7JCVioAtl2/7tsJtorVHwbD,iv:oXr//u/3PDfQ6Cq8HmwZtHWuJz8sWFLER/CjomZdeOk=,tag:OLxTQJjFVwfyossOWt5IVw==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:cnLrjg4PM4d6Y2nqRA==,iv:E5dVFraGqrEoSjAbPnJsFPxCwvEdXt0HiOv452rkn7c=,tag:P07iMppTacPNX7h8EH8E8w==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:IUawuGKtzSaK,iv:8gLjs9ftFnxRMKDnF9KumCTzNdBrpHHjgaQDOomRnac=,tag:R42WzYJ4F0MR5qhFvSY4/Q==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:da1MLXG6CKBZLsYP3WtKCbO/6bU=,iv:Ps/7ni7/6b0xGlSw9S2FretGzacOEBdRa3gw2IWcKl4=,tag:09M0Qkr0AcqSUUf0UwajKA==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:enMfcpiJn2kA/bN6jp0lFtEbLw0=,iv:EH08jnZsezJGWenGklG92Jb5MTNX+G2+8Wry8k1H5os=,tag:I2xabRIX3Oe8slszYs4AkQ==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:SmK2iqLS7GtsBkauzeuvCmm2SazTRaDdvqP3SJ9DAIaQM2bMZ6m0Zw==,iv:2BccP/+rAkKIFmdmO4H2b5WGAsguH8utkORDlYIXgF0=,tag:LanuD96VWcNFM2N89mgt4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1NNY2xOaXRLS3FTNXZL
            RUE5WlYvTmg5dUZqWHI1WXl4c1NqemQyUW1JCkNmTk1ZM0lPUUYrRHF4eFhNRm9O
            NnhLODI2SjRLUm9BemlicWFtZ3podkEKLS0tIGlQRGxBcHNJU1E5Tmtaa1JnSklR
            RmVvcTFKQzBUdWlDZkgreHRUSW5YTDQKINsZ0J5QNhzLzEkzV4HvQk8zLYQbIQiB
            xZK+nrGIvbJ1XtBRPWvl77bs9Ihi2tvhr3g7OHM6tBVIZx1W0YSJWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-29T20:19:33Z"
    mac: ENC[AES256_GCM,data:YReWFlDnvaxAjRaA3lha/G7pk3wVZtHo1qeE5PclwyIFDfzQ8M9QCiSLnfHFq/AQCxXChKz+27fyQ6Mx672Py1ODe6YSg1OOrH3Ct8cxW4/08bzqM64NBzn//dOqlD5L/o4XzENCUiVqvEd9+HNVoVOTzBwHqubqCxtCKrioT/4=,iv:VaO22fm+UKEevYA/rH/tBtBOvpgklYpIwivN0LGN6/0=,tag:CDEFtVvMBIg2f9vkR92PEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
