kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:gVsfp5yZtuZ0WEln,iv:piUtR7lMesLHDvazaEluVpPberK6i5yIrVh+ZfIat28=,tag:zNVxNxgHNVfOCS9D2erkYQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:78nnemI=,iv:ghWRaeEFNIgDseYXDTykESi2mKHnHjI11WFvcWv/PAw=,tag:sIAHgaBkGumGmVUec6/Fbw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:gNg68g3oOtufAwU=,iv:RVk6zki+xlv3BRtTTY6BvWu8Brtj2DKh+Qdly91M4vk=,tag:j1tCNypXIoSp/8hjjBbiGQ==,type:str]
    prism_element_user: ENC[AES256_GCM,data:j3miJao=,iv:EozItc5Qu+KUCsfDg7N8yWywZDQgV2mt8fb/ofepR4A=,tag:G3kE5PjwIqlaL+W9M9TFOA==,type:str]
    prism_element_password: ENC[AES256_GCM,data:rjvnJFgUe+YDmnI=,iv:lEbORMhhnIG4tFtsadAdKTeY4CeO+jWgz0chbOZSIkU=,tag:vHm3MHlaGDHMKWdJu9kEOQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:WZAV7KMbgHZ8rkQbaG+qOtK31X4G5tDGA7E5iyvIYhw=,iv:M3JpmB7FKPn4AVAnVXejXXktiqS8p3n+4qvDQqmlGPM=,tag:N0jKTArUmM8DFePIf3PAfg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:om+chPy1uRpb7P+Mwgf1GyMty9Ro6ZFX5LIMl6JPupI=,iv:zCHTSKwf0oDV1mRH7bmV8uijR7cSAf7BDmkPqJd6wL4=,tag:WUkrauBos0ld44hFENkO6g==,type:str]
    github_repo_url: ENC[AES256_GCM,data:oO9T7Ikp6N0SOv02hHQiOzakr24bXb66D5juz0Hb5wv/fcSn+Zx9mYbSG2zuKR2OLjHaxw==,iv:ccbqog5O/FsP3EsGEtxNaO+2vb6FsQDSRa8jz8OulwE=,tag:1Ztt1BtzPiuGFDHLpUnFPA==,type:str]
    github_user: ENC[AES256_GCM,data:X093A10hJ73RAIizVbY=,iv:FopoOgrEgFo3zCFV8S5IqTOBOsbePj+zrCM7mPIU5/Q=,tag:+i5KJ5AXWy7CbgvPn7mFSg==,type:str]
    github_api_token: ENC[AES256_GCM,data:GSgLFxKBVbPPny6WSb2XWneCjtyRNbflo7YQRI60qbEdnMagNWD66A==,iv:CMr6N+roxz7MxKarSEsHp0nQY7DEq8Dy5R1GAIsrpw0=,tag:6AUnP5EHrL2+8M56ZtUkXA==,type:str]
    github_app_id: ENC[AES256_GCM,data:G8TwcQXg,iv:2EERw9i6RAkN0QKjIxyCu+Sx2JOE9tW7izylqWATYSM=,tag:oY8gHJVewU/JqblKX6mWUw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:awcjs7Wn+Eg=,iv:VO5reeOsuZrFM04tL+cbc8vn+gLH+29xyLSLmhfZxwg=,tag:tpKfm7NRdVkeD5vCduYyPA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:uO1cqdERLKY=,iv:616B2/C01gIo2YPghkhF1g7jtk7HvcxfJn2uaWo8sSg=,tag:ygUt85uV+iQXhtA+S3a2Zw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:bWu/4GkCFtDlmKo+sCy+jMkaxKvWvRAs84FagmFiVDiub/dN,iv:BLmJcyuPE+taIjbis//HBccZZtPezRGmBmk4E8KPe9U=,tag:NP4Rr1sxzw2PTCGB/02LtQ==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:1Dqhfi4YeUSO4VwLvGi4743BnSE=,iv:/iWP/Wz8XhnYJe2F0zrSsIpjyAi8AxGYfgbZ3yyrmmk=,tag:HUHJ9K4xl1JvDBx+KU8AYQ==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:B6+FmoaNgkkZ4bXxUuGb+VbN2gziDNTXUpa+zHSSsQ3vaZ+YSuIsJg==,iv:ItzSdO+oUROgnK3UYngb6RS6fUs8IO0G3FUltAgPsss=,tag:5Z7K5uhGP7aNMItRXQ+oFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmODFrMTBkc3VGcXgzMnlI
            dE9nbm5ZSzI1MjI0SEx4SEdDSC90N3B4Q3hnCkJkbkdCSWpncld2MC9zMWY1bVBr
            cFJwSWhSVGRQWEwwL3VIME5MdzA5YXcKLS0tIGxrRDZSRmYvZlZMcXIzMjBnNW42
            K3kzb2NEK1V5UFVWWm4vZWlzd3I1Z3cKu3CRlOyQWVBazBv5WaQdITQQswSgS8E2
            3gMNqVnYdxvQoUjGuBEkglmd0ZmNbPveRohRpCCysrQo3JE+3NHOBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T01:01:11Z"
    mac: ENC[AES256_GCM,data:FdBEFv9I2raAHXNJgEX9n7fb9O6KyzsDF7y5yqeceigWVR3vtAzT+Ho9qSLBIARPzDyLE0yG074ybsQkOBtlmRKkFdlhvHljNUdfRPeSabRiAaf0Z6jGbeNiOhDzTSn/LEYe4F6liLSROXEOOVaLCQzgHcW8tq5oghXZjMTiw9k=,iv:s2L3P08iVMxPI69GWmNz3fYYA0mQigGImZudzh6b8NE=,tag:0BTu7yFHvQQVtLQrA1ducw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
