apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-collector-daemon
  namespace: flux-system
  annotations:
    #kustomize.toolkit.fluxcd.io/force: enabled
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./platform/opentelemetry-collector-daemon/_operators
  prune: true
  wait: true
  timeout: 15m
  postBuild:
    substitute:
      namespace_name: opentelemetry
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false

