kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:XfVsKx2/yypfNLiU8sZDYv4Ozh404F9+VGuJ0HbG4sGr0bHC1X9w8Dr3L9Lo,iv:RDZToX8/t4Xg77bShhOmJThVe6Bt31/UCgdBljjX/p4=,tag:OSXx8CqGfezFlevTNoe5yg==,type:str]
    github_user: ENC[AES256_GCM,data:X+cAFEAP,iv:doN9I2vWeo5iEw90qrP2NScc0fSsu48IqvyKei8byi8=,tag:FDbMzqsfLjkFDihT0/KB1A==,type:str]
    github_api_token: ENC[AES256_GCM,data:hWeBGEiaVR6lJRtEclUGwNFdmr+krVs8GXalh9iD6DhhiLJ2ZyoFPvVpn2JuXqJjxAprNK229T8aByLFwMBLHy8S0jycLFkHn2kyVPf1tC2OixcxLzxbm5q4hRgc,iv:PVttlSKFgg9454BwuH9qeXCLkSaM2ml1obbpczKC2G0=,tag:ApLh0ua26QrKAK9EFiml5g==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:L3s2B/I=,iv:u8ugwXeBnpcFs/ApNLd5Irv3k9EMOALXOfiTZ/WDy6c=,tag:CQ5qJgdFRR+BRjjnp8pkYA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:9M5T2Tc7JBob9Nhvh430V9yH8BYqTnlVbdFocBejKI50QBpL,iv:G2ujpR9/28SmgnEy/jMZ95EYv8tIE3lF/V9TZ0Be9cw=,tag:X/YUAfqBia9ZhOOdYUV6NA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:/9pBgIIcW1LZWPfcRA==,iv:ySlw4P2rOePZ4dXCPfeIoYPy01mhHNhdU8hIf9QzsNs=,tag:j0k0lW9v/8XikalbHF54Vw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:1s6Jwd4=,iv:iSnhzGEzO6xWeIsfXjCRcGq67w1WDwp4DYGMYa4OdZk=,tag:yc6NK+RZ5gn6TdxyTDF9IQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:4hvTiYUYYXIo8Q==,iv:TWryFuqieTnieCJITvwZqICyj7hvC5SgB7NPUw6heAc=,tag:EFV7MM2ZxH9cU6Y586rsGQ==,type:str]
    objects_host: ENC[AES256_GCM,data:4RUil3wn/8qYO0zG9Q==,iv:FHMAW0/Do6lpd9smhiqmqtWEo1XdirfYc5uEvfTMb4o=,tag:nAn4UIImMwgvpdHq02D/xA==,type:str]
    objects_port: ENC[AES256_GCM,data:rdA=,iv:1zVyn6Hyesil/qsb8DqtDbfoPYDcG+QbXhs7QCMpHKI=,tag:wuNVQqR8Cp4D3yFgNPImCw==,type:str]
    objects_region: ENC[AES256_GCM,data:H3s/TFHiH6tz,iv:E5gNDIbSBylF8w8hzGv2MjRQyQCmrSpby4ZFn+0TfgI=,tag:KdGmMy2hnLfBL++PXmCPCA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:jBD8ces=,iv:od+KdAoODCWCHU4OCTtoFxohAkC7Tdh8MFa0aTJ2fdg=,tag:OXLCuwG/V2NzHqIzuI31+w==,type:str]
    objects_access_key: ENC[AES256_GCM,data:GXpnA9Uu6u91e8U1QKa9MtiWZaQLg2w0cgP/U0roUTs=,iv:RRAfaAbEapmK69NErAE3FPnDID/a9PTKCCVcC9sQdls=,tag:5QSuZVIVkOuj1NVUJHV5tQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:M8zN7cUYbzJyOI7IZZ6jAsb6ZnSFJtvf59rjtwfN4Fo=,iv:jLmUT89xP5x752J5n1u4ogUCm0ONVcJoI+CmCu4xezw=,tag:U7g+u3R4zJIKy4yRQ+AICQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:RHjOvBwHbzKES7ooOqavIQVCJcSLK9mO7VsjkUw=,iv:K1mhS/ds/FrUUJLDaa6vO17ZM7Vg67QLCBBhpPufs/k=,tag:5/kC/f6kaeAD3babGI+ETw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:7dXYnw1WCXGBQXIgOytXQV0=,iv:10+H1qr/guJfmHx3vMVhDVIw7xty6NVv9jnjQ6BNt0U=,tag:v8v9qWbVB9dzvyZki2T0iQ==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:Xi9IPaZ6rZQqv7YFXk+1rpn7I2w7KtNHix7lC3JrYixo3B65dvs=,iv:uInfmTLCtMyPzUnnGdplwLSq4p927QYqUDsU7I6RE9o=,tag:w4BBl7+EDxTMTfassP9Ong==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:UKlZRMDBMSljN0D07IusbQg5s50ECTfdOWA+FDzhOjvwYg==,iv:Q9xINTVZxVSwrEeZwNpmaL91px4es7UuHsxt9ihIKck=,tag:5/ZTjCphpzErenVV29a0bQ==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:aSrvaVYGKRe/sFI8RQukbBc=,iv:TwfOgQ4oCiYDMjsH8AAWyjL8AMy+yMcDZaja8zJOXnA=,tag:/r4M/htwm6K9LRbPPpogBg==,type:str]
    istio_vip: ENC[AES256_GCM,data:sLDFGzqMH92Lfa8bP5E=,iv:zrkZynyQywUR2FrBxUPx/LL9AoV+XQW+aFWoya9mhn8=,tag:8YlK8d2UU6xdzFny+2VHJA==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:VGtQDPb/NgLv/6tvhLHtXEg1jQ1rQHaaMTgIz/WQyeoiELm67hA=,iv:6xWLk2RGI5BwfvgedcL5vUdtr1djIGEjE4fkU9iTYnw=,tag:J3uhEnrPj2meUFnaXkSDPg==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:JjWu/hCVN9R1Qls6vzC2DbOy8Qoqu3QB4LI0/fKF6POwrnxc7i4UHRuY3m+hU6zVPmxSaeAMHJWBpaLh,iv:tOXuUgxw794xpwnQo78vDwVUSwV+p7b+lfQrR0nzFAg=,tag:dswrK5ASp/VAlJ/GTa+qWg==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:nTjyDhtt4HI+IXJjfd858nnN/jibaJEHQpVzSl6wuLjMgXa35g==,iv:/U4Fq3r3hCmD657LWSFlDkEMocq3F4jLFjmxApDi1wI=,tag:4g2ps5DmtUMtlbub3soPvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vknuej3pqzsyh73prl9vfng84wdcdrmcvsdvngt0lcx3hueu7c5qcg5pdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVW9pOXhFY3AxS2x6T3Zv
            MUdzYWRYM2kxSU1td1VjaXJERzJJdFhmbDNrCjdCMTZ6OUlVZHFabWJ2RERLTDVX
            TERpNXdtUmVWU0VWR0RxM3NZUHc2TkEKLS0tIEdlSy9haVI5aHZUNWpCTUV1UFNr
            YVFreHlab1FVU1ZDcmlVMXBLYzIrYkkKjFANxvGvP0PCS9UI5sRQClK7nVx8e2YI
            nXXiIm0L0LGJMcAiFDGsUUqvIwG/n9ZX5T0J6b9qYl4K5QMWJJSLQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-16T22:11:20Z"
    mac: ENC[AES256_GCM,data:Ixh8N2K7Saspuj3K/LlaPusdIcVCbkRANdJzOgRjK15+DLfFsQ532L8rKhgWdOZh4oLHKbwhF8AYw/3vR7q0z3FqegUo2hgE1ROYP3cL0X14CejGP73xvv/IpY+1G59qtggrgPnAeA9W/jMxJpnPboG7NsQau+pLC5pyYROohmE=,iv:oWih3pZOiVxnVDau43Fgut2bQT0iu1hpVNQtGoz37Yg=,tag:ZLIhWWdVn9PnmIm89Gj16w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
