kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:5us8KqdM50/WpUMrZrhfFbKNj/2gJM/lzuts7E07/6LBNr6k0CWT5uw+g63q,iv:XekHcwpKbJt4pARv5MrP4CTyhJVpP3HYuh7rb1PnGkY=,tag:/twHvIkHPh2BeI4ctP3zXA==,type:str]
    github_user: ENC[AES256_GCM,data:xUTtehcD,iv:7+5IG6erQDcDJOlrbSHfSfQ6gpTvK5VfGeT1vjrguMo=,tag:pHA6ZIDF2u9N0qG2mfvBOw==,type:str]
    github_api_token: ENC[AES256_GCM,data:UE86HlJhOlZu5wrskOZa5jH+TUY5PLsfysUyyOyA5qkOr7CcU7GPETE0od4Z21rR0sfYsPR6aMheT1QNlOf+wV26TiNx3b8FPjfXwBfcnRT/CfqC3q0U+UKsSMm5,iv:FwQWm3CBRGMn8T6rRoyOkwMbt4lBy2HjoCkf1NhFrIg=,tag:9NfU4NVOzRnSxvyRtaNkrw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:05VvS18=,iv:buap69uEjTsf4qBiP2SYFmVtd0mSCHuKfsXLaHUrLIA=,tag:77Cn/aCKLwzwT3sk1CEhsw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:pl0Ge4Rr3hOxMGyxzjwVm85x7vaALJXQmjiB7wtEgTunNMwK,iv:BA41Cz4m/JJ6IG0BaLN7CbvJZb5pwVpKuH9szDBIj7w=,tag:O3PY0B2f7Bsbn9Qch4cYMA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:xqUhmTvMlayvXDF//g==,iv:CqySLtNFJ3R3fYIZHTB+mhhn/p+IZbCw6V2JdhiUn5Y=,tag:tyqy2HvhjwYbfoPb7T5SYg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:5XWqWn8=,iv:/zLcDWJwMXAd8oU0IHYIzUIaNfmhu6nsw97JJopqB1U=,tag:S7NotdaB0naXrUzTHU59FQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:FVJI7f6TvzAhEg==,iv:jwBaon09KNZeRnTavCAemCl0T9mTB2SWKrTgvgtX9mY=,tag:Gh/WyMg0zFEY/cpETR+XUw==,type:str]
    objects_host: ENC[AES256_GCM,data:oxxVB7Rz8TQQtNtPig==,iv:KbqeDIqTO69XRlGot8qVlt1aVco52eCRemHOAwiaVXo=,tag:5JfpumC7o/4knsQY6/HLjw==,type:str]
    objects_port: ENC[AES256_GCM,data:OCI=,iv:NxN7l0DvJSsdpow/qicOjJeZdA14ktBbkdXnNFkiDjM=,tag:rEKg8WtHCP6QWYkFBnoMlA==,type:str]
    objects_region: ENC[AES256_GCM,data:6oPf8a3H+Jvz,iv:nWuMxWgRm4Vaub2G2LfCaUV7ZT+J24/4wK0aDXu4SW8=,tag:Z6YfdHXKzRRBJ9HTg6TZLA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:PBnVmwU=,iv:Ff4ZoUiEv2+Ig8VxTbD8xgikL7YJvwJLhZlqtc6Fs64=,tag:NZ5jSsXS5eaTg6jlNEZhDA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:HAaKLuwydK/CPwp+GYPYeD4CqKK2DBXnA5268587Ad0=,iv:KYucgHzcYgbbNdwTV5XyLH9t6kZ3EsYz3dQA4uQNVXY=,tag:3mg4LfGNRR6/guImTKJ+vQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:WD0L4CGIPtUUkmrhrUpZwFkzfJHZYAYNHOBaeAaLt/k=,iv:6DIXkyxF0SxXJ9WLHpGowDpj7ec5PQVAs4S1pFO3fDs=,tag:0FxeZc+69xkXiIKJ9eLTgQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:7Vmw22k0chJxBSOtdCfBCkqGTos5eBLL0qmAg+E=,iv:Zr9Bou5ZypvdI5VMBwtdAW/So3U+crZGWwnUAcqFbLQ=,tag:1c9GL3UOKyr6H4c4FSEtLg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:0BOjm1rgxya+PxmFNrt1HyM=,iv:cBxjNEuzQ+k1T4WaupTBFYTMbdGlh6fuXlAZ3rGCkmw=,tag:oZKN44PoT0Q/2DJGegGclg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:OGxKWLslcyathhkcogDy7rvMClv+CMETiv5QNl79DNgeEFhaKlo=,iv:iDqOUuPX8/W7nl3w8iWyEwB+GX07ljaBnFwOJay8MQ4=,tag:ZeIj9AWju5HRDSNeVhPlAQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:tubx4QLmzjZhgk1svDT37AbXvjd/UAdqwGuQvcIvrnrKiw==,iv:uR1SPb0/v2cSQBVli6rKtZS07/VmkdJ4hrzFF6kRytk=,tag:pfonABMjRW46a75fzYOAaA==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:yF60F6CIPThYOP4Y7hkxP9g=,iv:gEcjIQatYHN1SnYgG4k322THYW/xsqqon67j0j8pu88=,tag:XlSHxKEj/3x93uN8q/+L8w==,type:str]
    istio_vip: ENC[AES256_GCM,data:VbtRg/Sz/Bmj8Va6pI8=,iv:SDxf36wyxSstIGOgifzYV5mcM/qOi9i+5NAXrYv8kas=,tag:VKKnF+JsmxIGyqxTA5wmew==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:ItjzZ+5VImTlArbxxpFaQRX1PfFJQhy+bCCkdIR1KaQkDTrMBbw=,iv:b4Q/8k+29EJsyRAHx/rkCboLSNskncv1WaRu6BgSP54=,tag:3el6gVMm5fKPEdeuO4LBoQ==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:rW9G5G0RWpDe9rdl0KRXF92vBIjP86UzHClYAZZDdwQEL2lKlQjHh+F8oJsLEN4EaRNVYNhrUGsCEjI1,iv:RzVfh312EaFoTAej3+4iHqE1gDE7qff2Dad7RahHnQg=,tag:WtIkEW+kqW48cOo6qgx+3Q==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:5XuifyiClRhqBfe9UE+lrLr0NuMyB6y3rZqBeVaNF66qGEwrAA==,iv:G86eG+y9ZP3t5km1LcUxH1u3FswtHsi00n7Wl50Q7Is=,tag:pPoF3qZTXRIdf2ruI36cLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vknuej3pqzsyh73prl9vfng84wdcdrmcvsdvngt0lcx3hueu7c5qcg5pdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMlhrRndzOUtxTldQd2FG
            aVh6U0ZVUkYvS0M3b0d0SzhLYVFOUGMrR0VVCkE0L096WDVZMnBaSm0zdW42UkNz
            S2sreEtRVXRadzh0Z1AvRFM4N0x1U00KLS0tIHhIdC9wVThTakdpZ3lXWTNIWjJt
            TWtML3pIbnpuaVF0dE5XejAxdTZ5OUEK0O30Ths3ocbexkHxzRt+n/8LWzxnevEY
            V2vuYAGc5hz6f56ye4zJXzH/ZwFRRQK+a70rompdHSJ6JPOGFcwvRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T06:35:29Z"
    mac: ENC[AES256_GCM,data:lnm7lD81GE2JofZcSN6oRgBMhljPMMiGLjbF6JUcbiOqBj2G/U+cfZ5ju+LNDOoDtbZKaCXfc0XgH771UD/LjanMJm1j3MtSB6F7SzvoGSUmv8wnaM2Wa54RLmumCS62xUcVYLKcjLyk3ivcPvmvGyLopKPc2w7Iwf2+RQK8g0s=,iv:ZTm3c4o408IZxWzeYTIUVUE6szhgWSiDy6Ake7/IwSk=,tag:G9MgPnyXNLf+jv1UNdCMfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
