kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:ppgju3/TzZ8CIIrq/jNQPzFzqBaXDwj/i+SNXR18J/O62+27kfwtKgusC0j2,iv:q6QmDFgoF3DGzcas8wsg/qfNpkXxdG5B2IpTTsL+ihw=,tag:KWnftHPsvhZ1V2CuIRpX3A==,type:str]
    github_user: ENC[AES256_GCM,data:D/pdE2wX,iv:mXmwH7/lb5T0jtb71hkpQTto0HHl+MJgaKoOThsOy+U=,tag:o+JJucz76rNEUbFeKRhuCg==,type:str]
    github_api_token: ENC[AES256_GCM,data:20np08wI8izgyBDGUxsz4kV7hbpwOqESwvTz/ZHENEyQNLUi0gN6v/gb/MMakI+WAsxGePGReIO8gujE6QdgHLPXwJ5YYwznKbNxKd8upfmDt5BU0X7RTjw52Mrf,iv:17AKU12x+tzMzHnEDljT8uh3vACS0itZvRa5ql2SKXo=,tag:ccniOvx04azeDeyanz06hA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:94BVtQo=,iv:uWz4LBrvHeVkjx/6fkI5RqPmZbZ1KGgbfeFoj+tNxys=,tag:gS198srPIYU7n9SK78d0Kg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:wBV20iLNdcT0og1QlG1lYKa7qf0NCRzhgJ8cewYWMVs8phXV,iv:mYQzpgEjBh0AQMTsTtpjdrP8cEYxodoNS6SdvGL8byk=,tag:R5NHNol1Wm+sJ1AbUulHtw==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:vYWoFZFoqzC71IeMgg==,iv:O6AOfOkSM//oaN03J7KNhfVdzhGHboEcUWHZuIEWKVY=,tag:PfqBa+jngUyz3TggCLzT1w==,type:str]
    prism_central_user: ENC[AES256_GCM,data:quGNXb8=,iv:OpXeojiWBgHfDz3wTQNxT6dHXzoS7+z4kz/lnzdAOeE=,tag:C+ef1336nRCzOm2cbhElyQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:2a2EVXRPN8FW8Q==,iv:Ypk6U5IIKdxOr1zZIrmrkn4SY+XlvhcgxJHKuYKDBn8=,tag:BOsT47szqGZIEoSVIi04rQ==,type:str]
    objects_host: ENC[AES256_GCM,data:JJAGKWnJ062cb5/K2Q==,iv:2nYeqi6fL7AFiap4apauFV+7iDvpk5/hea3CyS2aT+4=,tag:IywevZtxSdLeGIiVwhtsnw==,type:str]
    objects_port: ENC[AES256_GCM,data:R4M=,iv:5MyouCNkE1YC9qFkRLwmymr/pIRYMlBuRCq+7SxWWCk=,tag:8bmE9Le6mn0tXtvSQITKIQ==,type:str]
    objects_region: ENC[AES256_GCM,data:j387W3ntC0mE,iv:SlBZN9Px7fbRtbpJXjQl5vqDchZCQ+aAh2mtvUY72Co=,tag:Yj0/ULzdXDaDOzWDfH2xtA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:1kpAyNQ=,iv:7KEfhf9h0cD3c+6xx3a6MQRfmslkbjgXq7+KZd/R5w4=,tag:UNhWzoCEjbpdEqz6yXCOEA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:tJzTcO6CekVQwmgWqJsenlod14G3DKEjpiacuL/vVII=,iv:dnnvYYEqsuHoas9h/pMoall4FF3PEF8pEeUIjkBt73E=,tag:cBsKaF/+cOm1ozJttxc3/g==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:yIDpAQWuc5FVbpvaq2PMGQRjLtqhmZf5lOEzbQjHxL0=,iv:GW5nUm9VdjOboc4QFLBBR5jqFp18GS5dRCaDHXtZ1vk=,tag:X1sXiszFwoNfisTtjiMKsQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:BBrLm6H5lgecY+vGL/jbegSbTNT88MbLBheTRus=,iv:R5uyLar6LxJ0clkNMHDRyMQApyrfGS/Fx/nSKO6wjJg=,tag:zlBF9KNnX2OFzcCU+DtGXw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:yqJOifunG6k+8s39FDQVsdI=,iv:czaTtLUV52vuSqkdcfw2T2AoNsTxVrWkBeAoGSkqGik=,tag:kyFG3U5493RCNGP41qJMpw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:IT4yNDdfyHht83IM2W+j+S7HkFNijQT6YTcuL5aHQAc5Jtc+94E=,iv:d7qjvjNOdSMkf0TSHcvw5/SMqtHfQsD3O0u7nJ1XvzM=,tag:J5GtAamVUFni8FvnMQyPZw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:bKbRuz8m/vPwDwFMyM0/LLt350x760MwOKvsJ1+g1iIRsg==,iv:s0v23bnfnrpIVzq2iy56bkdjDTUjXAUa7Q3Lq5VM9B0=,tag:Kzc1TRAJHRRn/mQlwR0F0g==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:G6IzSEJdDiY476Equ5uiERA=,iv:sFdPWK5iKM4gc9NVg/H/ILYnr3+/9cI+P5U663cZD9w=,tag:vs5HaT4macYawToevgpVUw==,type:str]
    istio_vip: ENC[AES256_GCM,data:YAoeriiXczGvQhFqGaY=,iv:qV4dXTk3BQk6zKB9aNkQbjEaDAUpcmk0c2Kvhoc9woI=,tag:/wCyPI7lS/LkZqpaqXFzIA==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:dKUFUY4qyMokh60hr7M4j6MPqJ39H7/g8hvcd0voz9AAyYxGs5w=,iv:SG0kEEmQAz+kGw9NG6gGJoDcQp5vejRPH58ZTWdMkFc=,tag:Fi6DU19aZjDgduv7LHCFTA==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:GB7gVyh0RmsehxiLDG6DOREKPnyQnSc2DodZ4zTQLRh1+XnVUxjwjpuoFA59g8DMhinlGuL8aJA6Dmp9,iv:M34g6iYQLcGkD6iTGs9utpCCFQQXicUGP0ygh8DZfI8=,tag:vRiR7U4SUa+BPo5xJHhUpQ==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:ZzEJqn0psFzhRn1fU8I1WGJgI95BxYXN7XyYgZ7soqaSy0mN0A==,iv:pZqCbY/DV2uqnfAwcxmLJ9rZcmEnmlWOZ8KW4xMxm3U=,tag:2lxNAT8qStWPpWRzCU7HWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vknuej3pqzsyh73prl9vfng84wdcdrmcvsdvngt0lcx3hueu7c5qcg5pdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NlFXUERuempLRkJ3YUMw
            VVh2WUdkWFFScWJPTFhqK3o2OU5YZHFiOGd3Cjg3RzRKeHVNRURsMzdFMXFRLy9L
            bGpCa1drd29obVRDR1hYdStHejk4OG8KLS0tIE9RbitNbWcxNTFDWEhBeEpHV3FV
            SGRMK3FoU2FHOEc3QnhHMVFIWVlOd00KAa6X0g5u0PhL2C5doCRXlshSWbW2YNHx
            O4t3cH5UdYOa13R16NpoxFJQ3gfZPEf8l+JMn4nMCp6WfZtaG19cqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T07:54:41Z"
    mac: ENC[AES256_GCM,data:IEQWM5btJ4LiCg4uOJK6xHOB6Yf8NmksjBT6rSTAejyEAvHxCqds+E/T4UNdq8dM5fDCHoekwFvG8af5N64lv7SJfD+Vr5MxoZ5+Y8XiLK2d/8pp1vpfF1FTeGMvLgr7EtQZ4mI7aBgp1/u/Ibt9Mj2PE3154EwL6dzVJzWToqM=,iv:kGsfmTvGTMC8OCx5jVQw7/SMBUdogQWTQdyHvYVzOzg=,tag:WWPZmRi9sKKVpXQoJKULWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
