kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "flux-kind-cicd"
  environment: "minimal"
  cluster_profile: "kind-stacks"
  cert_manager_version: "v1.13.5"
  cert_manager_issuer_name: "selfsigned-cluster-issuer"
  weave_gitops_version: "4.0.36"
