kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:tNwCQYjFKUVb8gc4,iv:Dig3ot9U/Oy2rvUHLsk8Ifv9VrNe8ILDM/80V6AlWHU=,tag:Ia9p2qr/ttsxG1A4ngxGJA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:wPAVRbQ=,iv:08buO8wNOPo/ZafwQryxF5j5Wk191+LFbMsOrHESLI0=,tag:k5uMCwRx8ellNVmnh0jLgg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:h2B3Cy/Gtqql350=,iv:jTSA0ao6GibCBeS3mGhsxvEev7pn5dCzZ/d806+/Zuw=,tag:6Ra83RoT3vLBPj3kYoOU6g==,type:str]
    prism_element_user: ENC[AES256_GCM,data:GbVXroo=,iv:Kcwir+qCAi3HHFLh3P9TTWd8KJhgg/W1Gd7+pebQaYY=,tag:oX/rXefSP/l7h/ucOPbTYQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:Yi7BEUeNRcXWgJo=,iv:kQyLq7StgNDm4p7PZH4Y+82/RqnwyD9lJUQHYssDaow=,tag:fisRQ9J+BvOR7Mywz8jmTg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:MSn63XhEkX5KP3vIIXVUOkpcpSqmJd3jBgyo8ERw7AY=,iv:8IeL6qwETVx4j10jLELeG/TJmy/vighVBdRLe5Wv5xU=,tag:levPyhQXTnYxfNKd+RQ0lQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:zCwp1SRpXS1CrAym3IiDKt9rNicIvpSNsjr9ksz6Va4=,iv:e/SnWy1DCNguzS/envru3aXTXJ3w7uaWt3Em30fx9ZA=,tag:Sc0RRwvt6OQGdOdRySq8Jw==,type:str]
    github_repo_url: ENC[AES256_GCM,data:2AqyoGQIuZZcCmWUdmEQPF9dnzd267bOg8kFIbVTCY7k12tR3QCBlT7+50+pltCAiHhHRA==,iv:jCCP+oN0TZeR48rG1UTd8OGXy7A+3VxqaHH3MOmmK7E=,tag:IIZ0sgcZAaa/5WX6CQOHlw==,type:str]
    github_user: ENC[AES256_GCM,data:hvEu7tWP6epoem1+ZYE=,iv:YCEBkeQb1rCwQ8Dfc6YwgPVFIPtdWXmUjFC8L27etO0=,tag:dCL/nc2WjSrV6agBT1OzkA==,type:str]
    github_api_token: ENC[AES256_GCM,data:CooyRF7PvgBCkqjaOZohegnuXA6ZM+TjbuTUZ8ZGg2i+0Eq9ftlThw==,iv:4kBt7S1PySS/SV8b1hnbqwp30dlCnbMh39r/XkbHs2E=,tag:SOmfi4l1S80Yf1SfCHU/zw==,type:str]
    github_app_id: ENC[AES256_GCM,data:F1naOTxR,iv:+1TC8wxTFYBCdZ0dgtItAGC/m3E9hKYllDbkn3v9les=,tag:r4YZVXi0mnomDWQZWILcFQ==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:j853AzLSurY=,iv:v8vIMn0Mzvmpp2LyuPcTJYURIVYJHVyQYOSs0AeThFQ=,tag:kKQKDukMr8LAnifqTusgpg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:6vyse6RmcJk=,iv:BbPM+orHtsx0eh85zKJxZNTBNbbTQ4SfCf79KcFPhtU=,tag:mO8Js1hqwriRKDLjTvXI1Q==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:duCRY0uBhBl2Gx/t5B0Q9REFWYRSW5RJCPg91bAMMP5DWXgY,iv:hz/L4OYCIsRW3XNlv99oFJVcVpmYyjjOsIfI6NivIXk=,tag:jeZTv4l2KPJT0xDP2C07ag==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:h2jLg4jxVUP/0slZ08bS6JmEYP4=,iv:lLt+M8UUC6eMNgL16PdZ2tQvJtEQUrlwHityyxIYHd4=,tag:tcr/zCyPRdhRKS0BPF9+/A==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:0M0fOKPCSMfltMJeMizclYPTLV1aQ4wjleNuo3u2hyJbMdmJqa9QDA==,iv:gwBCG6XpjbgkKHdGY36lhY6sKTVX8M+oDzQnRNWvnmk=,tag:KIp6OnQcWkHjqjGqMi2CUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUDlOV3EwclNmTEVaWEZP
            MG9RM0VoeVF6VjhPZWxPTWVWSG5kbjlvdGxnCjZ2bXhIRG82WGpkdlF4ODBQWjZw
            aHl3WHhYQ2luRnhoR3RqUXV6aGdQc3cKLS0tIDQ0ZUpPWG5LdXZNejVqTldvMDZo
            UXk4Z2phUXBFcnhvcnVzdGlpYVhGVUEKNO/xxOYw8vYdA9LnlboLHk2kS/ZINB0F
            bVnlwwLoiUMOPUtOABO87/h2GYzQ2M+UPYejfCoesWywwRORzfEj7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-14T13:48:14Z"
    mac: ENC[AES256_GCM,data:4ysMGgtaOTXiIcCeyxyud0J6fCUiQLzRN8JO+SitqhcqcSP3MVcnAZXauwnqUDqBFbr1ppVi0Shf8CBNu4PDuEz/Ex1x8/z1KfyYGPzvW5GZKqg9kdDyiovHU2naOWESzavdwlzCW9uhy33luUS7HGlYjGi5p9leTrrkc8mSJ8A=,iv:yPccSmLdH9YK8Q1mqXmyLWdSPesLy2Jt1x/w6CtyEKQ=,tag:v+IwmNTUY6u8tcgbUbdVmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
