apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: cluster-policy
  annotations:
    kustomize.toolkit.fluxcd.io/force: disabled
  namespace: gpu-operator
spec:
  devicePlugin:
    config:
      default: any
      name: time-slicing-config
