kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:xa285DG/gfm67twuLRCFQfa0uCuY1aa+yuTj7p7vBphlJw3xJPnzZz23RHYpDg3c/hl05hU=,iv:yY1bgRBxc8SaP6dmnXH5dlTQtQsl/sRNmbAB77hBEaY=,tag:GSGisx81LUbRLfjeYdSL0w==,type:str]
    github_user: ENC[AES256_GCM,data:HUTV6ZENYtYW/fh5/8o=,iv:ok0496vuB/bQherG10JKB5Xy6NzywNofP+KVs277soU=,tag:RrGcjRTNsF6N6Rhh/h8CGA==,type:str]
    github_api_token: ENC[AES256_GCM,data:zyFhi+UfFrM659X1qfkrjgt+lZwYKktQqbXzS0WFMDX1A8h/AwZCxA==,iv:6sWsh9ZZPP+H85YoCJ4sGnOKZpvOQWaNnGruEKGMqxA=,tag:UI91QeHauTSYxDksYr8gOg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:ShA9XIh8tKU=,iv:HpErBhsGjaJDoK3q4jDNCut6MI4Q0hrZjMfpvojHqp4=,tag:qMgI57QfxZwWkGC6+r1DjA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:dtsOEUfqDtfhAKHNYEyyoQImZZVgiyq+iNindeBcOYjGgidG,iv:jNeiTpmi2d7BVTx8yE1Oj0OaWZSN6tzhPv2qL5RtO9g=,tag:Vu9xFdB5C1o2yoWbOop5pg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:OA6ChcCq3INeDek=,iv:1Hrd90hWqVw5TnDahAqE/GK1K3KEi2Os/EQLwfnlvag=,tag:K8LjGwuMGd1GUm8/Foc13A==,type:str]
    prism_central_user: ENC[AES256_GCM,data:UJMnSmU=,iv:VivlefMhxNmoODCkCY1POsXpIv7OqH5iaSJIQT4tkBY=,tag:8fFc8Y6AXj3GJ9/0csTZdA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:MZRy2fbm1tRb7Xo=,iv:XnOk7URJpn53q0iA/eJHusDCrfkPDcaaJ1XqpfO+O1U=,tag:cWhzYq7wbsue2nUYV6Hhbw==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:TGSC30D/zGiMuL3ikSUyzBcy195jXeI=,iv:hENaC3VbuS47HLPcoPLBM33jtN1k7+YI9gUhZ2f0np4=,tag:oJg2dNBxKtQu9YwSUf8Eyw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:hRfpGAQa35dBGtanwaI=,iv:5DnWtj2wbZ9FcWJ+EQoDZzKYKhEecN1MJTYR3HE1H4M=,tag:j6Sb5jtG2itimFrQ3b4oFw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:zqAgGb5MPG7sSLWyQO2Ufl6bpNpOpr8MdmhGYZN9,iv:rpXEI2FcJQvUypvaNKGngVAoZ/iP6WC0Ycg6B5Tiy38=,tag:g2LEFXbf2z/F8uPAllENtQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:yWLlGqsHD4BeD33CgQDB1b2OKHOTL9ewE8MnStjM,iv:ug3cfkfWIwbGhs0LLPbDZiMa53USFCZOnM1ZIJU15gU=,tag:MyI2HP5tnpt9galveqWqLg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:NJoqutY8rP3A2e7iFz8=,iv:4ZV71Az0f7ih6qQcJFHu7nkUGMaDOt7tV/woLhGoVC8=,tag:lSYa2Q7Ht9/UQA3SPkebXg==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:gMvf5aUNA5JYjCqEZZEnTkaec0ouhrAZzFawyUnhcVI8mq5ylPyRgJYRoNE=,iv:LV1+gllLqr+huoqFkc+tY636Hwba0dVxXXkdFs4U/vA=,tag:7e03+YBxOkPZePMue4gtWA==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:36KdGhj9EPcaTHIxsOr1qXTvAQz2tTZ+eg==,iv:7bx9At7KKI7dBNWgyjlaLx12ipp/hJe3pBnu4nuxFiY=,tag:MLkpJ1jB9iXqMAWV/sMmww==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:DzipyHBQ3Wri6trdNQxcMhBc0RVf4A==,iv:NzhLEwe1bBYXaJovS6nesrUZbGwtaMKQZHtcB+kL5VI=,tag:gwii2uy5afG04RiuEvTAfw==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:dkAkED6JHFSC,iv:JEjho8twDyRbnUDIYU9yF9MXLIhlGFRT5H94ki5kOwc=,tag:ewAbyaassf88YF58COfnYA==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:Txa6wRT/fsuhKu4kcZqlDUbCz45I,iv:P/Nu1hvjygvdGDNGGERB38LepEbRzco6j/fISKySVrE=,tag:4mAfpO++/qsGjH8GOe3myA==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:035r8rbq+Fp4Xd2FW3VQ7V6h+R0=,iv:/xOx1zddQvR3LdP1Qx1Tir0XKnFayIgsrBA2+6PA0uU=,tag:3Ra4ODw3Hto2eKAqoZA4mw==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:mdCJmVFl5bJ2qxqb2vJiyBQs9ZbwIwU5Va2+GxIeJVvTSuaV1l5IEw==,iv:CHREF6GGgcwwcIzA85RQ4/dr1zwn7bMfUKuwd7phw8o=,tag:VxFoWJ+ztdL/qzBC1aCO2A==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:U7ycsg1Ed+Uz7tKztOhgnm7YeLqZhmTkLXUI2h+S/envgmyZHQ==,iv:syceUp7VP9iOFymMFPtis3Gh5nWR8dZD+3yrbzb8LoY=,tag:2ZzZxD6J+RyEZkfOcIFkWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1am05cFA1dHFmeVZ2azlS
            dSs1MmdObnllb1Y5SEZlaTJ2b1JsZWRQL1ZzCkZ4R0swc0JSaUt6UkdsK1l4ZXhS
            cmJnOGdjTUdVc0l6T0NBbFR4TVN0eXMKLS0tIDlQaDRHeXJKTjZ4WTJKR1pLbXE2
            VklrZ0w3M0drRU1uSENrSGhvTGZKN00Kzd8KhnS08BFf5fRO+zIyzLsKZiwXt6Y3
            3LrLTfQn2QLu9KykE3Wb29SDMUwfPt0IGkSMtnvn3/0HElmwUyiZEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-29T18:06:49Z"
    mac: ENC[AES256_GCM,data:5mQH1x9qLFaBP4cfWwhpuNgpED5C5h/P4NnOWclfkOcjB3yPxZbH84DFFeXWydwBbLma8WumlAC3lVRmz5PPORKem4q5HdY9GvVdHdQaFgHMHKY7biBqr53zTHvHl0BmG/0eIIeOAxMDcBNylJRzTsEQiOUU0xOvlct6rWgzL9k=,iv:KxpgrR/ZFBlZpj+yhq+BMQSx/mcXqP3Fww5khyPJKwU=,tag:5i5E0EgA19lmw+833MFJgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
