apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: /spec/predictor/imagePullSecrets
      value: [{ name: docker-hub-regcred }]
  target:
    kind: InferenceService
    name: llm
    namespace: llm
