kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:zjwbeEOooyJx/rQ3nVHHCGd3eLo4PsNJ/iriMYJw/oU=,iv:0liiuWpA4oy9/66gRNkjSrYIBnpAyZ3fwL7ii2Cqhuc=,tag:HYcb7D2H3F5Ha012aA5bqg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:fmpcXno=,iv:ND0sdFxtjqS45+TqVcI1YV3NR3oObTCU9LGK1aUJhqw=,tag:+jHAOwI+TCXE8+8hFA7TnQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:PZG6N2vMzLnyl/c=,iv:JM8p/ArBtCo/PHESgrKTJK7tFcXb5FnEAvKLEBZvVPY=,tag:SZr9WKsuxXcuBJO4LQqa9w==,type:str]
    prism_element_user: ENC[AES256_GCM,data:xLhLZKI=,iv:UHYwKRBGzV5W5re4XjupNwsHfcPWhanNJ0Y+hOIskV4=,tag:i4GWNUJrekXlY/6VSQjcTQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:PV7djjIBamw2/2s=,iv:Mmn7E7UVDAuMlVSECzi6VK+BpZmeXQyJgg3827sFkFo=,tag:clAoUoEAX/VOXGPksoSJyQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:31z4ORIzIhTQOnWb8ocfyaGx8h5u9Vj1CUsOJ+FmqX4=,iv:hhQ2Au9GoB4CUzkLkIHQPmFEdknNsJWDw/ZTsR4NbG8=,tag:XPXzSpqFYmgVSY8hwxIN1A==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:g5j7c4SS/Eyj2xv/ykyXKTZ7EKDfuLcJs/Pkhgm/19M=,iv:rPO2v4Pp0NOF1PdnJr/Jlb5FITI+OOcmz/FFrttVzLo=,tag:zFjiqOGcigVdfmUb8LPVZQ==,type:str]
    github_repo_url: ENC[AES256_GCM,data:Zw442Dip8Ivvi79v44tgngaaG/WPx3B4jALHwtpgyv786EpotyHAWl7SKJT09wXE9F465A==,iv:jumi+FstBz9EVokKKLNZNjmwhl8qsiV9+b1yN30SMo4=,tag:cOMTD462Pe8gY5ksGi5P4w==,type:str]
    github_user: ENC[AES256_GCM,data:EYsq5Ucud9XJE9WG3MU=,iv:TJbny2WATcE4ifJ3Xl3xRsDU+AdFiLRaqM3HmCkj5w4=,tag:tvg0Jn20xxXnQgCiSaKU2g==,type:str]
    github_api_token: ENC[AES256_GCM,data:12MQoTvHlWeOXcfXaf4rq7dikQ4hKE3hdE7p3opQEBmah0SBvgidVA==,iv:SdUbS0y1cFUdRPsjNU+zZ9INO3/v5HSyTLSpQg/F+Bc=,tag:zSudQOYPqIn2c5AWHuGriA==,type:str]
    github_app_id: ENC[AES256_GCM,data:CIQGvbLg,iv:xUMxQDsrs6IdFXP3Dl42Xu2ZU9zJ3Q+3EGH/lgQNbjM=,tag:6xmZi1143xnRRuO/Su6PgA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:gKe3qqjzFkY=,iv:DD5DEs7CyBBLppYdMRthqiPyao0E3AxAJeC6FMNUQsY=,tag:7SWWV+fjlPWiSTWBaiR3ng==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:sIRHIxq0XOQ=,iv:uJBzYjNYpx7jtuob6QuiFDm0hdnw/oT0tCS9zjLXZwU=,tag:X4uSkFb4OisFYeG2vYdfDQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:m7ERSdB8r5+XtNvPnV7smOlVXzJwPJ3yIlzsm663GK0g2BP7,iv:QsuvvKinekgbibF12iibc5EzRM8O7Jhm+57qEc+sGWI=,tag:QfyQsABhRRdNu6N3ZMXkSQ==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:hT5zfs3YAN86+MGrSGgVWk21Ls8=,iv:Qwr2B1XhAKLcltl/wvDhstl9x2vs+6dnik9c6CreVbI=,tag:bnmwB+aYgHdJhRbxWXwREw==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:MDA0B4trimOaeQtmQOaULSntMPDEZmCA7g3v4cpQ3mlHWISco2QIBQ==,iv:aKvbAvR3EvOYIm/EGDAPIaLvrAY7JxqfX1P1CRDU3jg=,tag:8zwTPSfVzC2iLvcfkrpzaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K0xBeXdFNjAzSDBSS0dl
            cWdUU3VrQjZpbEFWM2pSNGJCTURhazc0bXdnClQzU3luQmNIMWZRdGVjVkRRTWYv
            RWtqZGtDWnZCR2NHWTc2bFFxcVB4UUEKLS0tIERwdTVyT20rbWp3YmhMRWVKVkVX
            RzJuck14V1h0MXZVU0Z2OFFsZWl1QnMK890xhqgxxgSqfCmQkVOCfIOgCsghiYSh
            uCGXJLV9exR3MaMyG537RyEO5bmQpzz6QJhy3lvdu0Ir6QwFC/NJlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T22:20:47Z"
    mac: ENC[AES256_GCM,data:iMIEvdELEhPISjsGMZ9nWutUEMPfjiW2GJW8+5Vk2Ho7De7yAyEdx84lKQcRl0vkhVYr31ZUecu1UYykjrop2yyBAxxnJLSSgz0nJPwo7xFFr/IvxaXW/AwZoKA4FMNaohR/QSaO3oK85IGlbHtF0zW8sxH8F6gRop/ysHYJKTI=,iv:SqnBWnTX0AX6ycV15aIjRpAvPLvXgRCasSTQjKaCsL8=,tag:ld8bSzt89INumakFm7j+HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
