kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:DPMMJPL9Snf4g9GC3XbMGam6d2oJRE2O5JQCdVrGKEs=,iv:sTd4DJmBcoef+0E+BXWRCvT9lYRciy+muGyWTsjIG9I=,tag:CSb9vAf1wc/+DVu6af7/3g==,type:str]
    prism_central_user: ENC[AES256_GCM,data:iMKycuQ=,iv:Pmr0Ufjlvi/Px8UZGUvUQelxkh5pEAXwwGI/BcVrn6g=,tag:30GaivD8TmOnuj2TpQblyw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:o4JVlE69P2Qie3U=,iv:bq9tNqe+622Gr7lbOX7uZrk9wPn1LiRu6JYfF6Cni8c=,tag:RlkJUpJpD6HCxuTRLeVMpA==,type:str]
    prism_element_user: ENC[AES256_GCM,data:Kxjc8Ck=,iv:MwW8Et5tuBjXgxO/WXdLKRXUCXoqH+UlSHJWsOne+v8=,tag:yRLY07mQQ2PdtC9sM+CIRQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:sFfvogfLVcLbHZU=,iv:XnxWTwHObNz4tshx0KjNlRpQOsGhHvPRPuhf4R1aFto=,tag:gy2NHsXlnNuDnLADHHG6OQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:uz5UzaswNHCzJmLK0lR6oJxSWMrCqLEBrT3hnNdjT4k=,iv:p1hApYjtZkSjAOWhnrlhE2YNj+KBCTtuNK94noQqMfw=,tag:vTKXCRafUGuRpTMePwvcrA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:uWx9OViVuHBhKicQtjQVbwLZZAavmGG7bOAlYIP3eRo=,iv:EZqD/jgHsqek6Ktrn5hWGbKfRWPaKwuWWgBx0zo7NRw=,tag:RG4Quk77gnkwdu4eL9unCA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:poRwOFvwPoe+rJ1UBQMIXuWFzR21yTagvrTZcwqBMOZhtY5fJ6MOYIxw+hxHL4WYv9XYdw==,iv:sTkqmHqIWBwckwRDDq/2A/0i39fBuYfrNp6KaliSMyU=,tag:OC2uP86b80Uo45UBFKkhfw==,type:str]
    github_user: ENC[AES256_GCM,data:OZqztnq0fOO2lwwFuX8=,iv:nYzGU1h5MmYsbkUPFFk0Ymew70cOL1ihcWirzTvn9j8=,tag:woGVjssjtpsuov4GMNZZEg==,type:str]
    github_api_token: ENC[AES256_GCM,data:GpmLV8/MQpo7c9MsoVPXIFqXX/D8BB8mR2iVn2EazQusqulRtVRPog==,iv:v3p9Vcht+N3ZqsbguXzuUdeuHBpOI3Xoq8/fJDi5o/E=,tag:/s5Z7e4LBcbZB0+k04tSpA==,type:str]
    github_app_id: ENC[AES256_GCM,data:44vYLxZ5,iv:CEESGLvb4y4tRXYgmFO3qJhdPwuD5gWxB8Kpb2SdUyo=,tag:GUeyHXWWRMRjPX/AH7RISQ==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:UF+MOT1PhN4=,iv:5U/HcbxwAQdssPwqWKmZ8etSZujGJt8ty+iQg+Wr3mA=,tag:Q7aVK2B5fFe2njp2iaYmzg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:Iy2MMHMSvMU=,iv:zyRKB4nazin6DGUL0Rg3OU5q9pHVb3h3RIofYI7yTHU=,tag:X9VjjcM3u+48wTnyoOKoaQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:shKYg/Ei6YJYUXHU0J6yel/BggO7UyiXd0b41yMsgUFvmPgu,iv:tkWa0R4wMRw6D6+NyPgV4paopNfST1UNxnnfl0I7gSM=,tag:uB7GDtHJbH56C65tJOZbbQ==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:xP3OsZKMBFoN/gok2zZ3VqgFn80=,iv:Vbj8UIbsnNRSBVfE24WaDN7xK9Tb0CKvJ9PCRfgjhmY=,tag:Gu+eTILWzS4KawR48szJSw==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:2nCkl/qUp+PLM9NEXOQNtmXJlJ5jG3lp6GApAHaNHhXHKN+W1A7WuA==,iv:hBs9x5vndOnAbEQAGeTF+11EASoLcmhZg3pCAFrxx/Y=,tag:Hy/yu/I7HoKwPLMtrah5HA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMUtDeHNsQ1N5Qm84MktD
            dVBXWUR3MTQ5ZnNDN0V0cDZEajhrOHU4Q3pBCk9XTFFiQnZ0NUYyckdGRzVJK0wy
            QkwwRE5wSTFKN0ZYOU1tUCtEcVZxeXMKLS0tIGl1TEFCb2NUTHIvSi8zemczNmNv
            NmU0M0NScVIrajBtT0k5WmZveTNtWG8KnGLiKqX47OUyJDyIYh7WuSBoC0esO4+S
            2jILbkw5hkKikM3gRipDEmg/+ZAkkX8AZwRQlSnUHzVqccxIwdy+Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T16:34:42Z"
    mac: ENC[AES256_GCM,data:jh21G3K3I1TPIqlwA4SFf7bviHlmzZj1hxwsSfY+RKdd1cJZGk++/HxTCLESHZPmrwiyNNoNCnLqXrRT86u5++Olq65KFQuJraYBHqWm1RKhDcssrm0Lk4RUDnILaSanl7BOfavdgIcz71Otm4tf3+PyeE8AwMVOjnaHERtPP1w=,iv:HiRXnciYC8yUBhi+Smds0/YHYAV8yoUuSjygpUNPp8s=,tag:ZcvWCWyKkneQgn+TA5+b/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
