kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:/mfA+GTlNzBuHEPvZAVcUN6XkkToLhJE4vockvTBDQM=,iv:pVU0dpdrqpg7uuDdu8orFhty1stSDrp7Hxi1p2sf/MM=,tag:YYY+l6SyRMtnBZjo8GNkUA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:yXfW/Fg=,iv:QUS+D0P2yHGo3ViuhBxKfx1SeEJ3zPmI+/u7qSP7cCY=,tag:9vPkxmCqZaUFD3Xd/i1Nww==,type:str]
    prism_central_password: ENC[AES256_GCM,data:yyox7fK9mBbmAyc=,iv:C7xQFWSGRCd51jaEvXFDE7kNBwYCaB+4pWKsJD0LuiQ=,tag:BUJhP7nEgOb9eKnhHscA1Q==,type:str]
    prism_element_user: ENC[AES256_GCM,data:aWUuw0c=,iv:y6TQyhQHCjkKjDGSSqhiJmEA5qQiuNbbifDYVkQb3jQ=,tag:Xy9BGwZoGQTfT0PItxmqmw==,type:str]
    prism_element_password: ENC[AES256_GCM,data:g6KTrlWV5tRULG0=,iv:NoDUQ5UzrG7T1Gx+otNzR01f5QwTNtM6ma31KbW2DjE=,tag:4DksOdXM89xebZBWbv7saA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:CFUDBxD+WPNdPYTKOgJOoYuB90IWHg5ZSsFEf6C1AOE=,iv:V/+df5m+nceikELNnsjmdEEdIaaxe017dv5dgSN2OIQ=,tag:HczKxljW50BY59HG1autug==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:iYy37zesVW1Ws+Vk2NjlsalL4AoK89q1rEMV4224prA=,iv:ZGvpy2JzjDzkHT9Sifl4gVQqofSuzDqhDVCY4Fb4/JY=,tag:FzIKdMv479YNciUwVbCHaw==,type:str]
    github_repo_url: ENC[AES256_GCM,data:Sdsv+85t1GX+7gs3RP5gVvFXAJr7U09/yHVQQS0RViCqZkDrFTNHsmZY7zQ0c6AuT8oiBQ==,iv:5+UcAVvcg90qpO4OaFxQddbb7hTYKg7nK5Lm4YhYvj8=,tag:73Rs1B+FFvwzXsSIZXRQCg==,type:str]
    github_user: ENC[AES256_GCM,data:wLSS3Rgi8MgvZt3GiVA=,iv:XhiMOfSBhNZMu9jDOz8Kj5V+AH61aNAYzr4qcGrobtk=,tag:mTN4RbvGIIeRl7ejCQFDtg==,type:str]
    github_api_token: ENC[AES256_GCM,data:mJFUHNdO2LhOhpDIt4hE3PM+73bcV1RLms006bgyjLjbrOeJ8Ph54g==,iv:1VieyJwi4XezfEmmN1BfwSwxk/KQGHDGIaNTtJLofNM=,tag:W5eUbrLBks8anRx3UtL2dA==,type:str]
    github_app_id: ENC[AES256_GCM,data:UINo5fkb,iv:djGX0NAJm40HVR6QeSMvoxPJLV/NrgfzwCWA4h27ijU=,tag:YK9llVif9qTQj4xe6aMBbQ==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:MkHA9BudWjM=,iv:bLd3IyVCk5ybdjTumqElMddtn0hxnzgtf9C1prFQVXs=,tag:KQNzRs6YQm2TjRdvTg7uIg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:LAwvevSWOsM=,iv:deEznT0x7lLCQ0lQRxpzYvEcTN0lMxnYPAwVl8DHoLU=,tag:sl537D4IuXVLKgl3COhydw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:hev5dfl/Wa7VWsgYNyRH/e7rIbns0Midf46iuL0Aih4G5JWM,iv:GDSauK1cr+An+51pU9eU8wNsHrkKqT1IRqOIVliiuus=,tag:SbcJv1FcYUvABZQjhzQk5Q==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:eIJn9Icm8RQ0Hf38zga7eMM6fJY=,iv:QnOc6fPjK9ekWzyqhS5mmyvZO0kzuJrPo8Vul4mFseI=,tag:hADc0RGtb8uU/+usrC8ROQ==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:mX4YH44yesnznNZZf/5PxaZrePn9MzkAP+r7M3Z+Db4vXS9fSWpeAQ==,iv:x+78V4g7xkEiqb+u06KMATpPzx89667P1CZZWxVm+58=,tag:MdH6cY4WAGsWSZD+21lwMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTE55SEV3RzRmTyswZ1NS
            dnNMNVU5UHFJb3pIOWJKemlVaEJwaXI4L1JzClU1Uk15WWh1czd1MGtYUC9xSW93
            MzlMSkJiNzNybk44ejRSV0VQMnpCQWMKLS0tIHlhUTBLU2QvVWhIcmZJYzFqTmNn
            dDBTenFGOStCdlJWNExzak5Ia0lXdmMKYIulXurGvdBrmKNLZ8PUhXTQlpBiDvU+
            KAqn4xF+85IM/64hT5f+WCYUZeS/YvUVKpxi41+k2ZtdUyFzr2VVKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T01:20:07Z"
    mac: ENC[AES256_GCM,data:ABeSAX1OjdC8VFFVmr71IjugQzwGuQ6qovvCgsbyoqRnulN3JBFQFUzgPwDpZg85uYMBqowAJSVczNEDtTmFprOSQOq2KhH1AtGzjfOR6Pjakm4UiEbU43BoT7JLOGWhxzQ/0GkWdPHk0+TRNR5TVBvEaFUdLxfA5Xyq/2z97kI=,iv:8pZO5OEhMW0TUC8mSWhl0zHJz3iFKIoBCb6LrKh3JDE=,tag:RDulEXPML7GHO172bsqBmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
