apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  values:
    tcp:
      "9092": "kafka/kafka-kafka:9092"
      "9094": "kafka/kafka-kafka-controller-0-external:9094"
      "9095": "kafka/kafka-kafka-controller-1-external:9094"
      "9096": "kafka/kafka-kafka-controller-2-external:9094"
      "19530": "milvus/milvus-milvus-vectordb:19530"
      "14317": "uptrace/uptrace-uptrace:uptrace:14317"
