kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:TFvx+WBjA2iMA3lZX+BTZRxVVk5ktXPYeE9wgGi9LtLemStk7Vn2U/zYRDMIwhPiaf/sHmCYWkYa,iv:B9N22cspGt5XQX6EGxPPliiQFqSzHlNcYTnZsutQ1yM=,tag:JtUg2zwlJrqBcbC8FFVEUA==,type:str]
    github_user: ENC[AES256_GCM,data:L9ennbjO3iNJtELkUwY=,iv:yXMeoAjCcXQItcpgAUEr0Xix3KaW7xal9yGBL2txxrY=,tag:xQQz0FrMUpVkmABMs0w0yg==,type:str]
    github_api_token: ENC[AES256_GCM,data:f7zVzPibUNrfHCCQiwwxD5PNKlDVuMHKXBq4IapzfP4kWBF4OmWkRA==,iv:YGlQHHcQ+Gi6SMODmRiZlluNdCzUaqtWyORqxPb15aw=,tag:q7vOCc+DmJKVqS3cp03rXA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:OMvKZHwr0oIPoZ3S,iv:wfxYYUmPYtqIlxAlYYX2/tQzhlAQ9d61i9mbQaD4m00=,tag:wYqYfUi59FSHk0WEbIUPag==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:K1VYFNXz3e7K2sJSgYd0,iv:Fn+3O1tWwjtECprBVgh3KaGW6Mx9e4B6iSVDLg6aYH0=,tag:foovqgBfGYzeKFwSRomoIA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:o4qA2K6KEcJOnEy7peiYq9q3zEt5ohM+xA0M1PiD40rnajUNaw==,iv:MBxVf0cYJQzD6ZqACm4LwOP4181ymUR6Yv8HVJ35mMQ=,tag:GF7YHHphuRojiaijumVJTw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:bOWKhW0=,iv:3gCyhtDlYk4hpHzY1PmeGqONlXeu4smSZIWxDEJsJCc=,tag:LWE3NYfeYY8YnSbte/YC9Q==,type:str]
    prism_central_password: ENC[AES256_GCM,data:aXFJ7alXtKmzxa8=,iv:QeftEg8YewpChQtRXGdlTUb2aeay13BfHyxOI00B50Q=,tag:TckN1PbEPFG7MZUmuYkQAw==,type:str]
    objects_host: ENC[AES256_GCM,data:LNZwgnR1HJkuByAqgzIK6fGwv4jnsceO3xUzXBF2RVfSAx3qDA==,iv:0aVWxbiEQX1Uochb1NSqYQSTfDVLqxCJFtVPF3y5Um4=,tag:VnFLit1Lh3e8bWf+TBH7dg==,type:str]
    objects_port: ENC[AES256_GCM,data:M5U=,iv:hggwvZj6KZTZ3kjU8nl510Ys827QjnC9gvcICr3O+e0=,tag:0Npu2LKHlGjQmwFfY9MY4A==,type:str]
    objects_region: ENC[AES256_GCM,data:bFceIJrC4vkK,iv:xQhDRzsKmcWDkZgjk0snMBD+yV/wLuEZW+OGycr2nNs=,tag:Qsy2Sup1gk4sxS5OMmbxew==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:gS026Q==,iv:X8m87RmacLRCM7u6LA432ffCBiLfaUltP2hvnKZgrLc=,tag:13sc2J89Q5Dkyg69OFbYDQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:5J4kCmmJOR1LVoVTEbd/Sy4kajIG+S0FDMc0tkuu6DQ=,iv:ViPaVSinP/Evbi2iG25xaJe9sfedxNgbNGoB3Fi59I8=,tag:ly5Uzu1i1hLyxJ3dxf7r/A==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:InCuV7MF2IzkA7ZdqjFZXjF2cfs6fteflKSuyirB7qg=,iv:wlgUVGNHdn6qS/risbuchGpsc8DFNdvJMGv8yzaDhXg=,tag:5pxpDoraB2FLK5IWZzUrTA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:eHTK7z5ZGqGwNWnJ8XMwad7zB3X9LZs=,iv:TkbEkfiF5fnZpGw05WRNn7/RpbXcWcW0r91h5lV4XSg=,tag:iomEVTVE1aD84kUYT9E9Ow==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:3f2kNzOvRHftSyYBBXw=,iv:HsXQXbJHLuM/cfpgCAAKtS5D2OPVgsaZNtJkAhoJk8U=,tag:ECi5b4gnAU9W5RFX6xQBcg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:vC+bZLKFcedBZtrJc2P5GGzTGLdc7e8JHfU2hnlivZyWiEmN+7E9Q9woyPB5Ui6CWyRkzaPGJuAL,iv:WNSxXEiXQl4aqOxDU9P+wz6Q6Wj75EtHCydzJeyxPJ0=,tag:9IZm1WxRjs7pUL450NERgg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:c9yHAqPc/RXU6EutDBSqO4toZC8S+D9iy4ErysrWmN559hJyX19PF3P5T4/ezEupkHztixTZH6Tc,iv:TII93S7KZmyct8tG4OIfASnfssQbi3VO+UJYbpII1uQ=,tag:cGWVEtoJETmYqUZLC5ANJQ==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:1idkL943VKwR9whhvLT1zGmv/RESbcl82w==,iv:XK8HQlkSSP1NGw5uKwJ1DehCe5jUhteHZcUBAiqMHHo=,tag:6O8RM4WwNqTfI9fB8bAUWg==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:qeCdycDUEajg8nYpgjIwzQzOnaUdew==,iv:l+5cNLLfT9Rm3SQ3AEqS7C1/DlV1sJId0R0j4mLjKuM=,tag:fmjXON/vAWKL366diveInw==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:ePZr6AnIUWSV,iv:r20KZ7zIWBPRFu4cDBj3TP7rUhhjYowURx2L1O525Bg=,tag:zUEFPe5oTo6xo+8kkVyGOQ==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:WGy3/bqabZc9Q4b9CIVC9GoHTGIu,iv:jihINmqS4Jncs65oFPx+nX+z/kOGaFAz/DS2GXpi7ck=,tag:jnaVN3k2FNSNOooMOUakJA==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:M8DLvZ0Xt1rNwBoseYjqkQsEXO4=,iv:igFYPK3cLDURf8dB8+i0ZcwAlRLbwx17gNAWXA/OIRw=,tag:zM5hE4ZBFzGH4SvqxQjQTA==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:NS3ikOPvwZVP54Ym4Q5AmxDSuQo19syIcmPS2L2e9ajqGaiMiWRv+w==,iv:BAnlRFpAeE6Y2oU28jzJN54WbV80l6eabZk1Dyj0l8g=,tag:syNk0FYP2+Jd5ZbCM2WRxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cnF1YUZCSE5QMkRPVmZh
            MkxIbHhZOXdQTG1scGdLNFg3ajhkNVQ4dFdJCk9VNlplZlRUWGFDN3YzMUNhdkJ3
            cGVXY0NTY2E1OU9NNW5jcEVlcDFDUk0KLS0tIFh0SEx6ZzN0czdZZnRsOUZJeFFq
            MzZXOTFMUlV1Y1B6SEprZzFyam1IVmMK34ZDzG73SvkQWYQ7J5e53D2MMDQnnWT8
            ALwc8k2rvf9bH31uPdXAxekULyN7k9CAt2l1hUNmzxv4cGq4Nt/P2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-24T16:23:44Z"
    mac: ENC[AES256_GCM,data:hzM/EvQ34XbEgr67J1+BZUVs1gllReh2nqq4hovjcsp+ZQKtlU4RfNDS9A7nnbEI0y4st31npJR3tRPhahL4BOeoEt8sX5nOoXWdynunUO5ARoz1Z2qukSrSbhYEznUYSr3FaNmILMvU4jOd8AB8jicDHsVZJcL2F0eYyjhQQE8=,iv:T0TOBhj0k0VraL2nyF8Vu5ICamnPa7NqPl2iuL8yM6c=,tag:3aEcUk7H0nqmtp3ZgAkpCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
