apiVersion: v1
kind: Namespace
metadata:
  name: kserve
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: community-charts
  namespace: flux-system
spec:
  interval: 4h
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kserve
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=kserve}
  chart:
    spec:
      chart: kserve
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: community-charts
      version: "*"
  interval: 30m
  values:
    certManager:
      enabled: true
    kserve:
      agent:
        image: kserve/agent:v0.8.0
      # storage:
      #   image: kserve/storage-initializer:v0.8.0
      #   s3:
      #     accessKeyIdName: AWS_ACCESS_KEY_ID
      #     secretAccessKeyName: AWS_SECRET_ACCESS_KEY
      controller:
        deploymentMode: "Serverless"
        gateway:
          domain: kserve.${wildcard_ingress_subdomain}
          localGateway:
            gateway: knative-serving/knative-local-gateway
            gatewayService: knative-local-gateway.istio-system.svc.cluster.local
          ingressGateway:
            gateway: knative-serving/knative-ingress-gateway
            gatewayService: istio-ingressgateway.istio-system.svc.cluster.local
        image: kserve/kserve-controller:v0.8.0
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
      modelmesh:
        controller:
          image: kserve/modelmesh-controller:v0.8.0
        config:
          modelmeshImage: kserve/modelmesh
          modelmeshImageTag: v0.8.0
          modelmeshRuntimeAdapterImage: kserve/modelmesh-runtime-adapter
          modelmeshRuntimeAdapterImageTag: v0.8.0
          restProxyImage: kserve/rest-proxy
          restProxyImageTag: v0.1.1
          podsPerRuntime: 2
      servingruntime:
        modelNamePlaceholder: '{{.Name}}'
        tensorflow:
          image: tensorflow/serving
          tag: 2.6.2
        # mlserver:
        #   image: docker.io/seldonio/mlserver
        #   tag: 0.5.3
        #   modelClassPlaceholder: '{{.Labels.modelClass}}'
        sklearnserver:
          image: kserve/sklearnserver
          tag: v0.8.0
        xgbserver:
          image: kserve/xgbserver
          tag: v0.8.0
        # tritonserver:
        #   image: nvcr.io/nvidia/tritonserver
        #   tag: 21.09-py3
        # pmmlserver:
        #   image: kserve/pmmlserver
        #   tag: v0.8.0
        # paddleserver:
        #   image: kserve/paddleserver
        #   tag: v0.8.0
        # lgbserver:
        #   image: kserve/lgbserver
        #   tag: v0.8.0
        torchserve:
          image: kserve/torchserve-kfs
          tag: 0.5.2
          serviceEnvelopePlaceholder: '{{.Labels.serviceEnvelope}}'
        # alibi:
        #   image: kserve/alibi-explainer
        #   defaultVersion: v0.8.0
        # art:
        #   image: kserve/art-explainer
        #   defaultVersion: v0.8.0
        # aix:
        #   image: kserve/aix-explainer
        #   defaultVersion: v0.8.0
