apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- envs:
  - params.env
  name: oidc-authservice-parameters
configurations:
- params.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: docker.io/kubeflowmanifestswg/oidc-authservice
  newTag: e236439
kind: Kustomization
namespace: istio-system
resources:
- rbac.yaml
- service.yaml
- statefulset.yaml
- envoy-filter.yaml
- pvc.yaml
secretGenerator:
- envs:
  - secret_params.env
  name: oidc-authservice-client
  type: Opaque
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: AUTHSERVICE_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: authservice
- fieldref:
    fieldPath: metadata.name
  name: AUTHSERVICE_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: authservice
