kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:b5+lt7x/suSYrMsM,iv:jOlYcgfdedHFJ5THbD86PhmenV0GTY2W8MCgu6xFR7c=,tag:RDnpjvlPnuqWfUOos5IF0g==,type:str]
    prism_central_user: ENC[AES256_GCM,data:9f9vxNI=,iv:oANyCgfRdlTtI1byCprjYTavk55DuxOpr2ydkV44FlI=,tag:BVpN8CNe7xmb+76eZgu0Nw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:w3pOb5qMt6HZvYU=,iv:fJRAZm9GSSsfOiGoOkmNIR/TAFY1ls13xMcDUdC8UQ0=,tag:snob2kx0fVotSNwuu484xg==,type:str]
    prism_element_user: ENC[AES256_GCM,data:sxfuGkU=,iv:sD5riYRd1R94PJFYdLh0MfOH9y3jaqXiL7F+ZDmWXSU=,tag:6lLtRBbagO12nH+HYWwYmw==,type:str]
    prism_element_password: ENC[AES256_GCM,data:xIWqQhIQPq23/bI=,iv:AbigGu+/DqW/01OARW4hRrP+dknnGNnIODxU/nP1P8o=,tag:aoJD/JkC9pBRWg5hcvQQmg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:BqirzWBOxsSL5tP1yC4xwgLf7euY79Cct/dfM9VGuxI=,iv:jmC1ZtsjqdT2cEnwVRy/2TTrMfy7ZS9iKXDk6UCtbOM=,tag:lDNm8I7pAfi1R9CliQmbvw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:7eSFUmgD6hILUOJaHwOZb3BRESHH4LymXXRPp4o6HrU=,iv:Hqw0K7GKNwTZYbniJHK/nDAYaOdZmoX6p3jZhr9vOfg=,tag:foVLxNaDnXMNeYWdmtpdrw==,type:str]
    github_repo_url: ENC[AES256_GCM,data:gdknR5zO0okiSecysZvMTpVzBqMRSpsoEtXl6b3jLHyKJtFc9dfpat4seyuyRoe3NVZCng==,iv:OueNPYyIcLPbq+8OfLzOvo9hIRDvB/A0QHu/S3MXNn8=,tag:tnvUAOONIr1nbbuCM3yCJQ==,type:str]
    github_user: ENC[AES256_GCM,data:Hb998Q8D8/j6YlxsqJE=,iv:1/BpirBzNmLV4pqar3Oxanvq4HWCa5YMuXjIG9RFDY8=,tag:Fw/cU+TNr3t6fI1sIk/1FQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:Ccz03A/H8RSkHRUtcbbfwq27BKcuqxgKHpjhD1EYbgYqjn1ILhExZw==,iv:/0tws2zddTYOoQS7zdNks8EXnurvyR2jaqARjxZGaB0=,tag:5zdJsbkcs9ZGeSggucqJbw==,type:str]
    github_app_id: ENC[AES256_GCM,data:FgQ/DD0v,iv:/tMPlVo6C+h+ltjtCtETxHVuxi3SDhuljEEWCD327xY=,tag:E8lRJzXLbbhae77d5bizlA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:areRuSr3qyA=,iv:WK7EVD3XjljApoSvwRzN8BmidMcaas3c2ujKlhkG+O4=,tag:BSKyZ2mH/gK26xpLTZ8j+A==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:YjOYFE9J0Kc=,iv:axxWnD1R9hIBcybgIvDuAZzUSW97XS2y9Xcb23u8t20=,tag:2IrFkuzECBS/71fKFUGbZg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:QcAjDwqRtNJuj8clzePTIC7jA/AToi4pZVwp2SvAgiMFbX/q,iv:aJMFvO5CQHuCnqe1R+CawaCrSJ+FrwxhTkR9uRcf654=,tag:vkUouLxhF4wk+ioaMwX4jg==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:f9iGSETW2kbCeL1E1IiuXDkmJhY=,iv:3Fvfnf7nQn97OLzFNS3yeSlmkRgfDSKfi5i+EQOKpN8=,tag:sfR2XOoUbMX4kttY++P9Ng==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:hzxsf9ISyzDazyrKw7JOEr+w0/+1ck0S1KDQJyNvyfFUPc6WIBXnOA==,iv:8/lrEanLa2fhgkvSh+m6yr0fwQzcvpFlG+q3ktK1kpU=,tag:5gXuXQelb6aR9KxAqWdKfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc1FnMHRocXJQUmZEMHd3
            ZG5TVERFanNJSW10UkMzTnpyYnZacng5RGxBClVVZ0JOMVZLSFBDZTQ3K3VuRkRM
            cnJxUVZuaDIwb3pwWTR4ZzFTa250YlkKLS0tIEJZdFFxUGtwTmI1VU1iNENUbVV5
            dEFMSlhXeVBBSmF3WkZkcExTKzU5SEkKg63EhXSsKEbME3HhUn1lVAAnzz7pIoYV
            lrwphHFIWRlp3b8PZond0LkkDJWREgTmFDaRefhy0qZ+vB+XUcmrpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T15:36:03Z"
    mac: ENC[AES256_GCM,data:Gc8aRoPwrqotggn0A/9wvn+kgXPV3QmCsdRzE/Oor40NsPo7e0+uG7VtrzOXZrrnYZsAJttAUDcw8PDqjHZZ++Jp6WiJ0nmf9QRTOid7NsYpFQ6+tWSGGQkXRezNCnuoG0AgF1f6zOo1RPf4KEzOQgww5S9xA3pshk1A/+QqhlE=,iv:00D7gycpr8AUKiYknmwVEwgKCDrRUKYFMZK/la0M6Dw=,tag:laZNjD2EguCpJV342/STHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
