kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:CooH72Jhz9wFOv8w,iv:E/aswWukm3PcGX1ibF/VrBvDgzK+B/NI59Rv0Yw7Ocw=,tag:9tPf8N7eiYwcDPQBByQzbQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:20Qdkbk=,iv:9mcgMkyI53mtyhuifaB2dsifB151rlzH4PC/YhiHR6c=,tag:3RLGH4zRwG5tpQTxEBBt2A==,type:str]
    prism_central_password: ENC[AES256_GCM,data:B9uM6JKQ4fR1eaY=,iv:jlufXixxGhQdekea2Ln/gtAvEkN37Y/363K1ZZqmeyc=,tag:lbrMBbSivWBYXoXccnkz6Q==,type:str]
    prism_element_user: ENC[AES256_GCM,data:x3y3V4Y=,iv:y/j5PXLFU65Yi9udI5waa2aO+kwq9HWf2FA0V6RaEuE=,tag:6x7obnS0TJn1UtFlq3T7Eg==,type:str]
    prism_element_password: ENC[AES256_GCM,data:C/Kg7a7UUYbwJgE=,iv:gScqhvxqvMkGbwG1VN9G/tpB92FR96KcKXNohUcGPI0=,tag:caO8qyV5Egh9/zJH6K36hA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:UfT+3t49aBnsNM2GartABzhXvmR7YkRS4JUNuy1kuxE=,iv:7Lbl5vYteuFdAgbX9C2xlAzP6xBDBVVlDytrHbzZSMM=,tag:Xg3GSsbTw0jamTBV12BltA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:XATzLnrkic7p7+sYHbu/qSelLJ6gPJOZ0jepbTxT/+M=,iv:wlclqShVcGBhEFTxpqV5o3H0qqq+1t5I6femHjibwpk=,tag:SL9NFFwQCpCY/Z4FZkrfAA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:W6CIPEb44lgWRH99xYe91DSNq0IfVY7SBirWQFrufioIr0XsarMPsQk580qF/U1HCYB8Lw==,iv:5jTYTjIFb2VaOqBqNnyTL0iA4Nbp3Z4/ds65RNWM8Z0=,tag:n9f0npIWVIwQxO135B63ig==,type:str]
    github_user: ENC[AES256_GCM,data:EzGeT4oQut9z8hDngq8=,iv:eu8yCS0mZwMkX2sYxR6cyXVveGXDUBJ+sno8rYoXSDw=,tag:UrzdL9mltiMTKvYQ/j6qsA==,type:str]
    github_api_token: ENC[AES256_GCM,data:Npnw123KbGYm2chQ1QuQAWD5bBPN1g6L+QMD9vtkOKzag0Ja9TmFNQ==,iv:qbUbwitE/I72i0dvtye3ouI9s94h0NAtK3LJqtUVfls=,tag:b3rPoW1ImpEZT3f35pxaxw==,type:str]
    github_app_id: ENC[AES256_GCM,data:+95vC0LV,iv:dWYhqCM88ylNFBmPx9wasA1eqOg+lPXkSYuXmsAtOiU=,tag:DZkuH42iMdzHsr39cTATkg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:lKxbhDO6kw8=,iv:WTa79Q/yOSRZIq2zU70uU67eInO/Qs6jQKWajyXiPlc=,tag:WTywVExT1rMAL4vVbDv53w==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:baykcbPnEqc=,iv:Q9WIJR3peO370haI2AvfMVD06Ss4PUJE92OyPNKwN+0=,tag:Z1SsmNGoQTYIKgKyD9gdvQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:QOq7KH1CyVb+NBWRRuzk254jd77hcnHOtpEcvHVzX5MxjJP2,iv:dBHEHtZYqkbVr5mZ02PBR+btCLv95Vx4XblHlJNw0LM=,tag:rj6JiORQtj3X/f2GWQk0eQ==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:lgoqYt7mBa+jFfyPiSbZeieSmLY=,iv:E8EseESu2NDoDBAIsY9dFQow7woy/XBvIPzAOUBJflU=,tag:xJfmkoQkh0D/Mwa+QS828w==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:PT/Sh3RAUEl7In5onAyZQp8r2MwVIsNpO1ayvYu4CDl4REmyqyIr0g==,iv:AR3prMSJHvafbx14250KywpwJYsoVvMNumSocOk/Rd0=,tag:NCBqVCMB7w6sRkq7IMH9iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bDdhM0RXOXFQSW1nQXdZ
            b3cyU296QlFIcUNWZWlleGFaeHRjd0V1dnhNCmN2MDJoaVNvV2ZvTnR2WU82UnBr
            Q0NvczJqK2pQSnZHWXRobjExVWNnVUEKLS0tIEN2MnlvTVEvN2RQYVdXNXA4Ny9X
            MmI3bVhPVUJMeGRERTlacHhtZGdJMjAKX7BEflVf+921nTwpamC3qvWpKh9hkG+L
            c6+ILsBRo39hkQCqKqIIPEhM8kgfQY8YW9piTk0LGt78tDkDqDcPEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T17:48:47Z"
    mac: ENC[AES256_GCM,data:4Bbe137o4d8klC62r7lJyyoqIdb+l85vd9ODSSu4qtbrE19bCtId/PernCUKXyy1LDSQ2cANtMfvvK7+JOx/LgJVmBJMsl8w4A4xZVVcSSLbU+xD30Np4C0BHrngkzDFi5a5lMPoNykvyK+s400A1eTulIharCK8BxRx2uF+qKI=,iv:OXGeAuri97G8qV9AMJk65IlrzDyR/0jNDx+AGGCZylY=,tag:GJ1snKzR7YA28UjnBcD+JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
