apiVersion: v1
kind: Namespace
metadata:
  name: llm
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nai-llm-helm
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://jesse-gonzalez.github.io/nai-llm-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: llm
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=llm}
  chart:
    spec:
      chart: nai-llm
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: nai-llm-helm
      version: "*"
  interval: 30m
  values:
    maxTokens: "${maxTokens}"
    model: "${model}"
    revision: "${revision}"
    nfs:
      export: "${nfs_export}"
      server: "${nfs_server}"
    useExistingNFS: "${useExistingNFS}"
    repPenalty: "${repPenalty}"
    temperature: "${temperature}"
    topP: "${topP}"
