apiVersion: v1
kind: Namespace
metadata:
  name: llm
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nai-llm-helm
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://jesse-gonzalez.github.io/nai-llm-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: llm
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=llm}
  chart:
    spec:
      chart: nai-helm
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: nai-llm-helm
      version: "*"
  interval: 30m
  values:
    model: gpt2
    revision:
    temperature: 0.2
    repPenalty: 1.75
    topP: 0.9
    maxTokens: 200
    useExistingNFS: false
    nfs:
      server: 10.54.78.48
      export: /llm
