apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- localized-files/github.com/knative/serving/releases/download/knative-v1.10.1/serving-core.yaml
patches:
- path: config-domain.yaml
- path: config-features.yaml
- path: config-gc.yaml
