kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:PkAo2AhSiB7NsCazCaAtasnEOkuyNo930C+2uxA8zgubrpZLqEMJBj7OFwwQR9mSPHG53JtdX+J5,iv:1yE7MnmQJFw0w3nBTCZ2HLv+JrYQC0LJBnRT2+IYsGc=,tag:hIESe0/4sEoN+nloUBWgiA==,type:str]
    github_user: ENC[AES256_GCM,data:qdHab0+M4dD0GTaB7ag=,iv:6bejDcDY1wURmA7ERjrwKUt0L5BQ81KhzJnDYI4fdWw=,tag:gMN81DzOiMhek5AxJ4qbgA==,type:str]
    github_api_token: ENC[AES256_GCM,data:6ZbaBDIObkn0jhupwMJyUHKyk1HACx4pUjVvTBYVpElDV6SjkGXB/A==,iv:ZoWU0IaV1c7nIKkWju+PdxwzZU5lGlQ/aj3NtkyYQjM=,tag:AoBvr26rUDOR/fdjSoSNjg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:80Ad4Oyg9qi2,iv:+f9hNvAkHG390Hn/VKVwqRrZplHa7BDlO4ZUR3/HeoM=,tag:QvQ9NAwgvU+teWlHXjXXnw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:CTZAmZpK7+LgA7GOlJLyed4WIJ0=,iv:gKF7qk6Do4hx1Ycpvokgp/qcahS3oduyA4z7cncx7mI=,tag:nKH32AFeymFn+Lh6QKNKfg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:IIrycxbPVLgZzdT+2lMrMuE8pHsiLIKd5R/MsdW6pnbx/rgURA==,iv:5UJR1LgibT9Y1r7Q4lndqjAV6zNzXebEJa3uHB6L+wQ=,tag:c7g2UNmZnba4gAB8fU6qww==,type:str]
    prism_central_user: ENC[AES256_GCM,data:iLQayWc=,iv:98OLmolQ1YPFTX5zTryoF9hkE+CGkqHo/igyPS/J50k=,tag:BArsPs+5TXh+2u4jlkd+pQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:b3ErKvPaVQ23+AE=,iv:xQs0gKHsUYVaiyiFSidwTfOoYjgv7xhzoHZhc/W3dw8=,tag:3bDndcjJaJB6HFaw+xHC4Q==,type:str]
    objects_host: ENC[AES256_GCM,data:tOOY8ZMLsuNWVzLYBasFH14trs3EeOJDUt7/SR/JbTHfbMpX0EaxbECc,iv:C8THYSzAgPiN/zyC+yaX01yMat6BaDobyk+OanKOxGg=,tag:TrZdIZa/o7upW3C1a/ZNlg==,type:str]
    objects_port: ENC[AES256_GCM,data:668=,iv:9e3Tk6OHlwEXCgMHLADREBosjYF8ZTohaPJSHr5LY3Y=,tag:kN3azI/Dgq1b2rbyU2DoRg==,type:str]
    objects_region: ENC[AES256_GCM,data:YdETluPHQqTH,iv:l9SGcQmp5cKZGHo7fobI6QiQF1OElPGbd+FhSrkGFnw=,tag:efJmsECMA0V3TtGXV0iatg==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:O8Ayjuc=,iv:hmp48BB2UTstSor7kyYcIQqS6LYTPqOw+Egk/icnTNc=,tag:KQmTEFHMfmRfKAsQ/xXg4g==,type:str]
    objects_access_key: ENC[AES256_GCM,data:UY3eSXeC5z209Z5eubFec+toUpEq6Uom10X+41MglCg=,iv:9HdBl3YY+SHZxdP6c1XYHlHLQJO7H61a9kRIWdz8GP0=,tag:dTBrFDCtFvoOJRKtLMWqlw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:sP8C78Uf8xNJ32lF0czK+izLGn7xZG3PaI0I/e4c4Oo=,iv:+jxdFIfKEnw47PHZbJs6Bmg57Cz0jdpbNH7OWpN0cDY=,tag:sei3OungWLgSRPfpc8Q/1g==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:TgVnrQSQM42TuJsqPwUXQwU2tmyE3QuTWA==,iv:WTZh3EeQVm24bIGjc/vMulik/AY01SMljRMF3pRdKP4=,tag:s71VT1AgIFByHucJ3PB7SA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:cBVOz2ikQEIpSwieAEup,iv:MSs0QG1aDPG9coQ/vJNv0XHA8sSKveswdP6gNMk/TqE=,tag:NT31wsTQKi1z45oB9V6RBw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:/mc3w/6AVoM4oBaTLXwTOBYy+DpH7IuOREktPFiFbg==,iv:UOc4Jgm9rnO+rZ5iwJwZGm63MWQxSlNwqJVmUrYsiq4=,tag:M/eB0Gr3TF6OGXBb41b2gw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:iFZR7tat2h8IFE8AiYG8excRVbpsR5FFNWUwNsnMT2w=,iv:nqYCfV3wdGBf0Yrz8YbfXlHDDS68nzIwG8UmQtwIJHM=,tag:jwjEiHW/VwfgvfF3rHgNXw==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:A8WJ0qGuMYzVdEPR5N6u,iv:GmRZ/6n1ct6CnNYoE66ruiR3TuJshiAnptT3O/jOEjU=,tag:hnAyH1i+KIfflpijCIkq/Q==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:U7GeTaIc1Dd26TjRFst/mTuoJz7JYo7EVqaXDwUauQ==,iv:UIGmQD8n8Giuwtv1arSpWlWKPKF7i3swApdv9NBrwOI=,tag:/KR/3R1yvNB/PZGVTMbD0w==,type:str]
    nfs_export: ENC[AES256_GCM,data:uY5OUVIGkHdV2JtRxkVlOA==,iv:Wf0sdiDpYlE2VFAnQyZjulgoO9hwOa/Y3aTUW2I5Gwc=,tag:BMxgMmhi5URoOo67fUPkhg==,type:str]
    nfs_server: ENC[AES256_GCM,data:wM2CC+uMPmAfJiD09giUrRBKwxZ0dezHJEHOw1bB2s0wCjsRc3Dsnw==,iv:t1ya7WzboAzDdo5sZuANaY83FjBlDovliuZDxXWHiGE=,tag:h5+JtGGziCq/8XAxOYoIUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akw20gxdussq8503jml0ccy64vywysc56t66sygs3ktflsgzsf9s2mzpcz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSWdnaGNtaTJtNnVjT0NG
            dldBYzFEZWp2TmlkSVZ2YnNmS24vTHZkSFNnCmFobGk2NmprVVdEcWZBazN5THk0
            NEJHS2ZSdUhGdlYxL29rbWdWNXA3TlkKLS0tIGtNQUdMNVVMQjJRWkNBZ0RJajJ4
            bUhVK1pSaHJvU2k1QXFoekRjTWY1Z1EK+kW1SbBcJz6p7CARUWpr50oAQhkTGPAY
            xyw3rpkbiwNrtIAIgQLIdWA5vXcbPwZBrzfOtQewqEh8xGGo/0zK+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-25T03:30:16Z"
    mac: ENC[AES256_GCM,data:eEahv9BLGUKR8ote6KePnkx38uQ8toqdzcdW0kq0Bbd0dlO467T4klUUXcWS9BC0B55MFMLkIhhoUOtWyhKpX+7TdO5ijnNhDSwVCWXoHpzALHDyINd5Ysec5qQsUxF6szFVa0k0qicAsOPDQwkjZw8P1/92dabEIC1eC+4vRWY=,iv://OTsXZXJwPdLK8f1tZ6DRtse6LgEqq+30/ZR6oi/J8=,tag:AELqniiwdQpXma30vLvbzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
