kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:4E6ibnoZbZx627ffktIOLqnAMuXlYgDMXh2mQE+4WP10oY0Uku0dBzFqwC27KHwiYUflePW6ylHn,iv:74OrYItoLibZA8+g4XW72yoj+ObC3zP4an3nhUGyd8g=,tag:9ygxtnPYoRCNMzjwS8r3Zw==,type:str]
    github_user: ENC[AES256_GCM,data:UuuXQQERYW0IIw1B/jY=,iv:w9uqxfWZNpf2KvxrpnulB8F4CsImzR09ekCTvWk6t9w=,tag:pXOGVkFBtj+fOTvikAALoQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:zOl6NvR6NfFiL9e8yVlytqWFP8TG9o+QF4i2vgH3NP7xsmOE7WUI8A==,iv:UlNmUnOZFBoCE72IOijM9n3mH0OooeowfUnickmKVlk=,tag:8GUlRmmWS3IjQasUFOlWgw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:AdSg9dNe1FY=,iv:gGWWDGEp3/AEdSIiIE7etba+iu7ZTxmBt7skw6K4XT0=,tag:biLcxE2Ax/0M/LWZXkuPyQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:DiYR46DasFHUvWBXVWi7,iv:s5+KyhtSocJvl38juxUlq3TP8Ct/OhFzGCb7EUeXYMw=,tag:YKnn7boXJsy8RjIZ7CGCUg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:UmogjNEvYpMaT/TETWXHnCsaHARErrIaw2+ADADWjA45zb0BiQ==,iv:P+MX4oN/UIYpAesqpq/ywOlf/dYrJ1tmde7tKUam/8A=,tag:14hJaVqr5Gt7Ck6DenQaHw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:N6Y1c9Q=,iv:odrpAt5TdO5zL/2k5rBBBNNhFUaxnZekSWqS3JIOYj4=,tag:fOrx5FtpyUNLulppachI3A==,type:str]
    prism_central_password: ENC[AES256_GCM,data:bqCAsTsedKMY1Xc=,iv:RiGknsBKsqF8qo5jhTgmTxOMVuIEiBEyyfVPTq1roHU=,tag:uH3/uCSHquew4H+R9e+RvA==,type:str]
    objects_host: ENC[AES256_GCM,data:AkCE+PK0Q+TxTcFbXhhlOq8DAOR/vPSpEhxiWB5nqwVu0u++eTX2qsub,iv:X+cNnBiwzRHyB6YxEL5F6Pr3//o0gSJI4mug5P90zD8=,tag:9ZkBx+r1BkTUKz3ER1SSFw==,type:str]
    objects_port: ENC[AES256_GCM,data:ExA=,iv:xoGmKNUighLJJRycqjfFjulwOIbjwgZ30KO1UZWaAMU=,tag:JecrGOTZqFeeCuTQ0lSIlw==,type:str]
    objects_region: ENC[AES256_GCM,data:CEenqv/Gir/d,iv:HOc0EvYxRkwNjS/k1SUmbMTueU44F3V5ZYM6aFRJZsc=,tag:0rw/uhb+v8A/cfoG3oWZ+A==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:GcnIz3A=,iv:JO3v97y5svlX+715taPHpFEHH2Q6J5jywwamp75jzTI=,tag:0IkdETaD+X1cCYcgjolq6w==,type:str]
    objects_access_key: ENC[AES256_GCM,data:75BSya6mUtrE1FUJVJ1PlCTvBoe4YjcBMIRAJTKi78U=,iv:2yhrKiXz059s6GG1LXe36siS3YjertnJtvGfCz6LqQk=,tag:tcdR5kIkXzpUPujSFmyGyg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:MLTNWArtb+8dogRIli9uwQ1xDbtSHMwN3joPTVuW3ek=,iv:s41Nv0rRwAjZYvMmf8YEm2xPbl/qVrF0K5SCA1alSPc=,tag:7z6SAa1UwxW5cGglj73mEg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:xPyCMEAxtTbxlXayKOfKjCYXToO6FIX5MQ==,iv:mVzfEYX3nezKZzjs/GwRJJBP++zsVYLjZZvb/Kk1Hzw=,tag:gxJy9evTUrl1FoVTnV3stA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:NBP9Z7ZHonm4009SoXkq,iv:/bJDAx2esEeTZih12o73G0m3Qh/Bpgx+lSaSvKdSV4w=,tag:xB+OjjtaukOhJU+OdPEJtw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:XsiE/kodgoTD8DhK2Zx/1yTdqQoFTVWSN03abp2COg==,iv:ygmZ3FzR3/SO0NO7NB4G/f733IWZFMQUQBHtGzh/6Kc=,tag:LeotHu17sD6ogyBM3TRnKg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:WNlWFWjtxepVlWa9MQlttZ+8fRJrTZAkaJobK4XnD2s=,iv:YtO6Cwmnntvq+Ufvgc+bWKsJ+IWDCcaLPuChehFFO0U=,tag:8uoFm7fYPbFSpisi4EFNCg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:eEw8rbLKql3St+MgOoRn,iv:RajULDWsXfRICxHEAx52JchFpeDrgcG9L2tRvAP8gsU=,tag:ikj4fQduFOIPuCyCJEUXQA==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:anaX8CMvqYqw44ZG9d1uIlGxWBJIntBhuqsEa2x6ekc/nCw=,iv:toPEHZbH9YNJi7jD/ORlOJV3Ek6+kABvaXzcZo08LBA=,tag:7bJ3Z4FAfvCnz9m2/2EgiQ==,type:str]
    nfs_export: ENC[AES256_GCM,data:l2GxLstP5ZwRvo2qls5RNw==,iv:gsWLum21+TiewF3icqSK+vBMZzK5gdPKzDRRF0uc64g=,tag:uvZlaDnbhp9X0WRIVv3CPg==,type:str]
    nfs_server: ENC[AES256_GCM,data:viayNjJHLOD+RgICIjCBbfeCTQsvcFkpyxCVO04HhNUu7qBBOAAgJg==,iv:k5ehLSsSXNERGZXF40z4biBCpy14FbJ6Q8eiH7DcrvI=,tag:JyFNP5uOBeFBk2EcLRXitw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ0pqaGR0cGIxTTZqRW8v
            eDdHRnh3SXczMTZ5N2tPNWMwQUZ2VkE2UGxRCjhDN3VJMU5nOXh2bXpJOUdrSkpT
            UXkzSDcrVG9zNWVjUkJlamk2OVFLTlUKLS0tIDUvS0NrbE1PRmp0ajN6UitGYmRl
            ZEJjY3ZrQXRpTVhoemNtTHgvLzRWLzQK3ywPT6qGtiRH5LRe6k4YaLiKNGEgL5IO
            nZxWH6gXsUZ9pfCQkwXiSrF+cTT0RYwvtfbV4ruqsVVHJUMiRxZh2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T09:59:25Z"
    mac: ENC[AES256_GCM,data:sVreT0JJLq0nHGJVEG+mRC9uSq0iJAGqBldWr8EtIkb0lNoIpjiBex+1YUaL4X/M6Rndj2N/MbedpLveqot8bK6jOV8T15kpnEZVGH8O09Iyo/fGKbDpuRVI9DPB+YEtEI+HIXlElqg0LXn/VQP+gWbfjwE3nLOx3mXGBsWfIfg=,iv:UoYYp+Ly/f41xTZzQ2+SLPs3Xy7OA89slywpP0elhA4=,tag:LrSab+dxyk75Ng7oB9pGAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
