kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:XaDNCLq5Y+7J4DfTdCW2zl7ogRY5UctgZM1DHWQz4a28eTf9SbURSKFCTZQQBXMuVsZQNJyvMhL/,iv:0thKMet85t4a7x9QMApz7Ap1jOrGnLMI2q7QPOrV0qE=,tag:beY23tKYWza3+m8Kf3swyA==,type:str]
    github_user: ENC[AES256_GCM,data:PrhZHPqtDX1bzUfqKB8=,iv:61zsTs35yO1kHQJr+XN7CzdzGjhGgSH40kcrXx2n7Kg=,tag:eKHWW6q3WrZsmuJbUtmM+A==,type:str]
    github_api_token: ENC[AES256_GCM,data:2+YzNpDFAc3QMQQQfxxe5wGeGDpt4/RdJT6GdsxOWlwFKNs0x39Bkw==,iv:HC6fxiXIb9pJn5iACOAvyx7tdZ6KwtqAoh8qaNUzFL4=,tag:jatr5cMFFBqZQtHU1ouNhg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:In1+Jgs/F2G8,iv:gE0VVWfTGM9g5wxOwBuPPiJR64koSXgVUxmVuIgo9rA=,tag:0KcgpRxaz7I53qPH8mIGeA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:jBwtefTdGp2hrA4zPy8PtpiJbS8=,iv:dynqkDCUSsH/xCdKBBRpcrPzMMyOdNmQMjigcIUrwTQ=,tag:y7AR4Y1PiOMBBqVkSVGmbA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:Qn++QWdg8+xtM1//44dl+D+4vsyNGlVPbr5JT2CbErweiGd9RQ==,iv:mP9h/KGDRAsZYNvmHiKmKGn/SY9368QEIE/hxHaZ2Qo=,tag:K7uQCkJ9tkrR3GHH7wR2jg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:WyyU+1M=,iv:YeqrGjymRmG9ctEoyHSv7vK/Sfc/6Ypsmqhpm9cvq24=,tag:olRc6NKoWzU8jIRUGWWSAw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:RYBkoho4Ni/tQ1A=,iv:Rc5mOxWXDMD4B4dhIEcJ4ywtSelitLKK6ytDnFOrj3E=,tag:CMFRcAdfqtZ1y7/Z7SbdVQ==,type:str]
    objects_host: ENC[AES256_GCM,data:s8qMmJMtrCqxMOs5eJDm2IUG4116BMcZncE9tFp/fhArl6dvCdCS3jax,iv:2yBjO7QenITOtXEJWcHxNr0PYec2cnKewimH4akIwPY=,tag:yFaRTY0FAnMyGejuwPNPTA==,type:str]
    objects_port: ENC[AES256_GCM,data:qAo=,iv:X4iWWkORChb3ZTln2uSWD3hjGjA0DbkCy8XmFkqkqUA=,tag:iS+TuvTUdcYJeGyQgZvUng==,type:str]
    objects_region: ENC[AES256_GCM,data:5VonTcKFMf8q,iv:IySLI4mqefkeBfqx5ARkkD7BetnLBWZ8dBJXIIk8M9A=,tag:ez+ZIPxoI/rXEOxfoadP2g==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:j5EQkQw=,iv:E25ZJBj3YXJhTYk+RpInvArKSv9+9+Ofecqe9C/KszA=,tag:DIseo8/J/rJ1EVj0F9SysQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:ibCnVnpUyXiBC+ogOk+MFFdYVVS3MG+XjF85xdD+UlM=,iv:D2N/aW9Mk7ayoPw64LD3M+rE+/oHzhpohjM1aSUnTyA=,tag:994lh72JKcbmyF7/t9vaqA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:5y8yruHJyC/njD+DNU10+v5LC+o05NbxYN9+JgdFBwo=,iv:o/lkpAq6b+3MVw3QWYACRRsM9Q9CsKn5dblRJ7PGckQ=,tag:3NqBNkBkRnza38fv5+IkxQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:mL5yG3ecsymvV1DHPdXjgymNrs94U2eHag==,iv:eN+sCj+8CNU8O1wcEVTUK9k6EDZEa/ErP5XKRlgqgQ0=,tag:osD+ZTM7+Ikaldg8G3Za7g==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:w9uZfGRYGjx3GJa3iUva,iv:7ESe6Aej3/5NIaDtQWSsiMZ9vVn+OjpJ+F6r/yiCnZU=,tag:0FY7VWfIkW9xICo5XR8N1A==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:/XOvPru+dCtWtWq+wOaTm9ImhnNfXSN6zoDUP12pAQ==,iv:UOzdtCbSYSFwK/k8bWQLv1n0+NaFYCk089BsyHb2A9I=,tag:QXbr1iygDi+Tn76lAwLJbA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:Z3TKUUxyq8Q2s4pXSQ9Fh6kpFgGPP9jxtvVKS1Z13Fk=,iv:fgjbJk11PS7htH1CNUoHKLJeN8f9ldPjVrsChzMSsPE=,tag:xNjXFvmhQauJMfcYnJ1F8Q==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:WcpViVGXYsp4pJH8wXaB,iv:qokQ4GJ84fvd1YTpPNFds0mI4hdlXPnl+g/IC2YNPXY=,tag:3kBwVB5w62lZdv2s24LYVg==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:Ozf+iUoDEkyBLaMBdvkskTRBMEjziyKyto/1961wUg==,iv:aG07/vyF2ooP7/Yq7dXXqS8rhqYLCxMLQrl1vqbHCJw=,tag:I5MgrKCp3MAPE+unujSLnQ==,type:str]
    nfs_export: ENC[AES256_GCM,data:sTLOd/16OpUVLUC5NThgXA==,iv:fGihbmvjmPrsqbqU26m7s2NyfH+eG6bv1wgKIGNq0gw=,tag:yGbImXEDM00mAFXrz0RNxg==,type:str]
    nfs_server: ENC[AES256_GCM,data:BzJx3zf8idbWeyb+ObxZ7Br9pfGC15NxLrtCknpZFq10dXbnTyvCOw==,iv:4Fk+iNBLD84HAskCNr6lKL22ouTznNE0C9p/sxA1/I0=,tag:4pGLg1W38RNzQDfN2GW2Zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akw20gxdussq8503jml0ccy64vywysc56t66sygs3ktflsgzsf9s2mzpcz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOUFCUmVGOXBJa2VIa1kx
            SkFrVVdnNGh4cVM3MUp0Y3RDdnlaZm9kL2lvClZPWXREbFNDTTIxNU0rYjVqbGIw
            RkV2dlRONCtVOEw3OVY4cy9hZ28xN2MKLS0tIFJYbUo0STlsOFQzWGRZQjhPTXVZ
            NGxCc2tHV0Q2ajBlTjJoSDhJRTVGQVkKMLgP3Z1qw4FmpX6Om4UoAhjVlJ5uhEQ3
            FabLGPBUYACitNrQMqMDY2vPRdw/R2/Uleg3o9TOFPs46dqCrWW2qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T04:13:08Z"
    mac: ENC[AES256_GCM,data:gGMyTp938/fQh8iUJAO8eL7vdEN5RlBEbhgMeJ36FfH+RTTvXzoFDk7DMgeZESKLbPNASuIf0OjAmgn95O2H6V0Zko0oNEv9Gb322XqYicIGGynAGR3b/QHiRUAMV3PwOZpblblZzT7S+6vFL+i6Bnl1OuHmkjxP4wSYAKkf5j0=,iv:LRoP822pcwGE5EnMxuiwtLjrcHsynjWP7atXi2AIOA8=,tag:xe+jiD8Et2GPWRWI1LedPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
