apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  values:
    hub:
      config:
        Authenticator:
          admin_users:
          - admin
          - jesse