kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "nke-t4-nai-llm-wkl"
  environment: "non-prod"
  cluster_profile: "llm-workload"
  kube_vip_ipam_range: "10.38.110.21-10.38.110.22"
  kube_vip_nginx_ingress_ipam: "10.38.110.19/32"
  kube_vip_istio_system_ipam: "10.38.110.20/32"
  wildcard_ingress_subdomain: "nke-t4-nai-llm-wkl.ncnlabs.ninja"
  milvus_objects_bucket_name: "milvus"
  documents_objects_bucket_name: "documents01"
  objects_host: "10.38.110.18"
  objects_port: "80"
  objects_region: "us-east-1"
  objects_use_ssl: "false"
  gpu_cuda_toolkit_version: "v1.14.3-centos7"
  gpu_time_slicing_replica_count: "2"
  aws_route53_dns_zone: "ncnlabs.ninja"
  aws_route53_region: "us-east-2"
