kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:w7pGEXUVS6061FfeqrZUNkbyhEghJ7VbS6Fy7QhOCfTkkEBn3yyUlMSm410FQ3GCssRUo4x+t+u7,iv:KrYBVodpahGOmAOM5R9IB3DNFs1BVOn1y7njvCYMo4Q=,tag:qNaYIWMRmhai0PTpwwPihg==,type:str]
    github_user: ENC[AES256_GCM,data:EEehfq5Do+AJMzwKabQ=,iv:zxhCSWivL+yXap5KlJWfdTENN+dAZP7IOulQFTbfR3s=,tag:Ck9DFb0Yn3ymS81eT1+vFg==,type:str]
    github_api_token: ENC[AES256_GCM,data:S46uKOLlYZGfygDksNj/SN5VmcT5A5MutLPu19bUdlEi7mflJ1QohA==,iv:to6Bu9EWR5+zZKBToGvu1vOQgplKjK5zUwPVfyXwP80=,tag:/Yj0ha/qLk7LFALYd6EDwg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:ICZqC77ZkFA4WzNz,iv:Wdh7fByyIBXQGifzyD439qvqKHnMoUP9mSsjlrtdLDU=,tag:w1GHxIrMm3wnw4vtl+vIAg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:d8MjTUXYfLm22zHtj6dg,iv:7upy9GwwZMhBr4/LY0I24tujq5VbarUFXFP9s0KKEEg=,tag:kVe/Qo69itgZFyfltz32WA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:kQ5hYbM5neVh4MemvfmfAAEY0ZWJT1iWbgN1qzfYbJA=,iv:CzJTj53Vz4tlDrtQbjrPFlgHN7alwdOw3sCdnANm+U0=,tag:K9ukexF3lSD+8WrZhQbrMw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:RardSeo=,iv:OhvZ84YYqjMgTwsDb8v3h80hlz+AsB3GUYSxBEcej/c=,tag:Ge8adJGRbCcCNqY9LUpU3g==,type:str]
    prism_central_password: ENC[AES256_GCM,data:AZIapOiOiismR7A=,iv:e/GrydkLyQejWxv00KWU8Z7BT2pSV8RA7u4iaKkd278=,tag:NcOixGvo2TMnx/3m+YePpQ==,type:str]
    objects_host: ENC[AES256_GCM,data:ko8A1vUeTrtv7b3lvXShX3SMZ+LvmRdiiS1Lknpxu7+x+0klqg==,iv:GrAQ/dpfsVigrOH3zIx4ETj6Lm+MN9gy4qVITt3pITs=,tag:VlBxUs3c0ZHR/oQ2f1ziGQ==,type:str]
    objects_port: ENC[AES256_GCM,data:MEI=,iv:r0XvSwhJcnOy2GihTLkgR0KuYciy90n1o3Zlmz0llt4=,tag:uhTL1giH1w34jZeNaQbblw==,type:str]
    objects_region: ENC[AES256_GCM,data:cn1UeToZf+3h,iv:y6TByIg9NGg7IuR3jqGqnjNTAI0a4tGZLylY9QERWko=,tag:X6IDNcjWJqIh0R+3mH0Q7g==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:/lFE9qc=,iv:ctpdkAfJoacuNEUH6PTQ/fTutFnQGakyejaYcA9RbP4=,tag:czkbbJOJj5sOjjSVJHpdCQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:tXwr4Np79p3OwerAaqcXp2EMTxH4OS0eJc/j1N/zhUg=,iv:dh6kZ/K6Xz8rhPvGnKwD7h8bUlnm/ZF9Dj2sa1LAG6Y=,tag:Wjpx5z43HZMYwlTiVzVIoQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:d5fK+T0eGSN+xsYcdaMzTxIOafJCTbBHAvaNgTGwTNU=,iv:oaeUbXJ/un5Lp8JKB2Mqy8klHefbed6RvvHJY7qygK8=,tag:dinbOa41DeBW8F7M9iDCmg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:L/9Wm733yxMuvjDxP1tV/HtEMMYPWec=,iv:atuMYhmviYfh7Bk9iXa0Kq3dAWjQOLpCUA+uHbnWndY=,tag:/1AT/J8QHPJKnYVEKR2QmQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:De0YVaD9S9m+zw+QVIE=,iv:M89gM6qroLEkv/369PSDFYLt4DY+WwNf11pmhWWTcN4=,tag:KfNYl5qK7b+n+bAvvwuKiw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:VwNtY3RYftnaRqKoWGObnpnEN5YcEU9ATqmCooKKTckuNCcai0MI,iv:PT8kultSXB0wP+QT2k55DiEi6GwZ4/TThMgyDA+7jxE=,tag:fkuXIG8BkjpbuwVZ8s7efA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:USELtCcgkdxQVleWPlr0KP6m7+vZRJ/0L8Adop2xAg/rTqW/GDVG/w==,iv:MAM/2+GC7kQQSOCkpDyXZacx3CIQs08gJCVRJ4lGtxI=,tag:kUc14gizmtU+WVn8V8QAuQ==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:uTiOi+n7irnACg1V25k=,iv:nmsyUSqBSDPwaSITfuaanj9Td0yK4HuSPQ9n0BU0USw=,tag:zlvQCnDoHC60Y6LYcH76OA==,type:str]
    istio_vip: ENC[AES256_GCM,data:Hhm3KtKZ2qZyK30=,iv:Eigg5p/Igg6qq8JJy6mPjGZLCuUv7DDNqOVmk7qtX/g=,tag:wn/1+kPxGZZKEWv54YTb9Q==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:ZrdEKcTPLvWuUUqU69YwLQyDnGrOf2FxbbdJxtrBIcngyxb+1/So,iv:+lw49JVwEKSV5AnjUcmuEUk/0BiIgJgbAOijc/XE5K8=,tag:7o6a+J0HeQmMXi7K5+1nFA==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:ki0/KEgwBikJNxXdnYLeq546G6xkwNSlLy0=,iv:lIVGfXyjXwzN2UHBKbFMFT2HdQbDTciXiT2kloH58CY=,tag:taO8RAih9RRNNtWgEm1vmA==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:DZdHO74Hxye6f7dNE/XMW5hvt/osmg==,iv:hh3Rne6Cn27ABgoLbfUHV1kMlgXaOg/DAdwZHb++ocM=,tag:+k206un0ythmL4WSgaP1qA==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:FaSajixCBNa7,iv:i8wnsTwirkXmP6+/yIAsjDylYq49NQyfcfjhUKU5Ukw=,tag:9jhCGz66JOHEosavAwGzPg==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:+I0B8esv7WMBFl9pL8CchsxOCdKh,iv:XHWl0oqLOAWOOfZ8wxDmpB7JLOU1tSisIe3DWnnmje8=,tag:6jNKWPZaZz5l/x+VHwTG2Q==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:1quyK0WhPz0aEqb67dwplh8LUjs=,iv:X2pwtYI/A8n1Wxoh4/8UrhpPzVuPO9u7BDCWHHgL+bo=,tag:U31ff4FrHFUGOHQlXgy0gQ==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:/ExbCf0kdUAgeIgIyTwY3KDrl3EhmYbDknlyaDTVNjo4hb4QXpPcBQ==,iv:VBrHv4hCdbXckzkH4o1JLVItfbe5RsZ5K81/11ofAb0=,tag:rfGspZqKJZy7sNSsDl8D+g==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:EyvnH5lbTsRGb+3k+p8yFUsdCDGJFES2I6TaxysXKzTkrjAhQgz+lC4zHUhO2grxfdx5q4IrCgpwfIlm,iv:lSHKG3+WDPCUKA068uRNzXyvwnl7oaeMnZSdwfYvdjc=,tag:bhsqe5qvQGGSCWHO0BtJDQ==,type:str]
    jupyterhub_default_pass: ENC[AES256_GCM,data:AOx5xjEsBQqIj/jS,iv:bAfaBvT7EZlNco7+iXOCc6fQaZJogH8Eo8MWUv7Rh2U=,tag:ugAG7nrJ0FFn7WHd5191cw==,type:str]
    nfs_export: ENC[AES256_GCM,data:pqsarwthj10C4rKMWQF+fg==,iv:bZSuEabgnEJd5g4lgkbetp871O4ptXzwa/KVPO48eek=,tag:ncgXDKQUFiPLIhHGArftpA==,type:str]
    nfs_server: ENC[AES256_GCM,data:e0Fc2oP6nUIDIAKRYF8Eqr5Nszs8i3vHbpVewmyRpZ50cfc=,iv:HYN3oFaTPLDPYb0UdHfdVme5F+rmw4oDYk6wGvrygk8=,tag:zMg/YltIRZ3euV3iDVOvBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHgxV2JWZ3puRXRkT3RR
            V0V1cjloaTRWcThnSUhDeDdGMmw2LzdobG1FClB5K1lpakdmWWpOV0VtdWgxRmRG
            dTNhVjRtc29nTW1QYkxKbW1EMytpcmcKLS0tIDZhZUJMcVhuRU1zOUZRL3J5NDJV
            N2sxM1l1TXlJZzNaZFFTejdJVk5qOHcKtxVAGJ5KWP80WWNtQGGEe7S1QoZI/HK0
            yt2f3UtuwZWvHbmhSTY3GyQklkd9Dxa3oFG9x14mRI0lLMULE2kRTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-24T20:38:48Z"
    mac: ENC[AES256_GCM,data:q69CechvKzjOZ+erkGBFR+VTO7XAb6kzqcPcnqD4jwwNHWY+Nf+g4E1jHxYyIlJAiABMTKXLgYdR1e8KzYuNtHhX9DOzFafDMfMtg2SPkZnm2JMg05M4TgQ48PLFDRB/og0ymaHVWEDKlnqwK4NTSeHjhW5JrMc88HnGd/27jpc=,iv:/mDdLi3MSH0PZhhJZywHukKF2QedBZNQjO8vcQNcd90=,tag:xtgxaYr4wVwH63/0hTwoyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
