kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:ONW2YLor4pkdzHYqwQQr6BsafpuY0bnMHgWC+sk5zLvIH6On4x4SxzdGtwALiEIaktI3Cj9rEPxv,iv:I34iD9jJs3fifJDJDGapuuVR8mYTl68ga4GqSZOV7vw=,tag:dJFSIxuJJeDJADmeVEcpPQ==,type:str]
    github_user: ENC[AES256_GCM,data:5wbMv9P/VdWpetpTnJk=,iv:51Z9exfrwosEq6De4DXzzWY3LrYGgvvj+m0tVIoNjro=,tag:Y6abV4CORL91oXipVg5Q0g==,type:str]
    github_api_token: ENC[AES256_GCM,data:JXpTBYBgKlCKRtyHorPwZeyRA18rwXM3gjB6fpbhxZvO+pl12h3ATg==,iv:y6IynDNhdwoKufj4W+ersb9aK4m61/rRENr+mXcIVwI=,tag:QSLOQwhfm0UPYMyvm2qEew==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:/z2nX4BTPlbEJOOk,iv:fUxpXnfudInLoavoNbqFTNOM2e2O8sElMbmOBVnbT48=,tag:i07zv9YPz9LqJwblCQVGhA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:yfdezI9j+Y6QLNU+F4a1,iv:buU1zvcTD4Fp3uhbh9LDeo5XYWc32RbFZYVtomJ5HKM=,tag:XsXqsAbx38zeILKQnyp6RA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:eI8KzTxlEhgW+vqLvCwNwXbdjDlTSiOQiYze8C6ga8k=,iv:qQs5yc6L5AZUtfUO7LqRiF3zEZjGsz+YBAMk2JSqJqQ=,tag:0g8tjs61Pg9YhRJBaVpobA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:67WSork=,iv:QC02ToSgI96bAEJprjTHBJDw6cRkwxuuYaN5Rp7t6k8=,tag:UIc9Zc1w/ytLx9ve14WrAg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:BQVG8YR0PBi4QVg=,iv:ic5Qr1cftyzrRoYoc4enEJprVtYaZW2RmeMjaFWoTP0=,tag:tuF1FpI+W89fYYSVm7Z5Jg==,type:str]
    objects_host: ENC[AES256_GCM,data:VMiNcAvzcyW5KmtD/7zPnNpPZxSEjchxh22ckemjDtFSin0j2w==,iv:FGnhA4aNrN9tVm2q5kSYXKDccwgemt4CdWtUwF5d4jY=,tag:aw1xYjODvfCI+Y99SBEoUw==,type:str]
    objects_port: ENC[AES256_GCM,data:yuU=,iv:vMQh001ZP+T2Q7+fJymT2/UJ/kCrtFOLgldEtWOawac=,tag:4aVqPEwaW1yjZwMG88V7/g==,type:str]
    objects_region: ENC[AES256_GCM,data:iBXU9kyvJV+2,iv:hwPHHxW2bEkK58qsl9qb1Bfzag67rM5GddpxATwoI9w=,tag:k3zoSZchBrNk42LOce7T9w==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:nQMMfkg=,iv:qF8rpSmdIWDpUDH1m5LgF1YdlLcu9hvXG1xq/4KNob8=,tag:3h1AnrMyuNYFnoUxqsuvpg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:qXa++0nQ/ap/4CLYw2PYfQ2+wMpIzxQtw9AdXH9H8Qc=,iv:k/pHLRxpG3VlFcCKPvcdpjctEcpfgk+52IyY7SJhqio=,tag:Wrb3sIOlaP9Lx12S/0hchQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:ySsvaPPnxfaQQ/Aqbd07OgUvjoB8om0AmZQyvIrzDJQ=,iv:TJiuTtAsSDvUNjnpyfbKyDzqnC1KxJ41te3qhZOczAc=,tag:7JTMSNJsoENRurIcFLKyhA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:vA3zbi0OMZGKMPUyp/B97nOD4jfq2rU=,iv:XREP93uhnYhnSutrVq4t9nlYehpX8tGABVbDLLjFdcY=,tag:+hj8RmF/t4iqB4NDLla53w==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:qr+4Vy/eiyBqirriseE=,iv:7pRTn4FxrKMAiCiQox5JVIBrQU+fIKVwVIpuI69HaZY=,tag:lrOBVEwiOpm8f1YhuzMTOg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:a+JMoZCxb9eTCI5O3Jq7OjCx/TloSIKZsaoMpXr2rEwT/yJzukYx,iv:FeEtXc8J7+z2YDi4JsapU5i4hkaYGu6F+OpCsXc0vsU=,tag:iDD9bFPpLBQDAFP7pjymTA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:WQrNRMYUHO4knO5BG2bb9grPpuda96WsnFBsMcOCKvQZq1YQYo/sPA==,iv:WGNqMWBaOxMxTFnvjCYDzK9bl8CCH5iLZYpKjQl7G2k=,tag:4fcZIsWotlIWILrdSUg9Xg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:/gSUEwknVvYsPukv6eU=,iv:j1MUKxk0ryaSfb9FJ3xdUYJpkWK/fvwSsxDW6okZQIw=,tag:+Rk0sSoZ+e8uovoeMcUvBA==,type:str]
    istio_vip: ENC[AES256_GCM,data:fSR6S9Zd7veZeT4=,iv:ksfgrsiwMQN2oweqksYP5JUXKUGvWxT1+lkVA9Xv6xQ=,tag:n42fx9l4XevIuhIWP+OHAw==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:MrB5WZPSQlLv5KDO/GjE/wxAzMPRD6/1oO8HaxdRA5RHqcq4DmnJ,iv:+rkKBXscz9EapEo486poN1258RA1fye59B4jMyTAUcI=,tag:tt0SfKBr7Q/02/X1tzZDJw==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:saJTomY8JznA8G3NHAewLYseOCpvRLzxE3M=,iv:zAWd25zJFF0JwZGnEb8NAriPEAeQm/O4dp5dAXajNzU=,tag:GudZgEXrMbRe53sg3h6tOQ==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:gWpVn9y2ZV4bDFjAL+l710jIAYYbGw==,iv:vACeqw+LOajzMFHTy3Qj1FaMiuSsKpXw0J81GEG196M=,tag:XPc75KwML1bd/iE7StoRKQ==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:pMSMhhAIjssu,iv:2tE4BWQP6Q8KurZXXt5D4yFtNWEXXbpG28pW/zjD8bI=,tag:Q1OzsU3i9xIJYf9k/2G+cQ==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:8678d53meD2kBtgNj05bCYcvskbK,iv:fMkwTLe+qG0OC2ED9SYOrSsPNazzW+FyOR9yEh44Jjw=,tag:ZlaXI94DVFmn2CQzGVyXlg==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:570wD+7EtnITPrj1H0u8GzIAwwg=,iv:BvkpofCDEI3ZVTZDTTc2193eGkepqFtKrOLPN52s+xw=,tag:UAXqeWPgGr1hQgq1t6kUaw==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:j7hNMVS5cFa8VP9fhj7eN9/zUrpBZpJqTflPPygbfYFnSXDf9tIdDw==,iv:tdc/xprlLuE0AosjxI1KC21WNv5sT0u4OOodXJyy0DE=,tag:v8zVP4I93N/R5cpNGbzn0w==,type:str]
    nfs_export: ENC[AES256_GCM,data:uC16DkjsHaptzUH4HyFnmg==,iv:bKNs4Cad8IOl2WPr8kXLkzA+EJzSqGnPwxy/r7UM3W0=,tag:D8EOjLvHY4QMCxJPxkyInQ==,type:str]
    nfs_server: ENC[AES256_GCM,data:rBxfz6nmJzULHm4vEy1HpGVDgKWrXYaj+CozopdhI/etSnU=,iv:bkHn3Pb5acSQu9YHLM+RbECb011ZmYe73aDs1chYMts=,tag:GONlXCtZdtBwdg1FEFNCDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmblJpY0JyVXY0YXVJTXNl
            b2xwR2ZEdElCakJiTFp0SHp2VXozZTJjbDB3Clc0dXArRHdLV1NRVTJOMUNEL3hO
            THFXVXN0RkJsdTFQbk5YMktGMHZMbzAKLS0tIFlUSGF2SnhRU0U0ZWxRVk4vSkw4
            cy9JUjNWeVc2RWc5QS81MEpOd00ySTgK0DZDeaIkZWEOkLT/xLUZh/aNoVkercKo
            u/l2KyOhKlCQQ2xzEx5YgSR028zaPwRTVaHYozIFlDH6BATP/KrR7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T15:44:55Z"
    mac: ENC[AES256_GCM,data:EOXjc26+/zNH+KBTf9lFmctkVG2HPg2By8wivop9C54wabx5qZdRoSYBiKUocCRRcllbHtbGV6x/MfNrD4sLn9T1Ubd/8/qe1tzH1EwJODf/24W0FZ7fIsP3hoHty1vs7hL/6AQg3+gyeS0Quw9GcNDd/Iw96eBPTwvh0mZS6dM=,iv:AgyPX8Vr7t14Cjs4sp6NLlGrMUDSgDnKu+Xi3eDvsVE=,tag:GVg2WAYMT9gUPimyc2zyZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
