kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "supportgpt-mgmt-k8"
  environment: "prod"
  cluster_profile: "llm-management"
  kube_vip_ipam_range: "10.50.126.134-10.50.126.135"
  kube_vip_nginx_ingress_ipam: "10.50.126.132/32"
  kube_vip_istio_system_ipam: "10.50.126.133/32"
  wildcard_ingress_subdomain: "supportgpt-mgmt-k8.saas.nutanix.com"
  management_cluster_ingress_subdomain: "supportgpt-mgmt-k8.saas.nutanix.com"
  milvus_objects_bucket_name: "onpremsupportGPT"
  documents_objects_bucket_name: "onpremsupportGPT"
  objects_host: "saas-xidev-nuchat-bucket.s3.amazonaws.com"
  objects_port: "443"
  objects_region: "us-east-1"
  objects_use_ssl: "true"
  gpu_cuda_toolkit_version: "v1.14.3-centos7"
  gpu_time_slicing_replica_count: "2"
  aws_route53_dns_zone: "saas.nutanix.com"
  aws_route53_region: "us-east-1"
  model: "llama-2-13b-chat"
  revision: "c2f3ec81aac798ae26dcc57799a994dfbf521496"
  nfs_export: "/llm-repo-k8s"
  nfs_server: "files.gptnvd.saas.nutanix.com"
  useExistingNFS: "true"
  maxTokens: "4000"
  repPenalty: "1.2"
  temperature: "0.2"
  topP: "0.9"









