kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:Dz8JXL9BN1jSGrhbv5rvUEHsTj7NexoZtfQOJXsydQNHkr3PNZdy,iv:LWjBH0RE5V8TwZ6gPROXghHCyz8p+WP4q/EPBC63PuE=,tag:xHoCGs1r8IgYfpuoP9wwzQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:4wpW7Uk=,iv:ydfytwhGLjPcKB4KIcS8+4vDbvcsVANfmk16SfAcBYg=,tag:SMrdB6VJ3zOLIgwT9YvlSw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:yHM83e0RMZKEjNJ1ruDp8qadoJPbsvrRd7A=,iv:0Lk8T65ClLKWUMWyRDQh3RykcqQE9WxrbZVTNed0pEI=,tag:AR4KRFP+24y5TXevxd3SXQ==,type:str]
    prism_element_user: ENC[AES256_GCM,data:zWeFCQA=,iv:FeTQ/F0n8ip1slSGgQn3PYPfRyJrLwWQdiK5jrLPK5o=,tag:6tE6g/uXAKXMKKTtlmuB4Q==,type:str]
    prism_element_password: ENC[AES256_GCM,data:7KQaVUFf3bfMhLPmy2XO+Y5k4V0xJMwSWBw=,iv:gUf/Cl3R/QdPFV4iNun+vNVRM9mWWpUAaNvrlrAU+Go=,tag:D8kL5rrH9SrAVii/sAmA+g==,type:str]
    objects_access_key: ENC[AES256_GCM,data:qqd3cguxLq7EVYVB8/w3W8Cmb10=,iv:wBuEGMadbm8D4YqmHMzjAC5lyWOf9UfSXy3QPC+TvXs=,tag:YtWgk/A6FGvcA7jwDiNnoQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:P2D1zlJQfOnaPrS1Cg0+Gu+jH47KTZjjl6lzufI1KaeuD+Rw/hWW/w==,iv:IY/lFZTQWpTY48ngrs9CN21whe6TShKn15ruczgSvh8=,tag:N8BqIVecmRU/JggUf1ni9w==,type:str]
    github_repo_url: ENC[AES256_GCM,data:5AZT1Pj8L+rln4WSLBw9gkVE0yY8Ecmi8Sl+0Q0t9QB7wukToKlljHdKfCpLV+2k0khVq4o=,iv:Xjh2WLalshpTzZXgzL3HKv9jbqrB1ijdAMRPWXm0C/o=,tag:owp9wK2R46uDWjjmTlTlHQ==,type:str]
    github_user: ENC[AES256_GCM,data:PBVpQv9lsKVRiL54R7Q=,iv:B+c+k30a2jgdY3mNwCKXlwspMSKf4zg8eXpNl6EESlg=,tag:P+FFZ6UN3cex19F64J53+w==,type:str]
    github_api_token: ENC[AES256_GCM,data:bx72noNIIi2Aq10AV+v3dp2PDfUsTHIxAjmZUYAMdgGVWqaIG4eFYw==,iv:xmURuAmVYC0YV1qY82pngjOdJEB7A8C/n7fNkX/4USI=,tag:O4eWmV204zI/rW6LPg5gwQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:5K/VvTg2,iv:gp6iadet1gVrJTISQa4NZL8sLKvS5Xo2Vt9xt4fB6CI=,tag:00yHyCfDc8JEHzMS1sBP5w==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:kjLB9zY3Em4=,iv:IuQ82oiyEr0ClFjHb28gj1vWFzugMYd8ZH7aXRM1Ds0=,tag:FECI/O6c6n9+nfvZ0F/wOQ==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:Y7pskXDhJ/Y=,iv:PEbV2KW4tw0vhplbY0qIik3hbGXwDp1vh2bjkXUkp+I=,tag:1MV3LICcYgcPdTlS+B9bXQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:EZff54sgtwoFFGU32qX10pHtBJvS6LrIlIYYAieYH7XFtbT0,iv:Vk69oskLispK21p8eqxDHrK9vUPIwCFhF/MHlcwAq20=,tag:txen9AXiVuQlswo0cLabtA==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:UzHD9gRA/7zDBl8i9Y7VbsiCm0w=,iv:9rCjVaO7Aal1/GB8hGKI2trkHY4A3oc3IOHnCDqBZAU=,tag:D5g4ckdy/VKlumFfdaG9Lw==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:ObRUYIXPhg9U0dOyRzsrloN/O80Kjz94OZYS4/jj8oqqKEMafTywGQ==,iv:WnMZepYhpTrWcz/yYE4yzwhts4E6YKsMKmdV4qZ7XoY=,tag:isjAVwsULKiZ6QjmXjksjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWTFXZi9YZzA1NDBjRTZu
            aGNlQjZ0eVpYdENPekVEUzFlbXNRTCtOdDJzCk41WG93MzZSSE5xYWx0MXJLc0hJ
            TE1mbkM5NlhYM3hMYlp3SUhYdS91NmcKLS0tIFhvTHVBK3hhWUQ3UDd5NFZ5azlo
            c21KOUdHdndkdjFveUdDMXVtZ3BmdlkK4c7ijjK0xwRmXP2DL2zU5UcTmuPcPpKd
            83NwgirHe7nOtREa1Eoeo4kVW3RgjcC4W+DRtPA9Sy2xdvH6IBhrWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T20:32:11Z"
    mac: ENC[AES256_GCM,data:49MBtECBGzaR3xvtEVhAP7jK8RIrftQdNjqkNh/wGl+pyvleuwXwxkHn5GDYyFDIMUWfnwEiyvvUVODtBia8OCU9JXzEnwkhBI6PTc80vPT44EW9c9b8z/OtehtXNbAXhmy27WgZLcOYjaoVBkWv41b9kdW6qOimTbP2OjrxfmM=,iv:ZFjvYedQkytIih9PgPWtWFuq06iYZUNNqSCOhzUt0AY=,tag:NVowoja33x2/m5ms0EUXsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
