kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:iYA4G+oNWTFAd2C4FWCn+uGAFsH/5OYwml8pUsJAuyk=,iv:b83YdSawcghO1QNkLxcbyickKcHNhFT+H7HVeTsqmtE=,tag:n5/kWxGaA5jnI3bt1MnDYA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:IyBYyDY=,iv:fciDdDnxCRjNPeBbx/SAfJeCgprthqqIGp1lQB6pfLg=,tag:aHCTwC3RDQwZ4R5fYvr86A==,type:str]
    prism_central_password: ENC[AES256_GCM,data:lt9dB1zs723eJaQ=,iv:bHVMtYUP2FWJwzRboPsJOVVTiCzxbWbpOziigYQUm6w=,tag:Myc+xatr+TeAIZUVo5rdDA==,type:str]
    prism_element_user: ENC[AES256_GCM,data:59NZgXI=,iv:qIw/hc3p3n7fuD9qGvWgF7moMJEbIlgECuu2S0Yz4yg=,tag:c1k61kDkadQz29+lvKD0kw==,type:str]
    prism_element_password: ENC[AES256_GCM,data:L4F3G/gjkI9h29k=,iv:ZTBTyIME3mUCEBNGTWxRc8PNu13jJyQfb8hnsHp97h8=,tag:6bxxcSt16DnGYysEN6aXPQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:lPkBzyKkDb/HoKMw5S+j1L+dc+KM7UrhYtf5HcKE1kw=,iv:AP/zr8jSq94CKzIuH6ewMmZwLchAeg61TZnfjSi/rmE=,tag:kOdU+5heknAM4yUAW9Z1oA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:OGz9e3AFoauF3yk7RKI2hZGNlbWi+3U1pUkg3Ubxs8g=,iv:MugmHo0EE8+uauyrG8pEaEPcDUzPNhJZr9wsRgjs7BU=,tag:3PcLkXsZrARvO5wuQcykcw==,type:str]
    github_repo_url: ENC[AES256_GCM,data:G4ls1jm5/gn85gU+gg0i3rdFu4wpokEJuFQ7z+aN+Q3w/HRN7NpIZ9iGhnPOQWBRtI0sxA==,iv:sGVQ+7bzCV8hjI/MEoYpUW8HOdaV4ePUKS1WJqgewLE=,tag:4sOitW7rnL+2LfgiVJQ//Q==,type:str]
    github_user: ENC[AES256_GCM,data:33/2MQpsXtc7ebmEwSw=,iv:huXkQHS4t3IkRkQ9QHp7OanhaH7E3vW1FNZwAvpA+1U=,tag:B+4+SdP60FolPJ//GhlsLA==,type:str]
    github_api_token: ENC[AES256_GCM,data:zGWJsv3im04emIqyNkQs0/kJqIFJhpSJ/jGwffJd5nTKQAKfzWQLFA==,iv:QTtsNPaL5FgAii8qoONue2Fo0suHAF2EuDdZ8QqwEZE=,tag:x94KW5mmS2NlHQ/Qy4Tb5g==,type:str]
    github_app_id: ENC[AES256_GCM,data:8cX+3NgR,iv:3Cb0QCNYGEGfPCCJs1IXWea0x8oaNAIVIAdvXHTnDJo=,tag:7mI6a3YDHqdaK5hsBNJBaw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:3eSfEPb2WDE=,iv:sWBULvnuVM616UFr6k+GDsKLf4D5yxhcKQWJDUd1lls=,tag:fJVTqBkLna4rZmPgCu/u8g==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:qBN3S+VA8LM=,iv:u9BZzHIZ+DF8Z/JRfTZhPNQeIKhjad6RONzvoaIBKa4=,tag:nH8Vs5CmW3hhfqrwle2CGQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:M6w15b1hRfEbm+tKTsttifHBXoO51hdQl5DlO+oBh//bdPix,iv:N9vsL0eKXE1iIY8IMj0D0WQCdB4dGtsUVGbL+O5+gRc=,tag:o82g+J3fWN6dw0lWzBakdw==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:jM7tnPryViJlxhBcIT/gTEP87Xk=,iv:PvDCnO5q53RCz7qOGK9YBLkcHpWoI61w/IGbacIHqzM=,tag:Jhv6QidEDZ0g3jvW56+G2A==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:1HioHL4p/BgK+SB4S7qCcC+6YqESN4oQ1xRxPHj32aGgHCNQytsDnA==,iv:JOh0NuvK9fwmqJfdqU0HZ7r2UpQjG9jHnHR+wEkqhcI=,tag:x0O5AgU0A98kRXP10lRLJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K29MNlNzY0luYmZvOWU0
            dDBlK0ZBUWI4L21PRzdHQWVoc2o5WDgrdTNnClV1czhmblZEUExRSU1ESWVoOUxa
            cjJZUmtma0daSjByMW0rVjRURlF1WUEKLS0tIEpmVS9KK1pwdFBaU3pKZ1pXK1NU
            VE8wNjczYy85cEtCVzJaSHBvd1puNk0KxIohxLUjn4FIwk3Sw22UdGvuoSFu81CO
            Wxs1lMjSXnWI3CjitPqL2PZOL9qt4wWVxAAxjMZWBlQLM2J3cPDKWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T17:53:21Z"
    mac: ENC[AES256_GCM,data:dUKpUnmkq3ft1WFORDysZyGzw1MWCFD4idUaPc6fYGzwlzpT8Ch4Yq2e03DmzFig96ikARguA2hxjaN3j0xtJ8xVV9Pn0IlCYy3ZJBh4AXyaiLRkH3xvh44Xfhzebg98q34R2LxnfiW5WKkJzl354uV2a1RpHMNYFOARvcbZ/T8=,iv:YGNmK+nFAm5pqU0+q01TXWxtiBmp0rFDG8LUD3o5EgY=,tag:3aAIyiizYc9+tOKDV/7WEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
