kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:VT7uU9fMClbIYAQaFDbNGFGn3p2ibiw5IU6A342TTz0=,iv:XphfZwS22OvAgvsoEBOM9Lffqw4oyjIl6KPss7Xe06c=,tag:4u4Ttl1yrwDsSEvDA/E78w==,type:str]
    prism_central_user: ENC[AES256_GCM,data:c953FaY=,iv:VybpcxF2XDvmfMAWZjYV70DQG9WuEhex/1xzyYjR6lk=,tag:cLOVpA7L5VfJtEyxdO09kg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:XhzpyYuc7TSQCnk=,iv:UmcDZrsH9s/oHbK6Ts0oV6wGOfJg3sT9iVxq16D4IbE=,tag:tM2kWBg9EI/SOCOpjesgug==,type:str]
    prism_element_user: ENC[AES256_GCM,data:GVA0aro=,iv:Sxfh8mIIxNuFQ5S0q9tC+alhlDwMbY9KbJCDhNEHR7g=,tag:Q3xC2V9uGQUWanYhx9K+fQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:zKvQJ+bBRQgyNhg=,iv:3Z4yS66vustLRiMw6LajCHBbrNCcxr11zovM2EVIteo=,tag:fLxE++AfrU1382Zwg/tUog==,type:str]
    objects_access_key: ENC[AES256_GCM,data:VSFepMFyfqgXQDKUgqP74fYqe0xQLxLCik/W7OllO0I=,iv:mMmm3lcHU6wzlt8ObP+ZDyTbYxyJ2LWuQ2kaTQOxL5E=,tag:hgGpQby2HyVqpKeTprP+5w==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:RkG6NCCBS2ouXMLbKqrd4a5q+NIX5yHpUEkEhwFR3Zs=,iv:g3cARs6/mp605INZw9tEx8zyc4Ax45fhJzYqvedw8YU=,tag:uqwUU0J8Vo2+pr+OGCPWoQ==,type:str]
    github_repo_url: ENC[AES256_GCM,data:hq6Jf/hZKQu0HAFbVEYAWfVNA/pGGEuBNK6Es2fN324kR2JmkctP8tR8NMfDKINqgHxo0Q==,iv:o+SQZ/L2Tx3DGjzD/mJNzs+7rFtEoDKP4ZRX+oMPq44=,tag:Bf5p7+GyvPCHBZzgoUKa9A==,type:str]
    github_user: ENC[AES256_GCM,data:bao/8dkOlbeRCT86lww=,iv:Irbd93aYNy20RoC6Zf2QVKHyC8FFsr9Y8MTDZqAByTw=,tag:o+kwfocUSObGWL0yLo2mWA==,type:str]
    github_api_token: ENC[AES256_GCM,data:V3iA+fRyWKplzEfzuxhcw79uzGURnjgfkBQPAnoLXLvJ6hYQECn9Lw==,iv:nNqYVNYdnNsuAHLThPVISHXuvnON3C9ukFkIluZGOhQ=,tag:tsSe978G5FOuOkM7JInXBg==,type:str]
    github_app_id: ENC[AES256_GCM,data:OKEWmtL/,iv:SKooOHlrCuus6Bu4Ry490yTZZohbkngbz3PKluQYKsA=,tag:IrQYXt2FX39HEUy2yvalqw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:tlz92H5y73w=,iv:5tzvTUdMkEPKV19xTlVGwFzBl7kzgDybBBXoUPP33Ao=,tag:8PxGEkThUV8iLhfxEDNfsA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:e9hh0tGQ7aw=,iv:oRb6Abr4k3yw9QX3eJjwNc9vuwFyE6h33Tuzy7QX66Y=,tag:qpt5iuE+cPtCBb476gYXjQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:YHcucjqVpgSNTx+6U8cgngr9718QVq1l7FvLM7FzAYuHd6T8,iv:u5jDEBD0WvkxNFmbj9Y0MzBTG3Iku5w5cYQZ0dzGYxI=,tag:G2nBN7uxj+dHMU/if8n2NQ==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:VYBmITLHhwDTt8+a+BgvJHCqp3E=,iv:e7NAJbwml5G4MOF2T0METeY+Kl85T4ubK1SYVeKZYc4=,tag:GmblE27FbgiYBJENw0hWog==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:mn12RawQgVvPvdmVWB/j8EjySDJRmlBjAnLmFxwN9nW8TSd2MC5X8w==,iv:OgKImaDy57qH36Cx+PDCZ0FyG9jgCvkLjMkewHAhmP0=,tag:QcgeNcWMtFBd6Qt1pFmWvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZGtYRmxMSFdLVCs0VjBB
            OUtTTXgyZ0kzbTZ6SGxVVGhUNmcwaUJqbEJvCk9aN0RlVFZYOFc1cHo5a3ZBNHBF
            aUx5MzZ0WThMYzYxUTZYNEduOE9MamcKLS0tIG9saFhRZzNkeEdJSHpWNU9yWlhP
            a0FoREJCN3hHbmd5ZExBLzEyQUgxQ0kKse5UZm5DT2xPT0AC8HxslsoEiHKn9X2O
            5giEqfbtceIqjlflj0pDBCT5O5g/6kOoeoab9omPS4xv48XicEJ7Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T17:25:50Z"
    mac: ENC[AES256_GCM,data:bd61l2oaRCseAMl+Ocwmz9BSe4luHxX5NongdBvZoCZYv5Kx/ocbX29WrqLNRRFPz/FWBx+10lfteiuEz8PT2uk5n0onBrMm7TxZrKs4RnWKjYP1O3DZgyoC+cuxsZbNc5l2CFMj7K72Q9QAsyk+6TBdPYtuqOep6jtA78Gs+ho=,iv:sYolDAgJGrdrFZTcgwokm4H0Wv6Bc4v9ETrKNEg6Cxo=,tag:GCqPIpItxO19Fh+VyCCjtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
