kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:HUiKKUnb6C2qL1ryATanrij5XBjVIotDXbLO3COaSp4=,iv:g6M2HhlD1HVPzW7FItkYPgRARBsnomBAl/JH2DfuqT8=,tag:5vuzam+EkbtEdzPACG/oMA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:YXi0ins=,iv:dYFe0KQ7RKZb1aHyGduL0mteYZjZVfemUv4q0/fD8OE=,tag:aasrNMYQr41MXlWq4VTtAg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:VCT1Qop5NGoSbBI=,iv:zU05BdvptVn1ruwOtsS520Y/qhcti5PJX6HVhVbLcy8=,tag:Kj8yytXwXPVaREXIZO1j+g==,type:str]
    prism_element_user: ENC[AES256_GCM,data:jvZt3xA=,iv:3vgDnqM7S6NS0kMJxbE0966lY3tGkm6Gymwuh6JhbrI=,tag:tvu9jUCU+tJ2wJK5R6mL9g==,type:str]
    prism_element_password: ENC[AES256_GCM,data:z5B9jKWT5jokVfs=,iv:PCjgaoyxIWtZs3lFlH0j/6fXGX6UVRq3W3vSxW/Mr9o=,tag:Sa1+tvRul3AMQidd1qVCIg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:F8Sx6irL/vEH+8YEAkQoWp7xtP5ORofEcXWD24jQlZ8=,iv:1qrErwQVn3Zo6p7fq6ITk1fVYJjeekEPetIG6ZLny2g=,tag:ibe1txfAqk2JtSnbT8napQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:DCzRPSP/agGKjMH2RtKHePYGHQi7arOCzFry3k8kK70=,iv:U9Ybvrh8/liJLc7EY+LhkyWWIonS0lD8UNQU5WVNMLs=,tag:u396ZvwQKLxX5nyBmU5thg==,type:str]
    github_repo_url: ENC[AES256_GCM,data:4PBlXMSGVCkUNwhBLzvwAbb+usxBURWauptse/8M9d5KCs2EMoEo31CRdyTDo86ty3an1g==,iv:YJHHBucHBBTnO32+aKzjXecEBqRIoOa4S3JeBj10Xto=,tag:MLQp5C25jMeAOwxin6NBaQ==,type:str]
    github_user: ENC[AES256_GCM,data:y4Apb6hlFrj76bn1R4c=,iv:ENefEDSqXmP+q9fQQhKlG+IXAtUNQ0lJ/v0P437FKx4=,tag:3hYvfqkApWVkMbGrcNdmDQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:8G0AUYua5vvPBoYbw4pVjAnV0TtHRmnQWy6vH+2Luz0i248+zl37rw==,iv:+QvXVTrFrf9veiaSukm9qmskakuGF/LCRbTMES3+Tn4=,tag:mYDF2yCBRhgQU4+pUnqUIQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:v1/DUs7f,iv:Gk77PnNq0JRpwuY4Lz1I8a4UG4sLx33Xo6UkFVo24vs=,tag:hjOjXfTtYWkTCV2sFd07sw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:O9/Qubm0iFs=,iv:P9TXfeG36obHlgcT40UambovmSPMazq7M+r8mz4Ch1g=,tag:ivM4s37UTaN4+bUuHooasA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:ceBB0/FhIi4=,iv:DbZjjoTrTPrdE9AEuo9JTFARr9U7W92uvzEmNx/42iI=,tag:keppWUsKyFl1f6yLU4sOWg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:IakIfRk50WDcWc0Lr2YREODrCU3QBW9NkW6RNnNyeVaq3C/t,iv:h0tsHcxdZtORA3chIGGKEty+JRgbPnZ3WFNMB+egPkE=,tag:RBlqdzTshpX2IQu8gbFEbA==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:LAM/0gAk8qgeeslRhLeIuncgxXg=,iv:dhlo8yukWMIsTi6VMeh+qc+L86WHaCpA0RP2cCQJBDA=,tag:HLswQAcFEUmKnWHSwHSXYA==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:Bzo3iNaaIBsmifLE5mir4Q9lei9Avf/U4jvtPLSX42cifJoO+KCQ5A==,iv:tFT1jyaThhZYS2+PipDCfMEkYp6DXY+B0NH1FQRZk48=,tag:sNBhysqtDpPWHrqsgMm5IQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M1RLSEZtR3poMDg3Uk5v
            NmZHUGJOdmU1Z2ZQMmlpOVl1VHE1K3l1Z0FBCjZhbHh4QzcyamlrU2lVWktENXBZ
            bHlsYmMyUnZUK2pUR0VjQWh0NC9TM28KLS0tIGgzWHJOaCtVMk9lV29BY3hFMmV4
            dHNuNVh5SnIzb3oxN2M4TWtZQmZONVkK0gBfHIGCePBGc/jbVtxfwhX405NoltjN
            3rF55E+WutJEy1gklnc92oVo+3X6ODs8RTuUQkqqQJeoG8VJ5j7pNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T18:12:05Z"
    mac: ENC[AES256_GCM,data:d/IOqGdge1QcjYNvacsumOzDGRWjs0KBx6qy+8rihTcwP1tEeYubzIB8ZZckfRY2EKTAU0pCLJRJ9HCRu/OfO93SgxgoRTb8XjSS6OnjVKcspl0MKvmOGDarLgZJZlZwOOrMudAin4hFaTZHIISL0VkLANPqd8Aykwu9fb0qhLs=,iv:ST5ZrkK1OEnE0WPa6MM6lbp4LAioNR/TUTKS5uWnogc=,tag:+7ZGghOPzJksPkqQihhgJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
