apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: milvus
  namespace: flux-system
spec:
  components:
  - ../enable-loadbalancer
  - ../enable-monitoring
  - ../enable-ingress
  - ../enable-nutanix-objects
