apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: milvus
  namespace: flux-system
spec:
  components:
  - ../enable-image-pull-secret
  - ../enable-monitoring
  - ../enable-ingress
  - ../enable-nutanix-objects
  ## enable cluster mode for nonprod
  ##- ../enable-standalone-mode
  ## enable cluster mode for prod
  #- ../enable-cluster-mode
