apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 4h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=kafka}
  chart:
    spec:
      chart: kafka
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: ${kafka_version}
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
  values:
    extraConfig:
      producer.max.request.size: 104857600
    broker:
      extraConfig:
        num.partitions: 1
        auto.create.topics.enable: true
        max.message.bytes: 104857600

