apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuberay-cluster
  namespace: flux-system
spec:
  values:
    head:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        # Setting "num-cpus: 0" to avoid any Ray actors or tasks being scheduled on the Ray head Pod.
        num-cpus: "0"
        # redis-password should match "requirepass" in redis.conf in the ConfigMap above.
        # Ray 2.3.0 changes the default redis password from "5241590000000000" to "".
        redis-password: $REDIS_PASSWORD
      containerEnv:
      # Ray will read the RAY_REDIS_ADDRESS environment variable to establish
      # a connection with the Redis server. In this instance, we use the "redis"
      # Kubernetes ClusterIP service name, also created by this YAML, as the
      # connection point to the Redis server.
      - name: RAY_REDIS_ADDRESS
        value: redis-redis-headless.redis.svc.cluster.local.:6379
      # This environment variable is used in the `rayStartParams` above.
      envFrom:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-password-secret
            key: password
      ports:
      - containerPort: 6379
        name: redis
