kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:QRmDrB0PaWsit7+qiCBeVrcD698b,iv:sshdN2EmMQAWGAv/6/yX7+73SnWhYajA17syiDriTGw=,tag:FHOFjMgv906ajFeGh7Wuhw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:zMFwAAM=,iv:PNgTT9UkSusTT3VZLkF9ssWQv2OLEjMSRHJf3xg2amA=,tag:v3X6ucMGvL7Nz0x2sqr4dw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:QxtYV0tUifu/H2Q=,iv:YLF1+dtZTkVymAKqRQm45vN9YpCi2LK1gKurStWpvAw=,tag:0i7t0wWiDwd4DnZdUGgcFg==,type:str]
    prism_element_user: ENC[AES256_GCM,data:Lo8iNlY=,iv:sXNfVwpNcH9ZibBi4/3XKZfg3AzfBWeitRwDqvV5zrk=,tag:Bgt2jc9vcqzeDhfgmUUHxQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:YY6PklAIjvpANzs=,iv:Qy5jK20adtlqN7GdNY7gJtRhGa9/lAYyR353LJ0L3Bs=,tag:BanNgQlBi0b6T6sJ9rwIAg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:kGR/auRhLJwesS8S85SthZDoJ14KsjGKclsEW/cF0q8=,iv:VvnYvGjfwgOk501B59OP/jYt+sybND5FOZbwCstUfF8=,tag:hz0BP2Zmd8Eq0DHzqyaCZw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:oJfiePJeACb7bIUTb9pRpcI/TerMGNQ4T10lTjXBu+A=,iv:eoGA9JA3IJR8kwDIg+D3C+fFVpFjKY2frmJdq0oifk0=,tag:c5uc7oU6oexrfTEwHUSJfA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:cYuW38LZMm4dUyUMzIYh80U6L3Zxcn8/xh1vftCPSgmrrpwickvlo0RBQCgf41AsM6gPGg==,iv:bYIep7Iu0/UM3GkaamE1CGN4RUegIHG3OcKibfPIvbc=,tag:DTGqY5JDAJTJhjfvDJ2ySg==,type:str]
    github_user: ENC[AES256_GCM,data:9g1S9M+hozosuDQrgM0=,iv:41b5+UE8JcbwrM1pxRmb6Xhhtusfa1Re9jvkmo+SjU8=,tag:ifqrR5W6s6etJpTdTn3M/Q==,type:str]
    github_api_token: ENC[AES256_GCM,data:W6jBVlJFKX56NRTMGnN5NN18hko8+Da39Ru5FYuut3v3CpRBvODmsQ==,iv:Nd6xt4UA3NS2s91FtpYIz5ElrqXOLLHWWXdI5lRog3s=,tag:qgGBuMmFPIzgPHnC6hrluQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:X/49nTzy,iv:hXlDhtOcSXk7WeoH942rNMQZOE//lx9St8CUZ1sRvAo=,tag:NChs8hOjbTAPpL8QzuRbfQ==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:Ne+Wj/i+JU8=,iv:SPj/pzfhmYoT21sqOt8U8t00Xsh7QEPeWLZ6OkXgxPs=,tag:UnYhae9xKHkJAbM4Sz15EA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:/efJd9AKagQ=,iv:dnkc33fM5ZfY9GCT/NH7kMJGxXuNOmk/NvJLcQOJxlg=,tag:0zCQqD1lOYg/m6NvI/0hgw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:qqmDiEGfySDXZNVcl/QCcJ0K6YE4SRdL9Gblnpea1jo1UgpX,iv:BPqSA2Fh+ChTf9uS6ODkM5hOovRNocrpN2znEoCz/oQ=,tag:OaiH54kV6Wi6LZhu0i80sQ==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:UpK8azYo3HtP8f7IZrsxqEZ3NkA=,iv:zkV44zWBMK4I88lsilqu2NHvIWZa3+LaGU1f1FngCzA=,tag:MYcFl/LGgCwpvcxkU0OM8A==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:vuvgEgN+YHJZQC8YAgStDS5mrprobyeKKT3cs+OEDqcO9obPysiyxw==,iv:y1A71KEKvvEVtQ08+ZlysDdRUb/9SEz6afjRzyF0bbU=,tag:yURDMLnh15dEctWIrugRsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z2FMMUltS0pSc3llZyt0
            UjRvR2hjcDhTTmM1bFNjRWJNQWt0eU1wbFN3CnFhdFduNDVLajF4WC93aFQvd1lv
            WG5pVDdsNjRoVXRPQXNCQ0llVnVDSTQKLS0tIExrQ25GRlY3Qkllenh6S3ZYTXZ0
            QnVLRFpNM0lYNlg1dExWaEJsWDZqK2MKLyGmwTstFa7SXWvllDiHCQ8yaXU6J1qQ
            mouS58Rf/OwjDoIqwnBolaytz1ZIfQ8RgMAHWXv0cCUfxeYpbDy5bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T23:33:39Z"
    mac: ENC[AES256_GCM,data:V9Gp62jbFJOfuI6aI46YAn6FnbMJudHO1H0tD3jhUQAugdPYCJxISqSvUwPPsp6KRTkalGJLootJBnoMXAXZ7W509jrp6ByBrCeN8DXjziHhF6ylGZS04kWNnBGPo9VrFg7VxNjAoxc/nzlMigNpvBXxirwN8ivFxzbaYStKWHE=,iv:Ib3n3mUl4SPrq7Ywf0V33KQ5Xj28Xl8oSrG2yBidgpM=,tag:/VbLxIAenCreOyNaPBUzsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
