kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:EDttHfkE7lScoAQQynYEi7s5zMDE,iv:zZiPZHGHsYJ8fRjDvOCatf1pwNY7MsI0fPXOQ7fUujY=,tag:JFzRgjJNTt/ozBpO5hBd+A==,type:str]
    prism_central_user: ENC[AES256_GCM,data:pvJb8oo=,iv:O8SV+Mk2sn46eEa9frfIEMU5kmoeKbAS3RQOJYnAHCY=,tag:Eup7XXFaPyWeVmScB7HGCg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:vvPuKBOsZ7i+Ef0=,iv:rdhE5D6pWgnx+Xn1tEIevZAZkkCHr68q5wNffmxf1iE=,tag:jlaUSy5hbTB3fdF43n1eGA==,type:str]
    prism_element_user: ENC[AES256_GCM,data:gN2cs9A=,iv:a+3wKBZ1zEjnGVtBHDjCnAw8lBkdxN/WB89e94NqAI8=,tag:q7DIhsdYeYsL1yV540742Q==,type:str]
    prism_element_password: ENC[AES256_GCM,data:TVsbR31hZMpdoZQ=,iv:Hf/UFUkguQwpLcQqY65npyQ4ZP0P6bCMLSxADLhBbp4=,tag:6rDVw+zjAKOGnUojVWGLFA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:DiYQV3cVBkwcQ8jc4XypkMAA7Zym6GV5Q6YPO3v38T0=,iv:sCJTwO/3Y9PTPVjJfChmlSXfjiE7oLqlDVX2wZZ73Go=,tag:9T/moa//2t4g4U6W05pleQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:dMQ592BCiwXlbhfdwLbpDsVXJvQKWeJJlcF9go4CUDA=,iv:V5trpVFv80OBk9lCmR+oTmGHJydGFnQF7myc2JEdI64=,tag:r4XUwbft8Gjb6UQ9QsB0wA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:/yP2dviQvDhxqvpqzQKxwokFMi1KXTL5uumQEZP0+Qrp60+HrYSuPe/ZgxnGvIXZzUykrg==,iv:Zi14pxPqbV1007NcyWuxq6GO0R4re8fH+u+Ntuc7kb4=,tag:xAags0HAC0hvWyRnmSGEMw==,type:str]
    github_user: ENC[AES256_GCM,data:QU3BJoNNyN2qaAdS0DY=,iv:BOq0Po0Xrm0OY5DLPNDmSuZJWeLhmUgQbBm7IG+K49U=,tag:WJxHsBhC23bwbAf61VCEyQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:TNTgImTD0emhW44gTLdI3V6H4gKcamTAYiDWfcYl49geFDWgaf16cw==,iv:h50DgtrHe+oPvKCgihYuB0snIyn4rmEfTlc7T0ZAWlI=,tag:N965lpwOSUxodVYL2JQyzA==,type:str]
    github_app_id: ENC[AES256_GCM,data:3I4Xsw+4,iv:AmaSKm6Y/J630vGwUy3qFPyGxTIgERhx8d8Ymh7F8iI=,tag:VbqhuqRPSXX0y69D23SHfA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:vDngCbt688o=,iv:PbbWx5TU46+iUEpjX98fABCt2rP2Oexfn8A++cvY38k=,tag:aMhhcQF5vKU5NNTxwlxG2Q==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:j20DICpe/Yo=,iv:8E2A5udYJxs8pIMvP3GhY0a6RkNH2jEp39lTNTXj0+E=,tag:apMOHKTK/ZM8bgO/fYnTig==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:9YFX6JtCm047+0wWBDxLiSpSqRQeAZHAAfCeM2C9cStYXuy2,iv:3NTC+5ZuLFYwzu9ecJnB+RSCCPdMfgFHYE0mvcS+jDg=,tag:4oaJsRzCmTsF3vzrf+gI0w==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:JtfS6JtPHekLOdl0KPfS9KXkohE=,iv:jRzRLdVV1LmxJlC1hFE0RkjLGhXrGGaxC9/Ka+flrnE=,tag:KBta69Fc6/9pk7vh9X2wOA==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:yiTyUbMu10lwxB387JrA8sBHslI3XCJBYeMzYXaYJHmcQUBx5jgrUQ==,iv:ZIJtGWFnilisYwn4Qv7zhWslZLsZqHFrbuyx8LOpJws=,tag:swMVbJhj9WyR0nLT07vXjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDODk3aENNWi9sUGd4QU9L
            aXVmL2l6ZHNWd3RML2JMN0U0TStLWkllUHljCnJiTnhpVWdQZ0JPTC81QTJhNnFB
            WnFyeGkwV1NKRXVWdmh6V2tNUGZhREkKLS0tIHBnZ25rUXJSaVdYSnNTenVhTURP
            QWFTOUFHSUF0V2NQOUhubVptNjJZdVEKMK00WdDk/tp9yLchvAi6QFKd5kON2CY7
            iGIoe6pY6Weh0g+f/qUgjqd7M5milOvLLEUmSpwUuRVo0qd6CsS0Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T18:11:19Z"
    mac: ENC[AES256_GCM,data:0sXWPJI43rKAQTXjryva3fXSPW3v9nbzeFQckG++e4BBSTlWHkJjhJry9rTQBx9H/KwrQMOgV8zmSFCal1zNMXWsKE7A7hr3M63TiD8ieKlbJzj4OId4TsJ6fm3o3wod8lPFEtoM0eW6j4u06ok12bE+nX9Ksf7mrFReZwYR2Tg=,iv:+pFFBFZKb+iADjiL8Gxdszl5kBkz7DWgAE0MZJu3I2M=,tag:jxRkhOqJih3Ly5PVIZ1d1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
