apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  components:
  - ../enable-ingress
  #- ../_overrides
  #- ../enable-shared-volume
