apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptrace
  namespace: flux-system
spec:
  components:
  - ../enable-image-pull-secret
  #- ../enable-loadbalancer
  - ../enable-ingress
