kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:mRx6EXtElWMJcDAj6D8qVSFK3FGXGOFqTW4utgp/2iJ9Wx7U4eklQqp82iH9SCnlJdFaXPH3gxpo,iv:RCfhgrn/F+9VqCe09+k+aFt1lt54KEa0RT4bgN3rgF0=,tag:cJBpjmFZhtZSnqfpWh4LBQ==,type:str]
    github_user: ENC[AES256_GCM,data:XxZIcXVAljqmXFhjbn8=,iv:6SsgjfQX1nwOzT7ZWkXgN5cIazwA02j0hzSUVQyK7Tc=,tag:tLWBDxe94vo3QSYz1C/d3w==,type:str]
    github_api_token: ENC[AES256_GCM,data:Usi5PqncjH0uVsZUmOkT1WpEIjyu7PCM1gxlz/F+YwYOCWmqu2/ohw==,iv:ePTLbwC8Lhv3xtZFCpwZp0qDVeaAm9ScFkaGUTMjiqA=,tag:81ZQpGRgSo4M7jq9t+9ufw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:bj8khMFjkto+SFQE,iv:D0mUKEGgXjfs1ibLNG9zcWOAkPagOM4SFx9jERJtzPU=,tag:x8olob1YX4s8eK2wJU/T0g==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:on1FdFwgPZBNhHKNM6t2,iv:Z7dvs+tZspHZC92pAYCin11sAs8AgB12EDM8RyYp2LM=,tag:Cv9Of4mKq6javjoO+0BgBg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:K9aI3wK4uwm34uQqHzWTBa0QrxxIOGdZVRUJg2ux8QY=,iv:cGdOcCdZnF3AWiAvxJk+4CNv6DuRpN76r9MxBKHmi5Q=,tag:6yzXbUH8YwCHFmFg4sjQqQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:8tjAAM0=,iv:W7poYnwxZwY8/x/kesHigU3uF1L3wLH24vTOVlnQh4Y=,tag:mz5vBd56ClAgySm7OWaAUA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:9AnHbwTFWXYeNY0=,iv:AL7VpI9uqRvudE13AFKhPCbXiEtk7FeUbKPsl1VQ8lk=,tag:9ajusRP/MGQp/sBtSiJSuQ==,type:str]
    objects_host: ENC[AES256_GCM,data:WrdElnsuYpJ07OQDFy0mYoVCjhRE3wpQwyd5pCOsRIcJ92Wbjg==,iv:yDbge5fBpuXPffiNZ1Q6n6fajTzIiBHMsI0IxvzSaJs=,tag:9RXLllj8NyUSxT4xQwSk3w==,type:str]
    objects_port: ENC[AES256_GCM,data:O2g=,iv:GudTotNKX1mMsYnRKG2QRxaI8TKwHScH3E63LO+lnQw=,tag:mFcSw6f8A3NopsSWrCCqyA==,type:str]
    objects_region: ENC[AES256_GCM,data:neYK2Wicitgw,iv:p4kJY8yZInCfcTRkRs/s+KT7F8qSqEljIEuSHjaS6G0=,tag:XRiX+2LK0WufRHDLhKnk7A==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:7pjlY8k=,iv:q1pjbN53dbBS6MwxC4RoHHwIRcjv053oYjAkprH5mdk=,tag:MSkb3wFjysV3Q3/chsmvWA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:mhIS1osORHkbsaS91LFDfbkx9AZKBJsMsSBr2+UsKJQ=,iv:G8k6QA29Exqqu9E2ORVxhqz5bY7htFsO35v6Lg2mC6M=,tag:IydMlJhYigBw3qIqHlRyZQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:zQAHCwmJexMTWv1Dr0733rhwmW9IHxKtygy1qJFEStc=,iv:wgZn+HyZ/7v491b1oGWghbLnxJGFeDpGHkqx3RK26aQ=,tag:LTop5Wl7JgcRZ9sqaZ5ciQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:cHgONZpT1h0Y0q7OVCuNL4+CNNJwo/c=,iv:1pKACtIyXPTMUb2AGfWTA4lj44xdpmwlYSxDGb7iqDY=,tag:0Oe0BeWtEUlQZKA0Md/ISA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:s1CeZhF4CWi64EV71UE=,iv:IdSocs1z7KNBq4FCuPLwLoffs4ZxbfcGxnpEGLkNiWc=,tag:QYc3CB9QzDt7WznzYGByDw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:+YN5GKSLOqKNFbIU6DJTO0ctYi3c1xV3C+V/IBccF/u1buJo2hjigg==,iv:67KOFi6+kLrVn/8AuLLM+ZSbcZ4jCEa/ob4KjW+LgAY=,tag:TyRs7K+22CNCWGlKs7hqzA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:BYKe4BDtANXGavV9vSF2qKNmF+hTUXiolj3JAn9SsHPkPf3JhYwK4w==,iv:WhVLJyMEGC4zl586GG9dOdN67UKaZTISocRoGXF8BuM=,tag:Zt7Yq7BuXgUt9/iLVTLAMQ==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:VteXtRP0nQ/yqt6hfbDsbb8iGBjCSYFpuBM=,iv:RSxSnzhtGiBeedVVCmgdepVQEmFJtq5rrirN/6hlq0E=,tag:MZQX0q3H95aqsG6eXdB0Wg==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:1zP8OGrCDMRt4UIK1cSCdyzFSzoHbA==,iv:DbsGyTEGUatqiBoShiW6ryM2HYNjWEYa9VYlrf0uan4=,tag:EZ/yvQIDQopbjoHyiawlvQ==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:tCBj2j2ZP9l5,iv:uIrsHJHwjAUqINebEUtbqEmhe+KdcLwumNDAi+FrVpU=,tag:I/uQdKZblAZfUsepMM505Q==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:zcGEFbE4kXydciK/SvljL1DfNjyD,iv:8QtCOH1CrJbXdWCEXknlpl3eDSMrN+0MWBosuScoO90=,tag:vYorpIshkcp/TOCGwM9mrg==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:7byXFE/PJxBak/mymHVcDe7WV+I=,iv:xfkja8NHtQo6DaIckf+zBaqBzkLQzj618FULleaG5ec=,tag:pH324bc3f/slKJBFynh+Sw==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:4QYod0jLf5HXJLtFT/VFi/63jL0cMpTvEvS6TIoWQ5JhNiJDQMMHog==,iv:lhswWb8mkDDfERxzfbTfrL1lNZ6PJhqjNkAvy4BRH3Q=,tag:GGowav9XUf+AipAvdRNFTg==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:6A6j34yTNXT0ZfmrcjV+7CBC4F5aDL/0euSeImeCZzFS6/56OZJFCsvSH+KmwO5xOK+kpOhmXyOGCX6W,iv:FXVaHI3W/WX1HPr8neVscDslOCWbo+x6vDc89mU0lqo=,tag:VhwF4MHe01zyQTUikdk88w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q1lFVkp4MnZPL3MyZ29G
            eG9nQXBZdkt1UVltQVpFVFNHaUg0Z2V2MDJzCnhuMEt5Q0JrVElvbEhML0FMRXZi
            SXJ3NVhsUFVOUDR5TlFkZjJvOFBsRzQKLS0tIFFBSjFWNENtcVdRcm9sd3lNUjky
            NDZMR3cwQ3psM2wxQjFVQXVoY3VVQWMKptwmAmRVEGN3EU31ysgE6w0pB9wRQUw+
            bgF3TtLXnbcnhxNsCCPNjWl9XQ+x7148+WMAF1PiAIaILJMUIZd4mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-24T20:41:13Z"
    mac: ENC[AES256_GCM,data:dGQFb/UoKiKuqEL3Nakx21cOAcBD09Y3fFqZ0BwLnw8PZI2TjLNK59oXvcO2iXMlVlau7Vecuwa/V8tdCm0XnCGNbYouNof6PUhIjzt6hzgURtMfHEQjugsWhsAG6SDNSooWS+ZcUt1Y3CIoxggVl1fF/E4rKxvXC4yPLgEv2PE=,iv:IW8GbM42aM2dQsvgPh2+9wVoPsQiqjDbRwlLCUo4KZ0=,tag:ljq7d+bm/MUnj6ZikJak1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
