kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:jtfW3pF5zXA5/4VKbiazhFilZSpPHKLk+LZF8xemHStiVxIblEDyIPRmqSQphzJ3OepmZM1WyHAS,iv:fLUKPgqTvmaGjUQNpsSBFSfzCCIscpcqntZ/rphyKyI=,tag:pEY4MrlvMt7DSWFnZf5yXQ==,type:str]
    github_user: ENC[AES256_GCM,data:APQMl1yXIPYY94e7Muo=,iv:p/jxX9eah3dwc3EDxaK8rajt+ybB4yu4Uwj2/snj1MM=,tag:SN62efNOfeFBOrbu6hopEw==,type:str]
    github_api_token: ENC[AES256_GCM,data:dq6ek6BH9lo+5bmZCE7sj4yQfi2Quopy1UXYBX6iqnIU21st9o/9dA==,iv:+Zvj4RrGfAOHsJ9xRh/GB0AuZOtQlZ/2tXHbVxIXbvA=,tag:8J10j1yeVV0ADTL52KNgzg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:Px/Gyx/rnkBCO1Gg,iv:CLEzKDw4JOkLOOkD6O3XHOTXrCxQ21iIVrCZMx0lzxU=,tag:L1tG4AvR5HVASYSyGCMlaw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:lGenFb6DhcX+yaeDCiyC,iv:6eapmXsJo4nmjjK9hXm/5MjUytQ7ClpEmLB2AM8Z+yk=,tag:JHvdqKhNhFet308w2j2RmA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:EqrrwqTuXoZm2CSRguYgAJocIjrq6LH7+y+TVJUeUVo=,iv:7TSRfDfRXDhnedDG20EEcnA/4N8oaZTxnaUL+OvCfxk=,tag:MvUr6P7G8BGWSZdeU3WzYA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:J+QNrBA=,iv:OpYHRrF/iMSivl9ky9S748+ksk/LJNUmvufy8d2e7bw=,tag:7oMDP9gaW7cBARLZkrAq6Q==,type:str]
    prism_central_password: ENC[AES256_GCM,data:PlSOmGCU6WvQaJU=,iv:ZQOuDX5IYw5PMiJxa8sx/h/vG0JWtCUYfomU+Q3ymlA=,tag:oPopCEAvFbvrU6hLISAbdg==,type:str]
    objects_host: ENC[AES256_GCM,data:Pq9ZmiaFerjWNstCturEgJGuxDzX5fI5Ktjm7Bpm2zQRTneXDA==,iv:pQgf9S3na2GApoUPOqPVFKNqc5q03IQPCCX5s/TTJr8=,tag:vQ6k+923vpCWBuq94VwlOA==,type:str]
    objects_port: ENC[AES256_GCM,data:tHM=,iv:SrfCeAFKR1ranSF/n9hRDkogqv9Rw3dk4LytPyS1kA0=,tag:k2Q3GKmx7QtcbxxnbyrK7w==,type:str]
    objects_region: ENC[AES256_GCM,data:e7tVpfkZUi7T,iv:kBI9ilpdqS5bt25HqlYgtxDhey1qvef3H7mwbCEwt/w=,tag:nLfy8lOJukbpfAAYGRQz0w==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:/LAyAtc=,iv:Q1OSAzr4kvhyljgNVpkFpQfkEDGjzAPXlitzcrGNO7c=,tag:dfBhVcg1kPU91rQk+7/lJg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:eD3ZyYI6vPo91vcFKjuOPAiRBJTJqZZ/oftemD0Wj00=,iv:4lMMuqAkKESv/g8K3PxDD2QDaRKlCR9vcXk/pLBoWhQ=,tag:cdojDZDgSwpfLmIyIPM5rg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:4Qcdv5v+rZt1PEWvNc5JFWMu3QaYNFeJwD1YROd9jJM=,iv:rT2ohm5GsPSFiUpBiYkLSBlM8RUD0l5JsmajLKFJdjY=,tag:8R0LKbJfFO4z58lkf+5EHA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:9kjkPhLNMgoaHf292IgKWq8EgwPP/XU=,iv:nv/7Q8sKk8A6cpOz1mFymFigym1S2k0G5kT+mXy4fPw=,tag:4uo6bUs3S/HphuQURBDH/A==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:Lp++MtCHMtIczcLdIpA=,iv:+gHHxLKUbOY0Jr02qL4vGAY+ZNqc6Jr9Fs3rkdhV7i0=,tag:VH/QLuum88FE3wf8iBpBIw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:S+2qVtLWrXKBRkK62LOr5zPVYiuFWj5RhjuZoHpf7mDDP1C6Y9j+5w==,iv:3f/iFHZZ8xx+5townTh1k30zMcnn/oqGRv/PRnxJek0=,tag:c6nRz1PvkSBH3sRc1VKkYA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:PXROYzr8kotcKcUzF2knMbhgdyPltOIUTLr7nvuYSfGRrigCi17cxw==,iv:Onfz2jXhQgTBcVB9kxDWQTENow5TTMcvJBSH0dSwBpw=,tag:layNvyEs9cuEaEpfXCODxQ==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:IyiiBe5lEagtcMAW1EpZPNaF6McHDrAYjHo=,iv:HYYIQP5HZBIgGXNbbXPFZ/j3XlUMEO/7dVfIp4ladoY=,tag:P/m0breoM/ANd5aPZVLVWw==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:jZ8pFc5sQ7rHMztLtFtDyK57LtOidg==,iv:NryuRPU0Jc29hBUStAsbJu2GsFXAVdCFOVcQNQF0Ibs=,tag:3C0BE0aB+ay2vloqg/MKSw==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:RDG8EdFRvYp4,iv:ZnwC64Ayhp2eRFo4arCJSwmu+LEFVMT52Hc9EICzGOM=,tag:ZGp5E5ZzcpJICneghUV/cQ==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:WibQ5bt7wIrm19ngAizTrGvwKzU3,iv:QtNTH9oZX8qqoa7K5R4GiPSOxnMR2PTgmnvtFtkETR4=,tag:+vMsqKOKqS9bhMjeQb2R4g==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:PYxyWtp/l9xHQTCQbwyU21tb8N8=,iv:9rxuNbJDKC/j+vunsMKEphS9CXYj10mkb4mGHOlX8UU=,tag:RsikOXgfOQb9crcUV0TneQ==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:vIW+J4w2i+z7mFnuJQD+Scg+GeM2WyDWaWsayHsPKta1nTbiEZGHIQ==,iv:YVh0XDF5jG6R/6xkvKIH+R2Yc1tMau/i6FRQ7LZ08aw=,tag:A/d8L51EUavT5Djo0aeNMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeGZCdjd4TTQwdjFjd2RR
            ZE1Vek9jOWI4MUltZjF1bU1VVjYwRzhTdGxRCkF5VnR2L0JsU3RWNTJSc3pHRzdo
            TTZlZ281YnhLMFp4OFo1dTNtOGhxQ0UKLS0tIGZBaVhnOWZJTXI2eVFwbW5qdkdU
            czMzQmg2SEx5NnNCNW9WNmkvYUdyb2cK9J6FrutUNPIdqk8Sdsl4N5K1K1313Xnz
            pnud8G8HIEVxMgefyD38Lhq5sqKIcsUf4+JrqLLURwevm4yEGhA18A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-18T16:22:08Z"
    mac: ENC[AES256_GCM,data:ab38vDcQvSCXnucX/TPEdeNJprkfcRb7gmM2AtJXew7YeUy4K7Yp1+hA0Pj7LPJsK/g0MjnW+zuQ4wEi9BtWrpQjZ2GFeT2eojpWqvivbCbp1ggtjQbcan0hKObNC/k6RVRKHEOl2+mZjKTjuSe4ZKb/ZLJLiPo5x4dpoNJqrtc=,iv:5AU77mIXl77o2Tcjod0mn8YnulzYznB8iWcicccP0Iw=,tag:w8tSuUTD69qMcD8PjBjVew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
