kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:iUycQ76rKQASjOPL3Y262pMMZJA20fjhKVthxZPUIIM=,iv:xH4x+SlybaYcTnzczDrnqZ/6NxPZXZwMmlE5j06ogI0=,tag:m9+3PDGOHwVSFdwaWDDrPw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:4xSM8Sg=,iv:icFSmFQjAOEVTb3/XAV4+rXJW25CPR21TVPuPq6ro4o=,tag:HbLYhPkOPgslXLcWnyqWbw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:K+Sr6t88smqwcCs=,iv:OFatkimjDSbeNOrP1yzBf5MnfFCXc0IoQZV0UJOqVVQ=,tag:keGFYCa2fNXrvqH59lOLag==,type:str]
    prism_element_user: ENC[AES256_GCM,data:tFGGbqY=,iv:32Fau8d4HJBGVETklq07TUYfxWseQCUJ0UqbjmEwAt0=,tag:DMD8U2mWfldnMk08qXJd7A==,type:str]
    prism_element_password: ENC[AES256_GCM,data:YBzQwqp+8jR+Zio=,iv:VYaXnHCLqdBWeBhRTVJRLDooMmbel0z8oPa8iz2+/24=,tag:HomWzaIVZRQyzUJ755YaYQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:PopioRtBYNebkB3lnWZpPCk0k1aTL70SdfY9ifgcrwo=,iv:fi82CaC3j/e6s9lAZQyGLR9PO0CtJt6CJVOuUmh6fcY=,tag:BL8UOFmUHPb1oKWR0SfFTQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:ZezQVL/4Og1IJJjgD7N5qTnjDuvyYWgu0R0Is+lXRxs=,iv:QRubxL+LDNqVR3cTwX8wf85+WK0/+xNw9JdF9QdNq+8=,tag:CUbKckRBaFS7Hc4BS++2Pg==,type:str]
    github_repo_url: ENC[AES256_GCM,data:5TahiBn65h0nbBkKKqF9Xu/JFnT/2a8N6dlu7cOEWiTBsXp8ZO6SUPDMOohiy3raH4N/zA==,iv:kD87jeDEESXk32scu6+YAmeRIIKJjWN8deA42WL3I6E=,tag:I8VadB6NC6OhF2jxzh04CA==,type:str]
    github_user: ENC[AES256_GCM,data:7KPbGGshZnY9JPSd0r0=,iv:CUYHh6TFK3SSavSjuSPcoIiDPxGs6H7ui/3SfgTk6wM=,tag:T1gYv0kA93m2Fr6frnXfeQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:fSol8FcD0l6U/21xbHZnpAypLdGkSRGoDXB7DxaRkiWTrQAH8/FGIA==,iv:Ut7HKWjFfnFStWRqd8TOQbtBVSt0PQAMQDsvQCXwbZY=,tag:qO9zs01JeuEyY2pmhGTC/g==,type:str]
    github_app_id: ENC[AES256_GCM,data:UduzM9x2,iv:ZkiY1lY+68RYCIN2wLwh2dRSOd+FYtdG3fjJZCkRBWA=,tag:hmyUg2Rh87upK7XvmTpWJg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:uHMuoUcr39M=,iv:RhR5V3Ku67s8U/m3ahuYRkTWK7c2id9Sr+gFvAxhzB0=,tag:I6jZVXJp6rWXmKKHR5tL/g==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:fHqCZ2PVFvw=,iv:N3mIN2eX8GkOMDbjR8Ii97lvll7fWDQNuOhIdtVMads=,tag:f1G97FZLZg3sABOe0Td/Jg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:jREjn70Ji3LKqpaBxQ6rJ8r+YjkzoPdLIGC7IPniXlF75cYm,iv:oPVnySq5Vf6bXkwlLKE3wj/Bp5VPdNZH5Y9/pyBaPG4=,tag:audTIkblKRDWndDTIM2KzA==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:KiqHAdZRjvBWwD29UtzRGvQe1t8=,iv:sfSY+SyLGZ6AONzmlyptAGHLwTYgtOSn0ZQ7Zrg8h0s=,tag:JZrqmLzjbTBHa/H5GMe/lA==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:pLkZYNkkIcmVs+lbeXKKKJ7TrerGLPTI8xevWedPRuTijgBgmcIgsg==,iv:mrpvmLgG9yzfmlH6S3ZvlAUfYyDIoN6OvETuFSscKik=,tag:BMkYm33Q1j7vA2CbGVEYgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM1pLTmxPOWxmYVFTWUNG
            Y1RabnY3UE9OUmEyY3lkMCtFcjQzQlZDU0E0CjhPVDlnZGFDalVVbFFxWHZyYURL
            V2JoakFUanJtcG9jSlowS01peDhGU00KLS0tIGN4Q01kRUN3V2dpNVMvZExNUEZ4
            bUQ4blYwUnlKQnBsYTYrRzJXSllzUDgKpcg8AMgv+SLN/4b1KRabGDLT145F43PQ
            nXfKkggyKrecnjptNfe/cKgOz+4uUgP85prYG47UbrbUFSNtbuEEhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T15:25:53Z"
    mac: ENC[AES256_GCM,data:c54xDSugOJgBLXoIjr9szipo2ZXzXwSRt8AMsA2kFsTYJTmp8I8Vi4kWqZjcMBrPnUjmrqffUNY94QtDVQ4F3b89W/+JtMzvZu6pwbdnxUHPY4897m86yeLUxElh6Hq09HvILXmeMtWhg/MCn1J2V/W6KXePgXwKf81FLjDJAXY=,iv:zxmB8ATmwC1lml+zGjEWV2pGkXI9lhETwoS1VTgkAPs=,tag:2XEO3FlxrX9Oo5myMBG3oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
