kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "nke-nvd-llm-wkl-02"
  environment: "non-prod"
  cluster_profile: "llm-workloads"
  gpu_cuda_toolkit_version: "v1.14.3-centos7"
  gpu_time_slicing_replica_count: "2"  
  kube_vip_ipam_range: "10.50.119.56-10.50.119.57"
  kube_vip_nginx_ingress_ipam: "10.50.119.54/32"
  wildcard_ingress_subdomain: "nke-nvd-llm-wkl-02.cloudnative.nvdlab.net"
  management_cluster_ingress_subdomain: "nke-nvd-llm-mgmt-02.cloudnative.nvdlab.net"
  kube_vip_istio_system_ipam: "10.50.119.55/32"
  aws_route53_dns_zone: "cloudnative.nvdlab.net"
  aws_route53_region: "us-east-1"
  objects_host: "objects.gptnvd.cloudnative.nvdlab.net"
  objects_port: "80"
  objects_region: "us-east-1"
  objects_use_ssl: "true"
  milvus_objects_bucket_name: "nke-nvd-llm-mgmt-02-milvus"
  documents_objects_bucket_name: "documents01"
  model: "llama-2-13b-chat"
  revision: "c2f3ec81aac798ae26dcc57799a994dfbf521496"
  maxTokens: "llama-2-13b-chat"
  repPenalty: "llama-2-13b-chat"
  temperature: "llama-2-13b-chat"
  topP: "llama-2-13b-chat"
  useExistingNFS: "true"
  nfs_export: "/llm-repo-k8s"
  nfs_server: "files.gptnvd.cloudnative.nvdlab.net"