apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls_cert_filename=tls.crt"
  target:
    kind: Deployment
    name: cache-server
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls_key_filename=tls.key"
  target:
    kind: Deployment
    name: cache-server
patchesStrategicMerge:
- delete-cache-deployer.yaml
resources:
- ../../ntnx
- localized-files/github.com/kubeflow/manifests/v1.8.1/common/cert-manager/cert-manager/base
