apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus
  namespace: flux-system
spec:
  values:
    extraVolumes:
    - name: jupyterhub-shared
      persistentVolumeClaim:
        claimName: jupyterhub-shared-volume
    extraVolumeMounts:
    - name: jupyterhub-shared
      mountPath: /home/jovyan/shared
