kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:xG/5WKvpBdgXLbsKN+0DRwzi+aUJR5541nqaltcwQYU=,iv:Oz1zvWTMnHUYpv9hDgSLZR+WYVBU9QaMoqLKzQklkTI=,tag:LRGYUHSZU1+eZxaOHlURHQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:pSc3p90=,iv:KNEgutieZ6zEmQnmXaX9MKg9TuqJgyBI3lD3I+8FsMw=,tag:IWh7lejrBtvJgXCYm30rdw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:9IWSglGP4kSOAU0=,iv:xDmoAcALkKrIRcBZkaVobcFrRzarBBeOZoeqPbsrpKg=,tag:pwug3sR9wJReMQ3UMuKJ+w==,type:str]
    prism_element_user: ENC[AES256_GCM,data:gKsqv2E=,iv:JIvYkiaLoe/DjkNQ08YoWzlapeV0oz5l1udtvvBoqI0=,tag:16tmkiktl6IceEcxkod8VQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:8D2bkxuo/eypy9E=,iv:FMb8yOAXw+IcD6EoaLw/1Ucs5JNsTnL2rPNiKR1m5JI=,tag:8Yxm/R8ZPZyFjSQ9aJDusg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:LmqfMm5C42r/l1TP0l6Rcvh1bEClotxIGBdwpKi7aVg=,iv:rylRPior3rBBmib97ZqHbPMsvohhZz6QKfwzghSs1tg=,tag://kpXWeIaOjRyGwMkWJ3wg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:JUs4r/cDpqaWQb/9cv+1o02nlb9MQ+1PgRkePs+Q9g0=,iv:SyEHrJaThZaUYVA1B1+gCRh5d+WDlKCopHEO2jv6T64=,tag:SDQBam+49YLPNVKI4R1nZA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:E+NViS4JJLLFOB0ffciizLWsW/PRFkau1f513CYsxswHiBvNBnvwY1gTVfvrEWJBwdSCAQ==,iv:c1T61EJDg8LLOfZmD+dyM/OSL5aZLR+H+2tPwkxEaQs=,tag:AuFHko4CX+cbkjdg2kLkbg==,type:str]
    github_user: ENC[AES256_GCM,data:JWmY06VAP3O+i6iIN9U=,iv:ZCWEu07esD72qwLRlPb22EZzHMWAYUDxzAHExWAmITM=,tag:VBTti1n7Ks5EdtKAn+wBJg==,type:str]
    github_api_token: ENC[AES256_GCM,data:evIkRFfmJ1Y203pF/zjymWWnpm/Yy7sslTZ5kTRfMyDMWKF66tbj/Q==,iv:HCQRXCRZ4LWJTPEicmRzxxSXsKeUfEcnYVFP8NtCMPY=,tag:BEaRAAECv/ni6OawfcJmyQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:G6u3WYLX,iv:8z9RN4vxYJVyJnwzMsYHUgnfZDFxVbilOXJdcK04n3Q=,tag:PK+ObAEA1igBGkB6GAwOAA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:uZMmPtSw3/Y=,iv:3b4mVCTcwKkcI+DBGerqj2MQqKYyP/vPH6Ytfx0zi98=,tag:MDEFnuD+lnM1d1iu0Jl2SA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:WO3qpCnifY4=,iv:NznXehzacPO6AI7rFVfKJmA1B1vzFAV8wuw6flNVtUA=,tag:XmFRWhm+QqT53/BuAPFITw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:0+b8lJSikMO+2Pr+3cmIuItKdHAQU6A1lKbpfiewdID13zd4,iv:+CzxnxCZQqbBP2OD8Xe0MydyfQn2APGbAU5QEkkxQ1I=,tag:uxKB+7nlPGmcigNcXVx6cw==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:pVFrd8/cbcIbzrsnCQUtSYWfhj0=,iv:Hr1clrnVeS7MndjzhJwF6rcrUUTp6+RZOQgBhiqUVQg=,tag:fNNCKKzgU3gUJc1mrg6g7g==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:7FFgpxo1tm6orfz6VWIuMRJxuDDgmZFlbV3nAWxWbvJ3zTfhpcQCOw==,iv:VBldNeVa1b0Ym+TBnxRHGa28997dSknDcdG1hKIa7xQ=,tag:aFPr++plzz1KaNuahD4mfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d0dDSzRsNXp2My9NMWVR
            MUdnUW1lTGJIRUxGU0luNlJRTWJGWE9sSHdFCnBOeGF3VDVjdHZKZE1BWlB2OGMw
            c3pFRmJDUnZUV0NJR3Z4eUZiNTNldGsKLS0tIDZhc1dja3JyajRHbFhYVXIwblFI
            RmsxZTNDZFFSelRxT3FaMHhHV3FneGcK8WYkMDvlB5/0I1CCzPNzeZHsqFqFQyUz
            hr43IYR+dtWmL6nMBcty5SES+mQGxrOCoU06tc2HTf+hiXR77mNGZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T04:12:11Z"
    mac: ENC[AES256_GCM,data:hWRFhWjoiywMAkxXJ25+VD/ZvPWjDGv3Elp8Q1QWOCzwdOQiZOWKh3WLw8DBNip+slIJXmJiYgYGcwQMMXba4zOzPlByy3FnQdDkwuW7Xw5XT9o33XvWwqlrzHUg/eoi/QiWdrmqE2h7EdM5kccwLX8X232nGB+235j3XlMwtt0=,iv:l3kCbJbYSPcgw0jmz6r8DsOeMx/DMSy7i76hP+eS0ew=,tag:AisXtDEyYiDDfj382vR9tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
