kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:a3g2851ns0HwJ2ZuJDLWQTIGUWZERp26BhFDLL0YYWU=,iv:+ikxO/kTaPpjZmIFRmgiXZuqbOpNkeluyeU93lOoJFg=,tag:Zfa4Avaul0+joQ+fxRr+sg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:Rav3+a8=,iv:GkMdP6iPqGdEOGgGwGhxPHAyBA0k3cUZxiHumgHOCME=,tag:bjkGNigMuGGUgR7hpnHrBA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:wZBIs5je8zrTzKs=,iv:ppTOSaIsY7RriKTHQFkk/fQ9gZfkYU5ac0RMGLxcPBE=,tag:+hlbkT/RoHXodhrHjxwOOw==,type:str]
    prism_element_user: ENC[AES256_GCM,data:v+EGBg4=,iv:OSB7dCF17AL5RS6afJ0AGyciwQAkfwQFrpn9YKxGkBg=,tag:RQAHb9qN66XiCbeYguMsDg==,type:str]
    prism_element_password: ENC[AES256_GCM,data:DSB/TzTtwFuc640=,iv:2xMOP+BFCNBCgkpKYpvR7gvbUIFD1JjPKyiRi/d+ezg=,tag:MS4u/Tv2qOtdpxITmISCaQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:ZFylGRsxFvj2k8WKG3+P+wdPaIejfTo1QfjlduDp96E=,iv:+N5ypOpnNPSCjG1KbabdTBxVRHBbgs8leOD+sRraGoo=,tag:Zr+nN4/sAovV5Car7E6k+g==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:yvXQ4uvkIrwCuA5Eq/U0segeIrTSwSUBEu0sGvLsSGg=,iv:zV9dswANBorzewMc7qc9d72xHifyvDMKcniu1o59WXc=,tag:lznuvMNkBD5xIfT4UUokSw==,type:str]
    github_repo_url: ENC[AES256_GCM,data:b3rTxLqu+rsLt3t0F8rI5OPx/v42U5EVtBrJgmr+QbwrUvTViMOUSahAmxDhylxNILo6Yw==,iv:3ACzCcJ26ABDxX/p/FZcRL0gyApbw1xEMB1Ci0ZWi64=,tag:fEU0gATigyMYFYpeF5wVqQ==,type:str]
    github_user: ENC[AES256_GCM,data:/yZ3GII1BhSc+en4rLo=,iv:AE3QSWDiNLhlO01NFFCH+LyzBOV9DMigMm7jE6t2EG0=,tag:DczqffBaOW7PBqUIUGoMKQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:in9torZM+JJMh7g7ppyxmbFL5JoFxZkRvnQeAe9gQ6/O8FA+1Vkr/w==,iv:szJ0uTncCPOtcMDpkIhppxGNbYT9UJVZs2TIV5CvwN0=,tag:Vpcj/u8XHhfTcRflA/pxcw==,type:str]
    github_app_id: ENC[AES256_GCM,data:JMZ92AnU,iv:o7Q0flqHCSVVWTtw4BvuoaZHEqW4hcIt+jhB51R7shE=,tag:OhEEKspEnXOhRqYgq3vbrw==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:0rBzijt/iFY=,iv:WZmIouIBZMudR07yMsJBVWWBWueXGHQ7KfivbmCErlg=,tag:Xo+rPq1M3of9gEO8TkzJMw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:ma+rY6SYJjI=,iv:4zDzYgeAo7Gqw6e4iG8YiSZ6PHPrcXuzr4QgLuoC9u0=,tag:SmnXlzwpatoJkGvoMISDCw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:4vJ0X7FKk8rIFQ6yQFtRuuFdC0+zERWKW/iRpzhTcoe0bJ4L,iv:EO7NqyoPeh9Y8nWwVWK7iITcQoqRfj3I1XVB3P2ZZSA=,tag:mjA1oHr6Pqtw/AiMAAQHBA==,type:str]
    aws_access_key_id: ENC[AES256_GCM,data:q3KX1MIZflFkPGXrkG06UWct8xc=,iv:fpwO6YCjAOWYud0snK/ErVd5M4UT+w6bmRWMvcOVtcs=,tag:Z00rIw0hgZv0x5BgMIo1pw==,type:str]
    aws_access_key_secret: ENC[AES256_GCM,data:jDR4+xH/eX67nr6z5h3DeEotvXW0qNZDNIMkte0pm8NGHdupv9yNBQ==,iv:QFqtyjjNKJfSAj6AakkCRkMnpnCq5DF4523EU9r2Iss=,tag:gPhxs62KCZb8ayRF92FlrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR21EZW1nRGZrQjRCZGUz
            ZDhqRUh1cmtyNm5CREd4R2hzQTgweSs3TVNFCnVEby9WMXBDZmtWd1RFUFZMc2ZG
            K1VONEIzbWJNdGo5UTJ5SmNPWk02WDgKLS0tIDRiS1lrekJqQlJhWFpFZHRHYzIr
            N3FhRDdpZlZaTC9pY1NkUnMxSkJZSU0KjUqUOsBfbFtn4TVxoR1jOTLbr7FeQDBx
            1Cim01TXvA4BLALNgOqjD1sDTspTJOEr7Tjfpl3vGtUzAv4Z/gtnRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T15:27:00Z"
    mac: ENC[AES256_GCM,data:ROC39L7CDf9XIoRk1q8WMNKlDWbKcnCFLZ2CcxtmIk9I4P2RPHMiX7GJpkhkmkuTHv/DorScCVxkkt2tZgpWgGG/wY29lghGm1iokwf5jyqxwAPE+QU3feN0PkeN7z2lENXYK13UnAT/NKAl0pPF5YZVWakK/eFsE92v1+93w1U=,iv:d7XU+OePE1RATq4pFHAfg6pFJiIgFh+xj2ML0RTuLIg=,tag:HGtTE2V/4lbkuck1N2mzhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
