kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:1VuCF0r+u3BUHGVdc/3hXtlMpKoj8wpAA7VVjygECC2wuTpYvOamx8PHw7eU,iv:dTaRRnTC/MbGuk34iZz5LZNT6GZlUSow7C4xIMj5XO0=,tag:rgKOmnEi+2v/A2gariGd4Q==,type:str]
    github_user: ENC[AES256_GCM,data:vRjBwz8u,iv:vYGzl3H0W2E2zUCPYGr9D1bpJVixLc65kdrh3OynkVM=,tag:ST648aQKcSiLZypGfb3QVQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:f4Pb93dt7Qe7ZtaolUjLHt72DHlh4Roi1YSZ7Nt7mv8bVSnTKRG88p/2rDfykawInaUFmdOeJGFI2tUl7lbn65d3IuhjoPx+DymfwAFUa6B7sbUfGgIw25NGYQr3,iv:JlEvpE+hD4A6Ovu0mMqL0dwviJVcDNoeZop9Nqo0pYY=,tag:ixLxD7L/z4qMQDtkOTD36w==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:yZ/Cmqg=,iv:vOTTiwWdGT/ogxT9IrHYg6ppFKndYJaNWvIc+Z5iZzU=,tag:TUbOyvSEy1cOzjL5f7X2Hw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:kZ+ggG4d4MBm0LwJfcV74gwiSk7DfoYf2GFG6pPU8ceBMcK/,iv:qffAa63a3bvlmBlWjDgdB4k+GVueDfxI2P3q5voOFF8=,tag:WlQjI/1ZmymxfW3eopMjug==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:vdq4rESj6w7X4uKdQg==,iv:KN4UD7aEgHRPHVjALSCT+OfX401HFXepmV7fhrY+z7Q=,tag:dDv7kPuplVnkeyzRk6ZipQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:IWU7PGw=,iv:pBDsO2m3xqWQrUo8MhudiSxEYKqj8JlR4Zi/yPEXLrc=,tag:r6E9TaMgv38XdhjwrX6ojg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:yMhyklD55vjMow==,iv:DL1YKpdFJzHZLr6QM0opEVn6BfF5u9mAKCYIfH6uSzg=,tag:g46TwIy6+NXkyvxRux4Djg==,type:str]
    objects_host: ENC[AES256_GCM,data:JZRQLHqu9RfxFhyUgw==,iv:KEMfezwb1k/hcr8Na7SX3Trr/QNz0LdsX4/ntgq1Dr4=,tag:VpLXnSs3oyfhzJY/0cYGmA==,type:str]
    objects_port: ENC[AES256_GCM,data:xAQ=,iv:SDeB5WqTFKlJj1LLpx43JXaeT4NB/UNbJGozFeT35Sk=,tag:FvyCHMxLWPz29RH4rUr+xw==,type:str]
    objects_region: ENC[AES256_GCM,data:kcASy4USNwIC,iv:RPssMNM91+z46WTSgdFBzHJdbw095ODbnRKbQEL1r2o=,tag:1KAeA9xMdOf0bcvFuuSeUA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:Olxdkco=,iv:Jh94A1DZcYn4GNBX4UJKH3xuna6/cFyUCx7lGuMuoIY=,tag:r2qs4WZPS/jEuU6WaJp9Iw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:lh0IrzFOXYPnZ2WW3EqlQzkGLuFBrcFh3WCYfKPtsB0=,iv:eXEPhAdjhpH8SzfuB3u8bggpnmUGhqJzzhAVerX6jxE=,tag:L6bPbrWEviZ6IG08Z/+y9A==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:K6U7jP1+q+ox8xQzS/pfgRp3mr4ShsMgfLR1ZL2z2gs=,iv:CW18dN/bJZ+3Wk6YnACoCP+PeoE260NRwdAZeD5xDNw=,tag:ddc8cvV47ifUn6UFdBn1rw==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:DjCIsPZXV18peqle01Q2Y+7KNKVGj8eBQutz0vA=,iv:ns+FbbJDWL2c2RYiBu64IqvDJIEgMnfOTkHZo09ihVI=,tag:MRdG/mm442G4btNOsG45WA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:sdR+LXjAM8CFsFxTZomsOo0=,iv:P/GpVvw7QPl2SCfZvSQjt+g1OhC9MxhWyihM0aPpU4c=,tag:Q0i1NzWhGwd4LtG3qnOUhw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:uMmEGRhIctWlxcLHWJkej4AdZ7WQQBZkmAP3BwhTMx/ytg==,iv:6CDd05d+DN3bT6SP5iF+xcJEnFzgJ/zdn1oEJc/9YHI=,tag:8Zo50lYt2EBR9Rtaj1bYAg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:PkrYvJoO4ZGlZ60XO+QGbHE1dhuzAeiAXVE4Ali4DRSjJg==,iv:N4geZBYkRXLbbIdp7Oq44vIsITLSkzxg38TWFi7mdn8=,tag:xtjq4TpMimz+fBeyGE8IYQ==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:a/bEdzk2fvtlR4hAVQXrcbCQjklQvqpnqk2A2fVcRWazRaF9ImKfiP6uUfcIUVlFbaPjGbRNOnPA7muW,iv:vdfG4c8OjrL9maxBXhvCt+bYP+lnjFHJMTRBfkAsld8=,tag:EVetlVwEWJnBASo9tHMIJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vknuej3pqzsyh73prl9vfng84wdcdrmcvsdvngt0lcx3hueu7c5qcg5pdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ1R4dWYvem9RdmZGYjJz
            cm9XVjJuYVYxMFhNenAvR1p5eWZ1VmZyZ3g4Cko1SmN5OWZIdTYxTU45M1QzWXFL
            V2FLWTlIYXVCUE5nVCsxb3FHcXdicm8KLS0tIGFlbnBHQm5TSGtUTFZMbm9YZFdF
            RFNOUzlITk1UbnlYVlNDc2lHVmM1c1UKCNBP3sUnEmgsglAtgRPJSuynyRtZxqr2
            8GpnY0zL3m6jHXNlieavGNwK7/gnCp4f8IMwRNx876wQo055BqAvEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T02:02:16Z"
    mac: ENC[AES256_GCM,data:VulDbkCVH/e38G/t9x/q5yI1720DV1k3lQ0ZDlyu1VF3JuBKbFaMLYq7vWn6j4kSwqkhxETKg8KKm7a6klxfFI56X/Zii22J+BHxDA4bfdWH73J/xmLvg4uGtpKqWkeYvNFd6bTf3Qb9Pdjzb3RbVYFYij22xAJZIf/NRWKuzLY=,iv:deY5ugvctn1craIGXcRcLYKX6oPwTiDLMiYOwU19VIU=,tag:PJuacxvFZHUPcQO19tJFHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
