kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:WOVRLe7AeAtQOR9WuAX+Lr7o84FLAJ5mIxoCEzXgemUzpfG5sjNbRi/+KL3QIsxaxB4nOdc=,iv:xPNOepDzBGKIV76ZxU+MgLvnx44LvxpPn3wuErm1G1M=,tag:qzmyfX4SLykB5/LBXP4O6w==,type:str]
    github_user: ENC[AES256_GCM,data:O1PBKOUkNVUaWUAx5k0=,iv:e5V5KXyEm1CbY8F7rBoUwYt+Gh2KXIN1NMm0oeIP3MY=,tag:fXIdJ0p5VTMzR2DKNDdD+g==,type:str]
    github_api_token: ENC[AES256_GCM,data:fHOr9XJDJm8n17nLWDqHxhpFS2HicBwl+nnPCbX9BBZ1ww6hzulJWA==,iv:1qwQGCtJUDlOLWInMip55tIz6AKtMYVxxtOMW8HSBok=,tag:BsdN5Ohynjn0m6g2zqEgWg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:YdtTcnLZLJQ=,iv:0yCa/DgbHKtBq0xpCbD0kqhRDinMfk+Ec1elWxzGDYQ=,tag:TzKN1aWSLoDyfX6TZvxmag==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:VVsFilT42PJ7N2GwXyf7dyDJUZ8zkeh4I38sF6H4bvzWzAXP,iv:Kz4WKrpL297pbM613F6MJL+71Heh5aqE6lvU18BZujo=,tag:9PaxsBABZnB5zJwHAvvsCA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:2pqNLiEOCpimZqMTJRd2bEN+suQOmb2tI2gRFw7N8bEZBhzW+Blx,iv:OFkM490rfKfL1mLRbYqFWUSrEPcbXljZNFeILrsj1Kc=,tag:z+B2ru8EY+R7AHYiVYlclQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:YnZleuQ=,iv:sQ6PqrK0YcqAPoXoOEWTLIh8x5uaRbGltMGBZUR5dOg=,tag:M99djMSq2qAYLRKSKw4oTg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:HKwaXzo/+lWTgJ10UuV/Vbd73LpBmIserM0=,iv:BUyhExzTnUjodn9TzU51z4PWt83JfFM8kuO8sTZzl6I=,tag:UJ6UM3Yr/uk1VOJXIKCevA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:3e1okDz+VZjTrLRPwH/EyuWMRQrJgvyvCUyo,iv:GASuT803BB699jDeOjQxV3SBgXLiw5coqIZzY+U9Gks=,tag:hhyyG/n7xPu3YqknuXc9Xg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:0W9xnvvnJA/PkHI2Wi8n7w==,iv:I2qVKjOE4YzOW343K3ziEwLwYPwdfAIud6G0oaIox5U=,tag:kmgDzbzN70xybBxmPpKKQA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:xmjGTvwKuCMSP8jyctpBNzNCCMQIWUfgwzynE9lbL5qG6zM=,iv:/i7ViWAT3od/tD0R1jbyh+MmJJ334x7AKYeq1fUcEJ0=,tag:t1r8cNAcCgZb4zdNpFeTVA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:5JRSfmUaBQfKxolEPP1GaFQC3QLV5fvxo2lhVtlI+bgqlvo=,iv:uEn5pfgcYHO5xLXgNJB3egGjCRYKCxA14hoqVl+xJI0=,tag:lnnmq9wKO7oSfTYxxD9qag==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:Hn1227OA2Mz57qDSNhtvUdJs,iv:QL1hfmMveBZkVxm3LpebfsKpzA1W9MYJBhuEkqFT7Hk=,tag:gFVAq9GSwt5TQSkCFQMvWg==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:nMkWU1k3+P6WlIftM6idAA==,iv:R/rB3ziZieO5qM3+X7/4g/gc9WhwS4jhlfbjipG26QY=,tag:NLCSMxhgd/ydpArxasGoEA==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:oFY5wObOV2Yn,iv:eCG8QSKu1dd7807Q1haMvlJ6N3x77bl0hFhEf7MjuXI=,tag:rmhYgnhh2GC+FdJ/CN5nyw==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:zEVWEJGM8XoGRR3kpH91gCncyMYP,iv:dxBvAF9FnISHhzldhGdU1e0syxvNskwtKRjuJAOvKVk=,tag:v6+n82rntbw21CO83GJH0Q==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:IDDsWb+Iv02NowjkB5KXUIACLvs=,iv:CRaFd4qiLxFjvtoxbWpOXP9UvGdkjBGsvTdiFiENkjI=,tag:PVphp5VKCuy3VKYmo1haKA==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:Mt/9cA/9NCIhduf94Ai6m/Wqm/4UNk6wYFbEyS2z9ZD0uYMwPRWMVQ==,iv:NcpdxqV4afCnZAtwAqf/Jk/rmdPoDVmF3zovP12Z1KA=,tag:0JZ6UgLp133e7pTRAmYMwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWmM4QXdSNHR3M0JzTmRV
            YlI1cDdEZU5jY0pnYVVZV1A5Q1ZTTU04RTF3CmQ5YnNBa0k0UWdZakZyUTUxU1lD
            Z20wN0E1VUFVMUEwS2NtMzJSSnBrRE0KLS0tIFpwSHZGUHMxaDNXRnZUM0ZIR2Nq
            eXNUMlNMZmxIZWhnZnVqTG1jU05DVDQKf48jc3Cuy8yG04Ox5qer8IMv6AtIWQV8
            CCFzNNxDKna2oKIyEHOrOpoADZwwiD/H+GP3DcFbQdcy0rbbQAh5qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-29T20:25:24Z"
    mac: ENC[AES256_GCM,data:7TQQWhv+KuI3metJp4koOuv8/GPNYMv+U4GG5r8VkIyUNkzKMiPO+DHmypvC7zUZvJ5bIY7/bDSbb+T/upOD/b44NUYTPOpTlg2ZI2hYqHZQ+vBSRa/X05buWpu/tzJNDS3K4QadbelyHHswFd1gpebEksvVtT2kd28js7/runU=,iv:LR6UUtDAByMMn47ffxL+IDyDK2eQT1DwHFAbUh/9DEs=,tag:3f+rsZz296G/tDRoFVglJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
