kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:9t7foFYWYuJ+yAatX6o03wJfGIyKm1d/XVxeN6X3FSWJlqAIODhR4NDX3tw44Ny2NeXWNkoEXXtP,iv:OsEUxM1h/pYpb1VthO+Viza3xefB12Fnfs+nKwl04mc=,tag:zeumgOUiMdCcGtRqh0f/dA==,type:str]
    github_user: ENC[AES256_GCM,data:Tqq4NF53a4SZYfuCYfw=,iv:ZBg/NqrMOCBYYbZGxsgNpCkjpMQqUMHxKhWT934Do+Q=,tag:CzF55QGFrPP3/NRmvbhulA==,type:str]
    github_api_token: ENC[AES256_GCM,data:DvxnJGVKh2iY8NB7K2whYqf/gbIoAPF+DAxOp1Fr90s0k7dA78073Q==,iv:7xbYZvgqbZvoppowLlUPNsigh0FRPUGE0RrW7lzUMY0=,tag:AibsjiK6K0aEd/YkN5nYKA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:fgqgKOVmHGHuC2Zh,iv:x5KxOiIW+trEoAlGcJJGX1xmRhzI9opcJ9DJWwi0PfY=,tag:EPU8JUsUgRFpssERgh9n3A==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:sNIphHEobaUPZDlk56nx,iv:XN682fXgKQxxLuA2IVKQm4jijaBdAY2Kbouzzg/q6gM=,tag:J1Iek7tv4M0U8JhkHriXEg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:VKlfK5nKdFHrsMMPcwopmsZZ0aZ649qJjzKVWkDMMaxoZZ7QCw==,iv:ISPpDS2D59K0K8WKU8kC7bOtwwLdQA143WxyLE27A0g=,tag:PtoWAS+Stj1fAcr3X6gDUg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:Hfykh9k=,iv:Hsej32Si8KltQxb8/wl+ggEL2TYEHBXBzpWoSKBo1N4=,tag:011gDJbOzm4DEM2zYckQ1A==,type:str]
    prism_central_password: ENC[AES256_GCM,data:qtIqVgPAf4kP9rM=,iv:duqE4WrRZI9AvaEcbfDIF1kV+E+mkQ5V441v+qLZB3Y=,tag:HaVk8w0N9Q6P8TEQSnXoLg==,type:str]
    objects_host: ENC[AES256_GCM,data:jXhSf/ptEutmiwJy66O7t3+o8l8aokht4M3XST+z3Minvp+oibsmR0c6,iv:kvgGihJeUn5cIGonGbGi0dRs/G3mlfTPZx2G9oabRME=,tag:HdOU99e9aErPCoTyoQMnPQ==,type:str]
    objects_port: ENC[AES256_GCM,data:kuI=,iv:oJHG0/Uq3aaRN+H9Iw7ivbEQcNWWXcNVEHeArtIIkls=,tag:2Gpla7wFatbbJM6MLlnE0w==,type:str]
    objects_region: ENC[AES256_GCM,data:4dXbyHEQ7Va8,iv:ygMcR/5GaQKxkuTP7m2iY1sTjsDFnrkuNkhJc3bUslA=,tag:bYFt0EBJpCIGuwN219/M6g==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:E3nr17U=,iv:mBERK03n7h8LORsVua+SPnFYcEQ1VQ08P+D1bjiq5Uk=,tag:aotVCgwtnTCMVOlQoTccDw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:tL076uOP3gGMAkGcHQ0QNhAx+GFL7xJPdh0jQD7dP0g=,iv:glTSd2V4nnooQPtGyJZFuChUQbRrmVAlicCR0tc9sCs=,tag:NYwowEYIlG/rfwZHA97Yfg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:ESxeAOuE4DnhHvctu/2dng7t1KCXRX3FEEHTAgdY6QU=,iv:sZwIcjx/X14GJFAXCZ6OvTY0re65y2CkAX1G0O5bfi0=,tag:/p8OV1WbiATlNauZIabpNQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:Sev6NJpn3ovl8OCpxXdkrE5rprKFLLHMkQ==,iv:FQpIo2aP3yp7orpUwfQI+nOt0EiJ6SN/zgB1fzteU1s=,tag:NIol1O4HTfKXMzISbLvZFw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:vdjTsIPm38U5luJF7/1n,iv:q9I5dnNTyF0gmwyr5c7tGGyAi2P8G3mr9SGdx5lPFZs=,tag:9ej7A59XoC7/+tRtynPEgA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:6P+9+vvmhuM0lTOv+Px+9EmWKJimT5PcGlebeQ8BCI0=,iv:KaYUNmakOYsKrHPUfQsNE9Kl/lqWwvAqiG9TRCxzsL4=,tag:ddSTDOgtRlewB0LMCUdeaQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:85gLiWSqAqqSnjBn/Ow0B3h67KUUudoMjROQS7NqMnA=,iv:XFBcI3U65xTYiW7Ic7ClVGlfA2gdnjyrcV4Sp9Ammgo=,tag:C7I4FZTGbFx9irbHrK6nSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akw20gxdussq8503jml0ccy64vywysc56t66sygs3ktflsgzsf9s2mzpcz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d0hCZUduTlEyL1dTeERs
            Si85NUdLKytuR2xiQ1ZUYVdsVUdOUkhTL2xZCmpVSlRpYzYxekEvMTUvekNVdVpy
            bC9hak5pa2J1anRpQ09PTUNKNXd4Wk0KLS0tIGRkYkdKZktHOEFTMUtVbFA3akpu
            M3VOeS9YZTNJdmxJVENEY0JLZkRqdlkKKM9bz/cQ0y+X7Q1WDZl7YQBKXoTOxIY4
            awXVJGJBaVXsV7042P21OSaSHGy5qoDOHAp8WWke4M1EYizchWsJjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T14:43:20Z"
    mac: ENC[AES256_GCM,data:VX3JbQJ/6jK8UtS0mNUVbFG8bZYR8zxt0eeJddj55sf2+cpSPOixL5aiuLJsyR10UfI3EwaBmoJuuxLgfDyZkuxNrM5jY+okH/vvTiALjV/dSuQLsjg0PwTvfgpS+mB4G5oUZ7dnYwKk6zFMaMlLo6sECeTCi4rkr6DmJvmxNmI=,iv:jYo+aS/YEyEg+zQnnkgGhbYoy9dN7krE0wlQWfNPewA=,tag:X2LfQ7PIa/6JAZMmGYe20A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
