kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:CfX55bRLmoJ+z2KHm/WaM7The4cs3Vk0idIZTwzMoFXU8KBT4epN5m8jHp0zhGAdyUWDFHfn+uYI,iv:N9vsg3M5dEhPNqOV5zRSL7bpduCks19eFH40WK6mm3c=,tag:XaAywU273PiKqa9NEJvR+g==,type:str]
    github_user: ENC[AES256_GCM,data:2wcYlYaJSICglnbns6Y=,iv:gnn1ao6eLrPhitRAn2u/oZ9wpq2fDY+r4jmCFy0LFUM=,tag:3xFY2FRdCrEJKRTNcoH8hA==,type:str]
    github_api_token: ENC[AES256_GCM,data:mFVyxm8i0ZWyDpjLjNE2dop93y2n1BKHVq6EF/RLSCaaGaGITykTCQ==,iv:BB+dmbzaX6JuRqp5ClSRXwhGmMHeU+M64NxRkDHGWAU=,tag:bYhN8IfEWWgqeJfWmzO+lg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:VyyCwEzaSlNbbucG,iv:dJRF0lV5sdV8l419UjFBWGTkI7XJuAxHjXVJkT+jgHQ=,tag:seleajmrGK+5o7E5CRbTiw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:gxPOf5ZpfCFyjsYfT8B2,iv:sGeeezSzRpvw46YPD6SUhWhGWX1b9R+/A8+wqpP2BKk=,tag:+bHhl/H7RVC4PvChFntxYg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:O32UMvLeIJjTTb3r5sKPmh778LPKngM1FMzVBi0lA9ek9m7UpQ==,iv:b+wqk+XtgPhp9xQR2j9KlCHPAO59WaIMyvkVR9lF1C8=,tag:eXzGvCzcvW2PYvgASErUsA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:QmJNJuo=,iv:fyynfKljyC0Iz4XbLcwmZJIQSYNk0YVrUJpXjv6oRyw=,tag:l4ct0x4ViA+dM1BZAWQm4A==,type:str]
    prism_central_password: ENC[AES256_GCM,data:wpPunrGxkcoNNqo=,iv:gyDAAMaNwkDTlOPDDz0QlHbldOFK1E7mMS7WIPAZiWo=,tag:ESOT2Vx0QS30/n3qq8O/1w==,type:str]
    objects_host: ENC[AES256_GCM,data:oPUNLqWuEzhEOg0Ozc93IiPjzb7LyaNv8sb+au/YX6Rwr85+jYH1FrRF,iv:AvXZdbkmCOIMs0EH0ZrIcuw+1mYOWmCdf2cNNHZgFy4=,tag:dRL4sJFXO8KazBc4BaETZA==,type:str]
    objects_port: ENC[AES256_GCM,data:1Ww=,iv:xbTAshHl/Aif10TG4Od4Z1kO3q0fNzwgYGlTMbpQ5WY=,tag:YVBUyCRjvMg5l1GMyJCXbg==,type:str]
    objects_region: ENC[AES256_GCM,data:QbP11UYBmMTY,iv:VmItk04Cwi9AUofpg/aEb96gw7tkn+wAF0mYeaQp52o=,tag:sLDHHTYq/ndDExQq1xEB3g==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:jHEBcQ8=,iv:THU9RPuJWcOzEL7uWHmmtMoz7apPmUb/n+hpalVKGPo=,tag:vh43nhFCc3EgkyJ2xLEXmQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:clSXpISDJngpUcmzuIeLs9YQgJ/5KR6ychSPaPEnuyg=,iv:Fa9jlRDR4Xk8XOWTm7gQb5ksBJH/3mi5yxnZkVE602g=,tag:E29dTzI7vxRTgu+5Vx2HXg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:NPN4zJrMF+7j5WwnrdZaW/DnuFO/Awaai0dmoJfnUQA=,iv:gobGf2L/IGAlaGcDwJb0QxOJsPU78bzwTEQdcdQ+4XE=,tag:u+Xg9NvIuDoI/ugOM3aN9w==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:zdT6G+UICZyf3ajPnxmsYhyumxiwyeZRsw==,iv:rmouuUmp7yLRTtcwANXQNp2npbaunb+wlDX0IeplAA4=,tag:MKFAGoohnjYvqB64JYia3Q==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:wd32YYv2Ke5xEYMkuuuT,iv:19fG4D85dui1ZRMAcAjcXeVtFBug8kTzRAMNYKIxSWA=,tag:2FMzBSaBfN/s8bntpu0nlg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:mFhzO5vS05j1/vPmaKWwVCxMHhcYHf7PH8ZYaK5uNAg=,iv:+eXhhCXLyfuHEj6JxBIkOaapoYdkRmZIVJ15O8t0/7c=,tag:pbhSOE8xnaO6QN3dKc26Kg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:juiWIdLiCg7+VXTn0QPXx+h+wGCMw1D1j1TIXkxa8Ys=,iv:+bP1MzLaZcHv4/Ew7OMwD6oF3WB3U3HnQZNWpp0lbVE=,tag:DIZ+gvxviLlvDNjgXgXDmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1akw20gxdussq8503jml0ccy64vywysc56t66sygs3ktflsgzsf9s2mzpcz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVHZnVzg2SGpFWk5jUi9W
            bWkrTk9Jb21RN2o5RmI2NnA5Y040NXdmckJBCk8rSldtRWp5K2tvVThNQTBRd2RH
            cFltRE10ajRyeC9KTFR2Yk54VUhYQW8KLS0tIHdGMDZBUlRRT3hKWEVibTBDemxm
            RUQ4UVBIaDRiYnRGRWZuQU55VVJPWVUK4okc7+yx7VKHAS+qsaywzjF1XU2Nwssl
            gm0hf/QoN5+w4+yymWqAu4GisgUj8FZ/QU3qLaaJrns87C+XCzLICw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T14:44:51Z"
    mac: ENC[AES256_GCM,data:00t63dQD/ggXXKMbdxtT0w06D+TlcpARM285o8Ho36528/wzHMGmLD8qDMpSyNWYO5EIPDSJPi5AKGxky5Y73cJGT5hQ7xmuJfm3nugFAmbW9tGxxcAf6Onvzb4D60QEgLv2USlY16lf22i2GXfVbt9mtmdN/hbV7DWcd0RtLCE=,iv:d8PHp4R44HVvC+xkvVVeVVbaiIuV3i25MtpgujXUMKQ=,tag:92zcdKRGxgqWti5LDDtrDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
