apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptrace
  namespace: flux-system
spec:
  values:
    postgresql:
      imagePullSecrets:
      - name: docker-hub-regcred
    clickhouse:
      imagePullSecrets:
      - name: docker-hub-regcred
