apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  values:
    app:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
        - gitops.${wildcard_ingress_subdomain}
        className: nginx
        secretName: weave-gitops-certs
        issuer:
          name: letsencrypt
          scope: cluster
