apiVersion: v1
kind: ConfigMap
metadata:
  name: config-features
  annotations:
    kustomize.toolkit.fluxcd.io/force: disabled
  namespace: knative-serving
data:
  kubernetes.podspec-tolerations: "enabled"
