apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  application-crd-id: kubeflow-pipelines
images:
- name: gcr.io/ml-pipeline/api-server
  newName: quay.io/ajaynagar/kubeflow-ntnx/kfp-backend
  newTag: 2.0.3
- name: gcr.io/ml-pipeline/frontend
  newName: quay.io/ajaynagar/kubeflow-ntnx/kfp-frontend
  newTag: 2.0.3
- name: gcr.io/ml-pipeline/metadata-writer
  newName: quay.io/ajaynagar/kubeflow-ntnx/kfp-metadata-writer
  newTag: 2.0.3
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- ntnx-config-patch.yaml
resources:
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pipeline/upstream/base/installs/multi-user
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pipeline/upstream/base/metadata/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pipeline/upstream/base/metadata/options/istio
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pipeline/upstream/third-party/argo/installs/cluster
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pipeline/upstream/third-party/mysql/base
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pipeline/upstream/third-party/mysql/options/istio
- localized-files/github.com/kubeflow/manifests/v1.8.1/apps/pipeline/upstream/third-party/metacontroller/base
- pipeline-install-config.yaml
- workflow-controller-configmap.yaml
- ml-pipeline-ui-configmap.yaml
- kubeflow-pipelines-profile-controller-code.yaml
- mlpipeline-minio-artifact-secret.yaml
